---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: Die innerhalb des StorageGRID -Systems ausgetauschten Prüfnachrichten enthalten für alle Nachrichten gemeinsame Standardinformationen und spezifische Inhalte, die das gemeldete Ereignis oder die gemeldete Aktivität beschreiben. 
---
= Format der Prüfnachricht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die innerhalb des StorageGRID -Systems ausgetauschten Prüfnachrichten enthalten für alle Nachrichten gemeinsame Standardinformationen und spezifische Inhalte, die das gemeldete Ereignis oder die gemeldete Aktivität beschreiben.

Wenn die zusammenfassenden Informationen derlink:using-audit-explain-tool.html["Audit-Erklärung"] Undlink:using-audit-sum-tool.html["Auditsumme"] Wenn die Tools nicht ausreichen, lesen Sie diesen Abschnitt, um das allgemeine Format aller Prüfmeldungen zu verstehen.

Nachfolgend sehen Sie ein Beispiel für eine Audit-Meldung, wie sie in der Audit-Protokolldatei erscheinen könnte:

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Jede Prüfnachricht enthält eine Zeichenfolge von Attributelementen.  Die gesamte Zeichenfolge ist in Klammern eingeschlossen(`[ ]` ), und jedes Attributelement in der Zeichenfolge weist die folgenden Eigenschaften auf:

* In Klammern eingeschlossen `[ ]`
* Eingeführt durch die Zeichenfolge `AUDT` , was auf eine Prüfmeldung hinweist
* Ohne Trennzeichen (keine Kommas oder Leerzeichen) davor oder danach
* Beendet durch ein Zeilenvorschubzeichen `\n`


Jedes Element enthält einen Attributcode, einen Datentyp und einen Wert, die in diesem Format gemeldet werden:

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
Die Anzahl der Attributelemente in der Nachricht hängt vom Ereignistyp der Nachricht ab.  Die Attributelemente sind in keiner bestimmten Reihenfolge aufgelistet.

Die folgende Liste beschreibt die Attributelemente:

* `ATTR`ist ein vierstelliger Code für das gemeldete Attribut.  Es gibt einige Attribute, die allen Prüfmeldungen gemeinsam sind, und andere, die ereignisspezifisch sind.
* `type`ist eine vierstellige Kennung des Programmierdatentyps des Werts, z. B. UI64, FC32 usw.  Der Typ ist in Klammern eingeschlossen `( )` .
* `value`ist der Inhalt des Attributs, normalerweise ein numerischer oder Textwert.  Auf Werte folgt immer ein Doppelpunkt(`:` ).  Werte des Datentyps CSTR sind in doppelte Anführungszeichen " " eingeschlossen.

