---
permalink: audit/audit-messages-main.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message 
summary: Detaillierte Beschreibungen der vom System zurückgegebenen Prüfmeldungen finden Sie in den folgenden Abschnitten.  Jede Prüfnachricht wird zunächst in einer Tabelle aufgelistet, in der verwandte Nachrichten nach der Aktivitätsklasse gruppiert werden, die die Nachricht darstellt.  Diese Gruppierungen sind sowohl für das Verständnis der überwachten Aktivitätstypen als auch für die Auswahl des gewünschten Typs der Überwachungsnachrichtenfilterung nützlich. 
---
= Beschreibungen der Prüfnachrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Detaillierte Beschreibungen der vom System zurückgegebenen Prüfmeldungen finden Sie in den folgenden Abschnitten.  Jede Prüfnachricht wird zunächst in einer Tabelle aufgelistet, in der verwandte Nachrichten nach der Aktivitätsklasse gruppiert werden, die die Nachricht darstellt.  Diese Gruppierungen sind sowohl für das Verständnis der überwachten Aktivitätstypen als auch für die Auswahl des gewünschten Typs der Überwachungsnachrichtenfilterung nützlich.

Die Prüfmeldungen werden außerdem alphabetisch nach ihren vierstelligen Codes aufgelistet.  Diese alphabetische Liste ermöglicht es Ihnen, Informationen zu bestimmten Nachrichten zu finden.

Die in diesem Kapitel verwendeten vierstelligen Codes sind die ATYP-Werte, die in den Prüfmeldungen zu finden sind, wie in der folgenden Beispielmeldung gezeigt:

[listing, subs="specialcharacters,quotes"]
----
2014-07-17T03:50:47.484627
\[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][*ATYP\(FC32\):SYSU*][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Informationen zum Festlegen von Audit-Meldungsebenen, zum Ändern von Protokollzielen und zur Verwendung eines externen Syslog-Servers für Ihre Audit-Informationen finden Sie unterlink:../monitor/configure-audit-messages.html["Konfigurieren von Überwachungsmeldungen und Protokollzielen"]
