---
permalink: audit/audit-log-file-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file formats, log formats, log file format, log format 
summary: Die Audit-Protokolldateien befinden sich auf jedem Admin-Knoten und enthalten eine Sammlung einzelner Audit-Meldungen. 
---
= Audit-Protokolldateiformat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Audit-Protokolldateien befinden sich auf jedem Admin-Knoten und enthalten eine Sammlung einzelner Audit-Meldungen.

Jede Prüfnachricht enthält Folgendes:

* Die koordinierte Weltzeit (UTC) des Ereignisses, das die Prüfnachricht ausgelöst hat (ATIM) im ISO 8601-Format, gefolgt von einem Leerzeichen:
+
`_YYYY-MM-DDTHH:MM:SS.UUUUUU_`, Wo `_UUUUUU_` sind Mikrosekunden.

* Die Prüfnachricht selbst, eingeschlossen in eckige Klammern und beginnend mit `AUDT` .


Das folgende Beispiel zeigt drei Audit-Meldungen in einer Audit-Protokolldatei (Zeilenumbrüche zur besseren Lesbarkeit hinzugefügt).  Diese Nachrichten wurden generiert, als ein Mandant einen S3-Bucket erstellte und diesem Bucket zwei Objekte hinzufügte.

[listing]
----
2019-08-07T18:43:30.247711
[AUDT:[RSLT(FC32):SUCS][CNID(UI64):1565149504991681][TIME(UI64):73520][SAIP(IPAD):"10.224.2.255"][S3AI(CSTR):"17530064241597054718"]
[SACC(CSTR):"s3tenant"][S3AK(CSTR):"SGKH9100SCkNB8M3MTWNt-PhoTDwB9JOk7PtyLkQmA=="][SUSR(CSTR):"urn:sgws:identity::17530064241597054718:root"]
[SBAI(CSTR):"17530064241597054718"][SBAC(CSTR):"s3tenant"][S3BK(CSTR):"bucket1"][AVER(UI32):10][ATIM(UI64):1565203410247711]
[ATYP(FC32):SPUT][ANID(UI32):12454421][AMID(FC32):S3RQ][ATID(UI64):7074142142472611085]]

2019-08-07T18:43:30.783597
[AUDT:[RSLT(FC32):SUCS][CNID(UI64):1565149504991696][TIME(UI64):120713][SAIP(IPAD):"10.224.2.255"][S3AI(CSTR):"17530064241597054718"]
[SACC(CSTR):"s3tenant"][S3AK(CSTR):"SGKH9100SCkNB8M3MTWNt-PhoTDwB9JOk7PtyLkQmA=="][SUSR(CSTR):"urn:sgws:identity::17530064241597054718:root"]
[SBAI(CSTR):"17530064241597054718"][SBAC(CSTR):"s3tenant"][S3BK(CSTR):"bucket1"][S3KY(CSTR):"fh-small-0"]
[CBID(UI64):0x779557A069B2C037][UUID(CSTR):"94BA6949-38E1-4B0C-BC80-EB44FB4FCC7F"][CSIZ(UI64):1024][AVER(UI32):10]
[ATIM(UI64):1565203410783597][ATYP(FC32):SPUT][ANID(UI32):12454421][AMID(FC32):S3RQ][ATID(UI64):8439606722108456022]]

2019-08-07T18:43:30.784558
[AUDT:[RSLT(FC32):SUCS][CNID(UI64):1565149504991693][TIME(UI64):121666][SAIP(IPAD):"10.224.2.255"][S3AI(CSTR):"17530064241597054718"]
[SACC(CSTR):"s3tenant"][S3AK(CSTR):"SGKH9100SCkNB8M3MTWNt-PhoTDwB9JOk7PtyLkQmA=="][SUSR(CSTR):"urn:sgws:identity::17530064241597054718:root"]
[SBAI(CSTR):"17530064241597054718"][SBAC(CSTR):"s3tenant"][S3BK(CSTR):"bucket1"][S3KY(CSTR):"fh-small-2000"]
[CBID(UI64):0x180CBD8E678EED17][UUID(CSTR):"19CE06D0-D2CF-4B03-9C38-E578D66F7ADD"][CSIZ(UI64):1024][AVER(UI32):10]
[ATIM(UI64):1565203410784558][ATYP(FC32):SPUT][ANID(UI32):12454421][AMID(FC32):S3RQ][ATID(UI64):13489590586043706682]]
----
In ihrem Standardformat sind die Prüfmeldungen in den Prüfprotokolldateien nicht einfach zu lesen oder zu interpretieren.  Sie können dielink:using-audit-explain-tool.html["Audit-Erklärtool"] um vereinfachte Zusammenfassungen der Audit-Meldungen im Audit-Protokoll zu erhalten.  Sie können dielink:using-audit-sum-tool.html["Auditsummen-Tool"] um zusammenzufassen, wie viele Schreib-, Lese- und Löschvorgänge protokolliert wurden und wie lange diese Vorgänge dauerten.
