---
permalink: audit/ilm-audit-messages.html 
sidebar: sidebar 
keywords: audit messages, ILM, IDEL, LKCU, ORLM 
summary: Die Prüfmeldungen der ILM-Prüfkategorie werden für Ereignisse im Zusammenhang mit Vorgängen im Informationslebenszyklus verwendet. 
---
= ILM-Audit-Meldungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Prüfmeldungen der Kategorie „ILM-Prüfung“ werden für Ereignisse im Zusammenhang mit Vorgängen im Zusammenhang mit dem Information Lifecycle Management (ILM) verwendet.

[cols="1a,3a,1a"]
|===
| Code | Nachrichtentitel und -beschreibung | Siehe 


 a| 
IDEL
 a| 
Von ILM initiiertes Löschen: Diese Prüfmeldung wird generiert, wenn ILM den Löschvorgang eines Objekts startet.
 a| 
link:idel-ilm-initiated-delete.html["IDEL: Von ILM initiiertes Löschen"]



 a| 
LKCU
 a| 
Bereinigung überschriebener Objekte.  Diese Prüfmeldung wird generiert, wenn ein überschriebenes Objekt automatisch entfernt wird, um Speicherplatz freizugeben.
 a| 
link:lkcu-overwritten-object-cleanup.html["LKCU: Bereinigung überschriebener Objekte"]



 a| 
ORLM
 a| 
Objektregeln erfüllt: Diese Prüfmeldung wird generiert, wenn Objektdaten gemäß den ILM-Regeln gespeichert werden.
 a| 
link:orlm-object-rules-met.html["ORLM: Objektregeln erfüllt"]

|===