---
permalink: audit/llst-location-lost.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LLST, Location Lost 
summary: 'Diese Meldung wird immer dann generiert, wenn ein Speicherort für eine Objektkopie \(repliziert oder löschcodiert\) nicht gefunden werden kann.' 
---
= LLST: Standort verloren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Nachricht wird generiert, wenn kein Speicherort für eine Objektkopie (repliziert oder löschcodiert) gefunden werden kann.

[cols="1a,1a,4a"]
|===
| Code | Feld | Beschreibung 


 a| 
CBIL
 a| 
CBID
 a| 
Das betroffene CBID.



 a| 
ECPR
 a| 
Erasure-Coding-Profil
 a| 
Für löschcodierte Objektdaten.  Die ID des verwendeten Erasure-Coding-Profils.



 a| 
LTYP
 a| 
Ortstyp
 a| 
CLDI (Online): Für replizierte Objektdaten

CLEC (Online): Für erasure-coded Objektdaten

CLNL (Nearline): Für archivierte replizierte Objektdaten



 a| 
NOID
 a| 
Quellknoten-ID
 a| 
Die Knoten-ID, auf der die Standorte verloren gegangen sind.



 a| 
PCLD
 a| 
Pfad zum replizierten Objekt
 a| 
Der vollständige Pfad zum Speicherort der verlorenen Objektdaten auf der Festplatte.  Wird nur zurückgegeben, wenn LTYP den Wert CLDI hat (d. h. für replizierte Objekte).

Nimmt die Form an `/var/local/rangedb/2/p/13/13/00oJs6X%{h{U)SeUFxE@`



 a| 
RSLT
 a| 
Ergebnis
 a| 
Immer KEINE.  RSLT ist ein obligatorisches Nachrichtenfeld, für diese Nachricht jedoch nicht relevant.  Damit diese Nachricht nicht gefiltert wird, wird NONE anstelle von SUCS verwendet.



 a| 
TSRC
 a| 
Auslösende Quelle
 a| 
USER: Vom Benutzer ausgelöst

SYST: System ausgelöst



 a| 
UUID
 a| 
Universell eindeutige ID
 a| 
Die Kennung des betroffenen Objekts im StorageGRID -System.

|===