---
permalink: audit/object-ingest-transactions.html 
sidebar: sidebar 
keywords: object ingest transaction, S3 ingest, SPUT, ORLM, WPUT 
summary: Sie können Client-Ingest-Transaktionen im Prüfprotokoll identifizieren, indem Sie S3-API-spezifische Prüfmeldungen suchen. 
---
= Objektaufnahmetransaktionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Client-Ingest-Transaktionen im Prüfprotokoll identifizieren, indem Sie S3-API-spezifische Prüfmeldungen suchen.

In den folgenden Tabellen sind nicht alle während einer Aufnahmetransaktion generierten Prüfmeldungen aufgeführt. Es sind nur die Nachrichten enthalten, die zum Verfolgen der Aufnahmetransaktion erforderlich sind.



== S3-Ingest-Audit-Nachrichten

[cols="1a,1a,2a,1a,2a"]
|===
| Code | Name | Beschreibung | Verfolgen | Siehe 


 a| 
SPUT
 a| 
S3 PUT-Transaktion
 a| 
Eine S3 PUT-Ingest-Transaktion wurde erfolgreich abgeschlossen.
 a| 
CBID, S3BK, S3KY
 a| 
link:sput-s3-put.html["SPUT: S3 PUT"]



 a| 
ORLM
 a| 
Objektregeln erfüllt
 a| 
Die ILM-Richtlinie wurde für dieses Objekt erfüllt.
 a| 
CBID
 a| 
link:orlm-object-rules-met.html["ORLM: Objektregeln erfüllt"]

|===


== Swift erfasst Audit-Nachrichten

[cols="1a,1a,2a,1a,2a"]
|===
| Code | Name | Beschreibung | Verfolgen | Siehe 


 a| 
WPUT
 a| 
Schnelle PUT-Transaktion
 a| 
Eine Swift PUT-Ingest-Transaktion wurde erfolgreich abgeschlossen.
 a| 
CBID, WCON, WOBJ
 a| 
link:wput-swift-put.html["WPUT: Schnelles PUT"]



 a| 
ORLM
 a| 
Objektregeln erfüllt
 a| 
Die ILM-Richtlinie wurde für dieses Objekt erfüllt.
 a| 
CBID
 a| 
link:orlm-object-rules-met.html["ORLM: Objektregeln erfüllt"]

|===


== Beispiel: S3-Objektaufnahme

Die folgende Reihe von Prüfmeldungen ist ein Beispiel für die Prüfmeldungen, die generiert und im Prüfprotokoll gespeichert werden, wenn ein S3-Client ein Objekt in einen Speicherknoten (LDR-Dienst) einspeist.

In diesem Beispiel enthält die aktive ILM-Richtlinie die ILM-Regel „2 Kopien erstellen“.


NOTE: Im folgenden Beispiel sind nicht alle während einer Transaktion generierten Prüfmeldungen aufgeführt.  Es werden nur diejenigen aufgelistet, die sich auf die S3-Ingest-Transaktion (SPUT) beziehen.

In diesem Beispiel wird davon ausgegangen, dass zuvor ein S3-Bucket erstellt wurde.



=== SPUT: S3 PUT

Die SPUT-Nachricht wird generiert, um anzuzeigen, dass eine S3 PUT-Transaktion ausgegeben wurde, um ein Objekt in einem bestimmten Bucket zu erstellen.

[listing, subs="specialcharacters,quotes"]
----
2017-07-17T21:17:58.959669[AUDT:[RSLT(FC32):SUCS][TIME(UI64):25771][SAIP(IPAD):"10.96.112.29"][S3AI(CSTR):"70899244468554783528"][SACC(CSTR):"test"][S3AK(CSTR):"SGKHyalRU_5cLflqajtaFmxJn946lAWRJfBF33gAOg=="][SUSR(CSTR):"urn:sgws:identity::70899244468554783528:root"][SBAI(CSTR):"70899244468554783528"][SBAC(CSTR):"test"][S3BK(CSTR):"example"][S3KY(CSTR):"testobject-0-3"][CBID\(UI64\):0x8EF52DF8025E63A8][CSIZ(UI64):30720][AVER(UI32):10][ATIM(UI64):150032627859669][ATYP\(FC32\):SPUT][ANID(UI32):12086324][AMID(FC32):S3RQ][ATID(UI64):14399932238768197038]]
----


=== ORLM: Objektregeln erfüllt

Die ORLM-Nachricht gibt an, dass die ILM-Richtlinie für dieses Objekt erfüllt wurde.  Die Nachricht enthält die CBID des Objekts und den Namen der angewendeten ILM-Regel.

Bei replizierten Objekten enthält das LOCS-Feld die LDR-Knoten-ID und die Volume-ID der Objektstandorte.

[listing, subs="specialcharacters,quotes"]
----
2019-07-17T21:18:31.230669[AUDT:[CBID\(UI64\):0x50C4F7AC2BC8EDF7][RULE(CSTR):"Make 2 Copies"][STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"0B344E18-98ED-4F22-A6C8-A93ED68F8D3F"][LOCS(CSTR):"CLDI 12828634 2148730112, CLDI 12745543 2147552014"][RSLT(FC32):SUCS][AVER(UI32):10][ATYP\(FC32\):ORLM][ATIM(UI64):1563398230669][ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
Bei Erasure-Coding-Objekten enthält das LOCS-Feld die Erasure-Coding-Profil-ID und die Erasure-Coding-Gruppen-ID

[listing, subs="specialcharacters,quotes"]
----
2019-02-23T01:52:54.647537 [AUDT:[CBID(UI64):0xFA8ABE5B5001F7E2][RULE(CSTR):"EC_2_plus_1"][STAT(FC32):DONE][CSIZ(UI64):10000][UUID(CSTR):"E291E456-D11A-4701-8F51-D2F7CC9AFECA"][LOCS(CSTR):"CLEC 1 A471E45D-A400-47C7-86AC-12E77F229831"][RSLT(FC32):SUCS][AVER(UI32):10][ATIM(UI64):1550929974537]\[ATYP\(FC32\):ORLM\][ANID(UI32):12355278][AMID(FC32):ILMX][ATID(UI64):4168559046473725560]]
----
Das PATH-Feld enthält S3-Bucket- und Schlüsselinformationen oder Swift-Container- und Objektinformationen, je nachdem, welche API verwendet wurde.

[listing]
----
2019-09-15.txt:2018-01-24T13:52:54.131559 [AUDT:[CBID(UI64):0x82704DFA4C9674F4][RULE(CSTR):"Make 2 Copies"][STAT(FC32):DONE][CSIZ(UI64):3145729][UUID(CSTR):"8C1C9CAC-22BB-4880-9115-CE604F8CE687"][PATH(CSTR):"frisbee_Bucket1/GridDataTests151683676324774_1_1vf9d"][LOCS(CSTR):"CLDI 12525468, CLDI 12222978"][RSLT(FC32):SUCS][AVER(UI32):10][ATIM(UI64):1568555574559][ATYP(FC32):ORLM][ANID(UI32):12525468][AMID(FC32):OBDI][ATID(UI64):344833886538369336]]
----