---
permalink: audit/sput-s3-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SPUT, S3 PUT 
summary: Wenn ein S3-Client eine PUT-Transaktion ausgibt, wird eine Anforderung zum Erstellen eines neuen Objekts oder Buckets gestellt.  Diese Nachricht wird vom Server ausgegeben, wenn die Transaktion erfolgreich war. 
---
= SPUT: S3 PUT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein S3-Client eine PUT-Transaktion ausgibt, wird eine Anforderung zum Erstellen eines neuen Objekts oder Buckets oder zum Entfernen einer Bucket-/Objekt-Unterressource gestellt.  Diese Nachricht wird vom Server ausgegeben, wenn die Transaktion erfolgreich war.

[cols="1a,1a,4a"]
|===
| Code | Feld | Beschreibung 


 a| 
CBID
 a| 
Inhaltsblockkennung
 a| 
Die eindeutige Kennung des angeforderten Inhaltsblocks.  Wenn die CBID unbekannt ist, wird dieses Feld auf 0 gesetzt.  Operationen an Buckets schließen dieses Feld nicht ein.



 a| 
CMPS
 a| 
Compliance-Einstellungen
 a| 
Die beim Erstellen des Buckets verwendeten Compliance-Einstellungen, sofern in der Anfrage vorhanden (auf die ersten 1024 Zeichen gekürzt).



 a| 
CNCH
 a| 
Konsistenzkontrollkopf
 a| 
Der Wert des HTTP-Anforderungsheaders „Consistency-Control“, sofern in der Anforderung vorhanden.



 a| 
CNID
 a| 
Verbindungskennung
 a| 
Die eindeutige Systemkennung für die TCP/IP-Verbindung.



 a| 
CSIZ
 a| 
Inhaltsgröße
 a| 
Die Größe des abgerufenen Objekts in Bytes.  Operationen an Buckets schließen dieses Feld nicht ein.



 a| 
GFID
 a| 
Grid Federation-Verbindungs-ID
 a| 
Die Verbindungs-ID der Grid-Föderationsverbindung, die einer PUT-Anforderung für die Grid-übergreifende Replikation zugeordnet ist.  Nur in Prüfprotokollen im Zielraster enthalten.



 a| 
GFSA
 a| 
Grid Federation-Quellkonto-ID
 a| 
Die Konto-ID des Mandanten im Quellraster für eine PUT-Anforderung zur rasterübergreifenden Replikation.  Nur in Prüfprotokollen im Zielraster enthalten.



 a| 
HTRH
 a| 
HTTP-Anforderungsheader
 a| 
Liste der protokollierten HTTP-Anforderungsheadernamen und -werte, wie während der Konfiguration ausgewählt.

 `X-Forwarded-For`wird automatisch eingefügt, wenn es in der Anfrage vorhanden ist und wenn die `X-Forwarded-For` Der Wert unterscheidet sich von der IP-Adresse des Anforderungsabsenders (SAIP-Auditfeld).

`x-amz-bypass-governance-retention`wird automatisch eingefügt, wenn es in der Anfrage vorhanden ist.



 a| 
LKEN
 a| 
Objektsperre aktiviert
 a| 
Wert des Anforderungsheaders `x-amz-bucket-object-lock-enabled` , falls in der Anfrage vorhanden.



 a| 
LKLH
 a| 
Objektsperre – Rechtliche Aufbewahrung
 a| 
Wert des Anforderungsheaders `x-amz-object-lock-legal-hold` , falls in der PutObject-Anforderung vorhanden.



 a| 
LKMD
 a| 
Objektsperr-Aufbewahrungsmodus
 a| 
Wert des Anforderungsheaders `x-amz-object-lock-mode` , falls in der PutObject-Anforderung vorhanden.



 a| 
LKRU
 a| 
Objektsperre – Aufbewahrung bis Datum
 a| 
Wert des Anforderungsheaders `x-amz-object-lock-retain-until-date` , falls in der PutObject-Anforderung vorhanden.  Die Werte sind auf einen Zeitraum von 100 Jahren ab dem Datum der Einnahme des Objekts begrenzt.



 a| 
MTME
 a| 
Letzte Änderung
 a| 
Der Unix-Zeitstempel in Mikrosekunden, der angibt, wann das Objekt zuletzt geändert wurde.



 a| 
RSLT
 a| 
Ergebniscode
 a| 
Ergebnis der PUT-Transaktion.  Ergebnis ist immer:

SUCS: Erfolgreich



 a| 
S3AI
 a| 
S3-Mandantenkonto-ID (Absender der Anfrage)
 a| 
Die Mandantenkonto-ID des Benutzers, der die Anfrage gesendet hat.  Ein leerer Wert zeigt einen anonymen Zugriff an.



 a| 
S3AK
 a| 
S3-Zugriffsschlüssel-ID (Absender der Anfrage)
 a| 
Die gehashte S3-Zugriffsschlüssel-ID für den Benutzer, der die Anfrage gesendet hat.  Ein leerer Wert zeigt einen anonymen Zugriff an.



 a| 
S3BK
 a| 
S3-Bucket
 a| 
Der Name des S3-Buckets.



 a| 
S3KY
 a| 
S3-Schlüssel
 a| 
Der S3-Schlüsselname, ohne den Bucket-Namen.  Operationen an Buckets schließen dieses Feld nicht ein.



 a| 
S3SR
 a| 
S3-Unterressource
 a| 
Der Bucket oder die Objekt-Subressource, an der gearbeitet wird, falls zutreffend.



 a| 
SACC
 a| 
S3-Mandantenkontoname (Absender der Anfrage)
 a| 
Der Name des Mandantenkontos des Benutzers, der die Anfrage gesendet hat.  Leer für anonyme Anfragen.



 a| 
SAIP
 a| 
IP-Adresse (Absender der Anfrage)
 a| 
Die IP-Adresse der Clientanwendung, die die Anfrage gestellt hat.



 a| 
SBAC
 a| 
S3-Mandantenkontoname (Bucket-Eigentümer)
 a| 
Der Mandantenkontoname für den Bucket-Eigentümer.  Wird verwendet, um kontoübergreifenden oder anonymen Zugriff zu identifizieren.



 a| 
SBAI
 a| 
S3-Mandantenkonto-ID (Bucket-Eigentümer)
 a| 
Die Mandantenkonto-ID des Eigentümers des Ziel-Buckets.  Wird verwendet, um kontoübergreifenden oder anonymen Zugriff zu identifizieren.



 a| 
SRCF
 a| 
Unterressourcenkonfiguration
 a| 
Die neue Unterressourcenkonfiguration (auf die ersten 1024 Zeichen gekürzt).



 a| 
SUSR
 a| 
S3-Benutzer-URN (Absender der Anfrage)
 a| 
Die Mandantenkonto-ID und der Benutzername des Benutzers, der die Anfrage stellt.  Der Benutzer kann entweder ein lokaler Benutzer oder ein LDAP-Benutzer sein. Beispiel:  `urn:sgws:identity::03393893651506583485:root`

Leer für anonyme Anfragen.



 a| 
ZEIT
 a| 
Zeit
 a| 
Gesamtverarbeitungszeit für die Anfrage in Mikrosekunden.



 a| 
TLIP
 a| 
Vertrauenswürdige IP-Adresse des Load Balancers
 a| 
Wenn die Anfrage von einem vertrauenswürdigen Layer 7-Load Balancer weitergeleitet wurde, die IP-Adresse des Load Balancers.



 a| 
ULID
 a| 
ID hochladen
 a| 
Nur in SPUT-Nachrichten für CompleteMultipartUpload-Vorgänge enthalten.  Zeigt an, dass alle Teile hochgeladen und zusammengebaut wurden.



 a| 
UUID
 a| 
Universell eindeutige Kennung
 a| 
Die Kennung des Objekts innerhalb des StorageGRID -Systems.



 a| 
VSID
 a| 
Versions-ID
 a| 
Die Versions-ID eines neuen Objekts, das in einem versionierten Bucket erstellt wurde.  Vorgänge an Buckets und Objekten in Buckets ohne Versionierung schließen dieses Feld nicht ein.



 a| 
VSST
 a| 
Versionsstatus
 a| 
Der neue Versionsstatus eines Buckets.  Es werden zwei Zustände verwendet: „aktiviert“ oder „ausgesetzt“.  Operationen an Objekten schließen dieses Feld nicht ein.

|===