---
permalink: audit/syst-node-stopping.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYST, Node Stopping 
summary: 'Wenn ein Dienst ordnungsgemäß beendet wird, wird diese Meldung generiert, um anzuzeigen, dass das Herunterfahren angefordert wurde und dass der Dienst seine Herunterfahrsequenz eingeleitet hat.  SYST kann verwendet werden, um festzustellen, ob das Herunterfahren angefordert wurde, bevor der Dienst neu gestartet wird (im Gegensatz zu SYSD, das normalerweise nach dem Neustart des Dienstes gesendet wird).' 
---
= SYST: Knoten wird gestoppt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Dienst ordnungsgemäß beendet wird, wird diese Meldung generiert, um anzuzeigen, dass das Herunterfahren angefordert wurde und dass der Dienst seine Herunterfahrsequenz eingeleitet hat.  Mit SYST kann ermittelt werden, ob das Herunterfahren angefordert wurde, bevor der Dienst neu gestartet wird (im Gegensatz zu SYSD, das normalerweise nach dem Neustart des Dienstes gesendet wird).

[cols="1a,1a,4a"]
|===
| Code | Feld | Beschreibung 


 a| 
RSLT
 a| 
Sauberes Herunterfahren
 a| 
Die Art der Abschaltung:

SUCS: Das System wurde ordnungsgemäß heruntergefahren.

|===
Die Meldung gibt nicht an, ob der Hostserver gestoppt wird, sondern nur der Berichtsdienst.  Der RSLT-Code einer SYST-Nachricht kann kein „schmutziges“ Herunterfahren anzeigen, da die Nachricht nur bei „sauberen“ Herunterfahren generiert wird.
