---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Erfahren Sie, welche Auswirkungen das Upgrade auf Ihr StorageGRID -System hat. 
---
= Auswirkungen des Upgrades auf Ihr System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, welche Auswirkungen das Upgrade auf Ihr StorageGRID -System hat.



== StorageGRID -Upgrades sind unterbrechungsfrei

Das StorageGRID -System kann während des gesamten Upgrade-Prozesses Daten von Client-Anwendungen aufnehmen und abrufen.  Wenn Sie die Aktualisierung aller Knoten desselben Typs genehmigen (z. B. Speicherknoten), werden die Knoten einzeln heruntergefahren, sodass es nicht vorkommt, dass alle Grid-Knoten oder alle Grid-Knoten eines bestimmten Typs nicht verfügbar sind.

Um eine kontinuierliche Verfügbarkeit zu gewährleisten, stellen Sie sicher, dass Ihre ILM-Richtlinie Regeln enthält, die das Speichern mehrerer Kopien jedes Objekts vorschreiben.  Sie müssen außerdem sicherstellen, dass alle externen S3-Clients so konfiguriert sind, dass sie Anfragen an eines der folgenden Elemente senden:

* Eine virtuelle IP-Adresse einer Hochverfügbarkeitsgruppe (HA)
* Ein hochverfügbarer Load Balancer eines Drittanbieters
* Mehrere Gateway-Knoten für jeden Client
* Mehrere Speicherknoten für jeden Client




== Bei Clientanwendungen kann es zu kurzfristigen Störungen kommen

Das StorageGRID -System kann während des gesamten Upgrade-Prozesses Daten von Client-Anwendungen aufnehmen und abrufen. Allerdings können Client-Verbindungen zu einzelnen Gateway-Knoten oder Speicherknoten vorübergehend unterbrochen werden, wenn für das Upgrade ein Neustart der Dienste auf diesen Knoten erforderlich ist.  Die Konnektivität wird wiederhergestellt, nachdem der Upgrade-Prozess abgeschlossen ist und die Dienste auf den einzelnen Knoten wieder aufgenommen werden.

Wenn ein kurzzeitiger Verbindungsverlust nicht akzeptabel ist, müssen Sie möglicherweise eine Ausfallzeit für die Durchführung eines Upgrades einplanen.  Mithilfe der selektiven Genehmigung können Sie planen, wann bestimmte Knoten aktualisiert werden.


NOTE: Sie können mehrere Gateways und Hochverfügbarkeitsgruppen (HA) verwenden, um während des Upgrade-Prozesses ein automatisches Failover bereitzustellen. Siehe die Anweisungen fürlink:../admin/configure-high-availability-group.html["Konfigurieren von Hochverfügbarkeitsgruppen"] .



== Die Appliance-Firmware wird aktualisiert

Während des StorageGRID 11.9-Upgrades:

* Alle StorageGRID Appliance-Knoten werden automatisch auf die StorageGRID Appliance Installer-Firmwareversion 3.9 aktualisiert.
* SG6060- und SGF6024-Geräte werden automatisch auf die BIOS-Firmware-Version 3B08.EX und die BMC -Firmware-Version 4.00.07 aktualisiert.
* SG100- und SG1000-Geräte werden automatisch auf die BIOS-Firmware-Version 3B13.EC und die BMC -Firmware-Version 4.74.07 aktualisiert.
* Die Geräte SGF6112, SG6160, SG110 und SG1100 werden automatisch auf die BMC -Firmwareversion 3.16.07 aktualisiert.




== ILM-Richtlinien werden je nach Status unterschiedlich behandelt

* Die aktive Richtlinie bleibt nach dem Upgrade unverändert.
* Beim Upgrade bleiben nur die letzten 10 historischen Richtlinien erhalten.
* Wenn eine vorgeschlagene Richtlinie vorhanden ist, wird sie während des Upgrades gelöscht.




== Es können Warnungen ausgelöst werden

Warnungen können ausgelöst werden, wenn Dienste gestartet und gestoppt werden und wenn das StorageGRID -System als Umgebung mit gemischten Versionen betrieben wird (einige Grid-Knoten führen eine frühere Version aus, während andere auf eine neuere Version aktualisiert wurden).  Nach Abschluss des Upgrades können weitere Warnungen ausgelöst werden.

Beispielsweise wird möglicherweise die Warnung *Kommunikation mit Knoten nicht möglich* angezeigt, wenn Dienste gestoppt werden, oder die Warnung *Cassandra-Kommunikationsfehler*, wenn einige Knoten auf StorageGRID 11.9 aktualisiert wurden, auf anderen Knoten jedoch noch StorageGRID 11.8 ausgeführt wird. Im Allgemeinen werden diese Warnungen gelöscht, wenn das Upgrade abgeschlossen ist.

Die Warnung *ILM-Platzierung nicht erreichbar* kann ausgelöst werden, wenn Speicherknoten während des Upgrades auf StorageGRID 11.9 angehalten werden. Diese Warnung bleibt möglicherweise noch einen Tag nach Abschluss des Upgrades bestehen.

Nach Abschluss des Upgrades können Sie alle Upgrade-bezogenen Warnungen überprüfen, indem Sie im Grid Manager-Dashboard *Kürzlich behobene Warnungen* oder *Aktuelle Warnungen* auswählen.



== Viele SNMP-Benachrichtigungen werden generiert

Beachten Sie, dass beim Anhalten und Neustarten von Grid-Knoten während des Upgrades möglicherweise eine große Anzahl von SNMP-Benachrichtigungen generiert wird.  Um übermäßige Benachrichtigungen zu vermeiden, deaktivieren Sie das Kontrollkästchen *SNMP-Agent-Benachrichtigungen aktivieren* (*KONFIGURATION* > *Überwachung* > *SNMP-Agent*), um SNMP-Benachrichtigungen zu deaktivieren, bevor Sie mit dem Upgrade beginnen.  Aktivieren Sie die Benachrichtigungen dann erneut, nachdem das Upgrade abgeschlossen ist.



== Konfigurationsänderungen sind eingeschränkt


NOTE: Diese Liste gilt speziell für Upgrades von StorageGRID 11.8 auf StorageGRID 11.9. Wenn Sie auf eine andere StorageGRID Version aktualisieren, lesen Sie die Liste der eingeschränkten Änderungen in den Upgrade-Anweisungen für diese Version.

Bis die Aufgabe *Neue Funktion aktivieren* abgeschlossen ist:

* Nehmen Sie keine Änderungen an der Rasterkonfiguration vor.
* Aktivieren oder deaktivieren Sie keine neuen Funktionen.
* Aktualisieren Sie die ILM-Konfiguration nicht.  Andernfalls kann es zu inkonsistentem und unerwartetem ILM-Verhalten kommen.
* Wenden Sie keinen Hotfix an und stellen Sie keinen Grid-Knoten wieder her.
+

NOTE: Wenden Sie sich an den technischen Support, wenn Sie während des Upgrades einen Knoten wiederherstellen müssen.

* Sie sollten während des Upgrades auf StorageGRID 11.9 keine HA-Gruppen, VLAN-Schnittstellen oder Load Balancer-Endpunkte verwalten.
* Löschen Sie keine HA-Gruppen, bis das Upgrade auf StorageGRID 11.9 abgeschlossen ist. Auf virtuelle IP-Adressen in anderen HA-Gruppen kann möglicherweise nicht mehr zugegriffen werden.


Bis die Aufgabe *Letzte Upgrade-Schritte* abgeschlossen ist:

* Führen Sie keinen Erweiterungsvorgang durch.
* Führen Sie kein Außerbetriebnahmeverfahren durch.




== Sie können Bucket-Details nicht anzeigen oder Buckets vom Tenant Manager aus verwalten.

Während des Upgrades auf StorageGRID 11.9 (d. h. während das System als Umgebung mit gemischten Versionen betrieben wird) können Sie mit dem Tenant Manager keine Bucket-Details anzeigen oder Buckets verwalten.  Auf der Buckets-Seite im Tenant Manager wird einer der folgenden Fehler angezeigt:

* Sie können diese API nicht verwenden, während Sie auf 11.9 aktualisieren.
* Während Sie ein Upgrade auf 11.9 durchführen, können Sie im Tenant Manager keine Bucket-Versionsdetails anzeigen.


Dieser Fehler wird behoben, nachdem das Upgrade auf 11.9 abgeschlossen ist.

.Problemumgehung
Während das Upgrade auf 11.9 läuft, können Sie die folgenden Tools verwenden, um Bucket-Details anzuzeigen oder Buckets zu verwalten, anstatt den Tenant Manager zu verwenden:

* Um Standard-S3-Operationen auf einem Bucket durchzuführen, verwenden Sie entweder dielink:../s3/operations-on-buckets.html["S3 REST API"] oder dielink:../tenant/understanding-tenant-management-api.html["Mandantenverwaltungs-API"] .
* Um benutzerdefinierte StorageGRID -Vorgänge für einen Bucket auszuführen (z. B. Anzeigen und Ändern der Bucket-Konsistenz, Aktivieren oder Deaktivieren von Aktualisierungen der letzten Zugriffszeit oder Konfigurieren der Suchintegration), verwenden Sie die Tenant Management API.

