---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: storagegrid software upgrade 
summary: Verwenden Sie diese Anweisungen, um ein StorageGRID -System auf eine neue Version zu aktualisieren. 
---
= Aktualisieren Sie die StorageGRID -Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie diese Anweisungen, um ein StorageGRID -System auf eine neue Version zu aktualisieren.

Wenn Sie das Upgrade durchführen, werden alle Knoten in Ihrem StorageGRID -System aktualisiert.



== Bevor Sie beginnen

Lesen Sie diese Themen, um mehr über die neuen Funktionen und Verbesserungen in StorageGRID 11.9 zu erfahren, festzustellen, ob Funktionen veraltet sind oder entfernt wurden, und sich über Änderungen an den StorageGRID -APIs zu informieren.

* link:whats-new.html["Was ist neu in StorageGRID 11.9"]
* link:removed-or-deprecated-features.html["Entfernte oder veraltete Funktionen"]
* link:changes-to-grid-management-api.html["Änderungen an der Grid Management API"]
* link:changes-to-tenant-management-api.html["Änderungen an der Tenant Management API"]

