---
permalink: ubuntu/example-node-configuration-files.html 
sidebar: sidebar 
keywords: example node configuration files 
summary: Sie können die Beispielknotenkonfigurationsdateien verwenden, um die Knotenkonfigurationsdateien für Ihr StorageGRID -System einzurichten.  Die Beispiele zeigen Knotenkonfigurationsdateien für alle Arten von Grid-Knoten. 
---
= Beispiele für Knotenkonfigurationsdateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Beispielknotenkonfigurationsdateien verwenden, um die Knotenkonfigurationsdateien für Ihr StorageGRID -System einzurichten.  Die Beispiele zeigen Knotenkonfigurationsdateien für alle Arten von Grid-Knoten.

Für die meisten Knoten können Sie Administrator- und Client-Netzwerkadressinformationen (IP, Maske, Gateway usw.) hinzufügen, wenn Sie das Grid mit dem Grid Manager oder der Installations-API konfigurieren.  Die Ausnahme ist der primäre Admin-Knoten.  Wenn Sie zur Admin-Netzwerk-IP des primären Admin-Knotens navigieren möchten, um die Grid-Konfiguration abzuschließen (weil das Grid-Netzwerk beispielsweise nicht geroutet wird), müssen Sie die Admin-Netzwerkverbindung für den primären Admin-Knoten in seiner Knotenkonfigurationsdatei konfigurieren.  Dies wird im Beispiel gezeigt.


NOTE: In den Beispielen wurde das Client-Netzwerkziel als Best Practice konfiguriert, obwohl das Client-Netzwerk standardmäßig deaktiviert ist.



== Beispiel für primären Admin-Knoten

*Beispieldateiname*: `/etc/storagegrid/nodes/dc1-adm1.conf`

*Beispieldateiinhalt:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
TEMPORARY_PASSWORD_TYPE = Use custom password
CUSTOM_TEMPORARY_PASSWORD = Passw0rd
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm1-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm1-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm1-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.2
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1

ADMIN_NETWORK_CONFIG = STATIC
ADMIN_NETWORK_IP = 192.168.100.2
ADMIN_NETWORK_MASK = 255.255.248.0
ADMIN_NETWORK_GATEWAY = 192.168.100.1
ADMIN_NETWORK_ESL = 192.168.100.0/21,172.16.0.0/21,172.17.0.0/21
----


== Beispiel für Speicherknoten

*Beispieldateiname:* `/etc/storagegrid/nodes/dc1-sn1.conf`

*Beispieldateiinhalt:*

[listing]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/dc1-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/dc1-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/dc1-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/dc1-sn1-rangedb-3
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Beispiel für Gateway-Knoten

*Beispieldateiname:* `/etc/storagegrid/nodes/dc1-gw1.conf`

*Beispieldateiinhalt:*

[listing]
----
NODE_TYPE = VM_API_Gateway
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-gw1-var-local
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.5
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Beispiel für einen nicht primären Admin-Knoten

*Beispieldateiname:* `/etc/storagegrid/nodes/dc1-adm2.conf`

*Beispieldateiinhalt:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Non-Primary
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm2-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm2-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm2-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.6
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----