---
permalink: ubuntu/example-etc-network-interfaces.html 
sidebar: sidebar 
keywords: example etc network interfaces 
summary: Die Datei /etc/network/interfaces enthält drei Abschnitte, die die physischen Schnittstellen, die Bond-Schnittstelle und die VLAN-Schnittstellen definieren.  Sie können die drei Beispielabschnitte in einer einzigen Datei kombinieren, die vier physische Linux-Schnittstellen in einer einzigen LACP-Verbindung zusammenfasst und dann drei VLAN-Schnittstellen einrichtet, die die Verbindung zur Verwendung als StorageGRID Grid-, Admin- und Client-Netzwerkschnittstellen unterteilen. 
---
= Beispiel /etc/network/interfaces
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `/etc/network/interfaces` Die Datei enthält drei Abschnitte, die die physischen Schnittstellen, die Bond-Schnittstelle und die VLAN-Schnittstellen definieren.  Sie können die drei Beispielabschnitte in einer einzigen Datei kombinieren, die vier physische Linux-Schnittstellen in einer einzigen LACP-Verbindung zusammenfasst und dann drei VLAN-Schnittstellen einrichtet, die die Verbindung zur Verwendung als StorageGRID Grid-, Admin- und Client-Netzwerkschnittstellen unterteilen.



== Physikalische Schnittstellen

Beachten Sie, dass die Switches an den anderen Enden der Links die vier Ports ebenfalls als einen einzigen LACP-Trunk oder Port-Kanal behandeln und mindestens die drei referenzierten VLANs mit Tags übergeben müssen.

[listing]
----
# loopback interface
auto lo
iface lo inet loopback

# ens160 interface
auto ens160
iface ens160 inet manual
    bond-master bond0
    bond-primary en160

# ens192 interface
auto ens192
iface ens192 inet manual
    bond-master bond0

# ens224 interface
auto ens224
iface ens224 inet manual
    bond-master bond0

# ens256 interface
auto ens256
iface ens256 inet manual
    bond-master bond0
----


== Bond-Schnittstelle

[listing]
----
# bond0 interface
auto bond0
iface bond0 inet manual
    bond-mode 4
    bond-miimon 100
    bond-slaves ens160 ens192 end224 ens256
----


== VLAN-Schnittstellen

[listing]
----
# 1001 vlan
auto bond0.1001
iface bond0.1001 inet manual
vlan-raw-device bond0

# 1002 vlan
auto bond0.1002
iface bond0.1002 inet manual
vlan-raw-device bond0

# 1003 vlan
auto bond0.1003
iface bond0.1003 inet manual
vlan-raw-device bond0
----