---
permalink: ubuntu/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Sie können eine virtuelle Maschine verwenden, um jeden StorageGRID Knotentyp zu hosten.  Sie benötigen eine virtuelle Maschine für jeden Grid-Knoten. 
---
= Softwareanforderungen für Ubuntu und Debian
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine virtuelle Maschine verwenden, um jeden StorageGRID Knotentyp zu hosten.  Sie benötigen eine virtuelle Maschine für jeden Grid-Knoten.

Um StorageGRID auf Ubuntu oder Debian zu installieren, müssen Sie einige Softwarepakete von Drittanbietern installieren. Einige unterstützte Linux-Distributionen enthalten diese Pakete nicht standardmäßig. Zu den Softwarepaketversionen, auf denen StorageGRID Installationen getestet werden, gehören die auf dieser Seite aufgeführten.

Wenn Sie eine Linux-Distribution und eine Container-Runtime-Installationsoption auswählen, die eines dieser Pakete erfordert und diese nicht automatisch von der Linux-Distribution installiert werden, installieren Sie eine der hier aufgeführten Versionen, sofern diese von Ihrem Provider oder dem unterstützenden Anbieter für Ihre Linux-Distribution verfügbar ist.  Verwenden Sie andernfalls die von Ihrem Anbieter verfügbaren Standardpaketversionen.

Alle Installationsoptionen erfordern entweder Podman oder Docker.  Installieren Sie nicht beide Pakete.  Installieren Sie nur das Paket, das für Ihre Installationsoption erforderlich ist.


NOTE: Die Unterstützung für Docker als Container-Engine für reine Softwarebereitstellungen ist veraltet. Docker wird in einer zukünftigen Version durch eine andere Container-Engine ersetzt.



== Getestete Python-Versionen

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== Getestete Podman-Versionen

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12




== Getestete Docker-Versionen


IMPORTANT: Die Docker-Unterstützung ist veraltet und wird in einer zukünftigen Version entfernt.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23.0.6-1
* Docker-CE 24.0.2-1
* Docker-CE 24.0.4-1
* Docker-CE 24.0.5-1
* Docker-CE 24.0.7-1
* 1,5-2

