---
permalink: ubuntu/understanding-apparmor-profile-installation.html 
sidebar: sidebar 
keywords: how to install AppArmor profile 
summary: Wenn Sie in einer selbst bereitgestellten Ubuntu-Umgebung arbeiten und das obligatorische Zugriffskontrollsystem AppArmor verwenden, werden die AppArmor-Profile, die mit den Paketen verknüpft sind, die Sie auf dem Basissystem installieren, möglicherweise durch die entsprechenden Pakete blockiert, die mit StorageGRID installiert wurden. 
---
= Verstehen Sie die Installation des AppArmor-Profils
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie in einer selbst bereitgestellten Ubuntu-Umgebung arbeiten und das obligatorische Zugriffskontrollsystem AppArmor verwenden, werden die AppArmor-Profile, die mit den Paketen verknüpft sind, die Sie auf dem Basissystem installieren, möglicherweise durch die entsprechenden Pakete blockiert, die mit StorageGRID installiert wurden.

Standardmäßig werden AppArmor-Profile für Pakete installiert, die Sie auf dem Basisbetriebssystem installieren.  Wenn Sie diese Pakete aus dem StorageGRID -Systemcontainer ausführen, werden die AppArmor-Profile blockiert.  Die DHCP-, MySQL-, NTP- und tcdump-Basispakete stehen im Konflikt mit AppArmor, und auch bei anderen Basispaketen kann es zu Konflikten kommen.

Sie haben zwei Möglichkeiten, AppArmor-Profile zu handhaben:

* Deaktivieren Sie einzelne Profile für die auf dem Basissystem installierten Pakete, die sich mit den Paketen im StorageGRID -Systemcontainer überschneiden.  Wenn Sie einzelne Profile deaktivieren, wird in den StorageGRID -Protokolldateien ein Eintrag angezeigt, der angibt, dass AppArmor aktiviert ist.
+
Verwenden Sie die folgenden Befehle:

+
[listing]
----
sudo ln -s /etc/apparmor.d/<profile.name> /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/<profile.name>
----
+
*Beispiel:*

+
[listing]
----
sudo ln -s /etc/apparmor.d/bin.ping /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/bin.ping
----
* Deaktivieren Sie AppArmor vollständig.  Befolgen Sie für Ubuntu 9.10 oder höher die Anweisungen in der Ubuntu-Online-Community: https://help.ubuntu.com/community/AppArmor#Disable_AppArmor_framework["AppArmor deaktivieren"^] .  Das vollständige Deaktivieren von AppArmor ist bei neueren Ubuntu-Versionen möglicherweise nicht möglich.
+
Nachdem Sie AppArmor deaktiviert haben, werden in den StorageGRID Protokolldateien keine Einträge angezeigt, die darauf hinweisen, dass AppArmor aktiviert ist.


