---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: Sie müssen Ihr StorageGRID -System und die zugehörigen Dienste auf dem neuesten Stand halten, um sich vor Angriffen zu schützen. 
---
= Härtungsrichtlinien für Software-Upgrades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Ihr StorageGRID -System und die zugehörigen Dienste auf dem neuesten Stand halten, um sich vor Angriffen zu schützen.



== Upgrades der StorageGRID -Software

Wenn möglich, sollten Sie die StorageGRID -Software auf die neueste Hauptversion oder auf die vorherige Hauptversion aktualisieren.  Durch die Aktualisierung von StorageGRID lässt sich die Zeit verkürzen, in der bekannte Schwachstellen aktiv sind, und die gesamte Angriffsfläche wird verringert.  Darüber hinaus enthalten die neuesten Versionen von StorageGRID häufig Funktionen zur Sicherheitshärtung, die in früheren Versionen nicht enthalten waren.

Konsultieren Sie die https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitätsmatrix-Tool"^] (IMT), um zu bestimmen, welche Version der StorageGRID -Software Sie verwenden sollten.  Wenn ein Hotfix erforderlich ist, legt NetApp Wert darauf, Updates für die aktuellsten Versionen zu erstellen.  Einige Patches sind möglicherweise nicht mit früheren Versionen kompatibel.

* Um die neuesten StorageGRID Versionen und Hotfixes herunterzuladen, gehen Sie zu https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] .
* Informationen zum Upgrade der StorageGRID -Software finden Sie imlink:../upgrade/performing-upgrade.html["Upgrade-Anweisungen"] .
* Informationen zum Anwenden eines Hotfixes finden Sie imlink:../maintain/storagegrid-hotfix-procedure.html["StorageGRID Hotfix-Verfahren"] .




== Upgrades auf externe Dienste

Externe Dienste können Schwachstellen aufweisen, die StorageGRID indirekt betreffen. Sie sollten sicherstellen, dass die Dienste, von denen StorageGRID abhängt, auf dem neuesten Stand gehalten werden. Zu diesen Diensten gehören LDAP, KMS (oder KMIP-Server), DNS und NTP.

Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitätsmatrix-Tool"^] .



== Upgrades auf Hypervisoren

Wenn Ihre StorageGRID -Knoten auf VMware oder einem anderen Hypervisor ausgeführt werden, müssen Sie sicherstellen, dass die Software und Firmware des Hypervisors auf dem neuesten Stand sind.

Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitätsmatrix-Tool"^] .



== *Upgrades auf Linux-Knoten*

Wenn Ihre StorageGRID -Knoten Linux-Hostplattformen verwenden, müssen Sie sicherstellen, dass Sicherheitsupdates und Kernelupdates auf das Hostbetriebssystem angewendet werden.  Darüber hinaus müssen Sie Firmware-Updates auf anfällige Hardware anwenden, sobald diese Updates verfügbar sind.

Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitätsmatrix-Tool"^] .
