---
permalink: network/admin-network-requirements.html 
sidebar: sidebar 
keywords: admin network requirements, guidelines for admin network, aesl 
summary: Das Admin-Netzwerk ist optional.  Wenn Sie ein Admin-Netzwerk konfigurieren möchten, befolgen Sie diese Anforderungen und Richtlinien. 
---
= Anforderungen an das Admin-Netzwerk
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Admin-Netzwerk ist optional.  Wenn Sie ein Admin-Netzwerk konfigurieren möchten, befolgen Sie diese Anforderungen und Richtlinien.

Zu den typischen Verwendungszwecken des Admin-Netzwerks gehören Verwaltungsverbindungen, AutoSupport, KMS und Verbindungen zu kritischen Servern wie NTP, DNS und LDAP, wenn diese Verbindungen nicht über das Grid-Netzwerk oder das Client-Netzwerk bereitgestellt werden.


NOTE: Das Admin-Netzwerk und die AESL können für jeden Knoten eindeutig sein, solange die gewünschten Netzwerkdienste und Clients erreichbar sind.


NOTE: Sie müssen mindestens ein Subnetz im Admin-Netzwerk definieren, um eingehende Verbindungen von externen Subnetzen zu ermöglichen.  Auf jedem Knoten werden für jedes Subnetz in der AESL automatisch statische Routen generiert.
