---
permalink: tenant/configuring-event-notifications.html 
sidebar: sidebar 
keywords: how to configure event notifications, bucket notification 
summary: Sie aktivieren Benachrichtigungen für einen Bucket, indem Sie eine XML-Benachrichtigungskonfiguration erstellen und den Tenant Manager verwenden, um die XML auf einen Bucket anzuwenden. 
---
= Konfigurieren von Ereignisbenachrichtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie aktivieren Benachrichtigungen für einen Bucket, indem Sie eine XML-Benachrichtigungskonfiguration erstellen und den Tenant Manager verwenden, um die XML auf einen Bucket anzuwenden.

.Bevor Sie beginnen
* Die Plattformdienste wurden von einem StorageGRID Administrator für Ihr Mandantenkonto aktiviert.
* Sie haben bereits einen Bucket erstellt, der als Benachrichtigungsquelle dient.
* Der Endpunkt, den Sie als Ziel für Ereignisbenachrichtigungen verwenden möchten, ist bereits vorhanden und Sie verfügen über seine URN.
* Sie gehören einer Benutzergruppe an, die über dielink:tenant-management-permissions.html["Verwalten Sie alle Buckets oder Root-Zugriffsberechtigungen"] .  Diese Berechtigungen überschreiben die Berechtigungseinstellungen in Gruppen- oder Bucket-Richtlinien, wenn der Bucket mit dem Tenant Manager konfiguriert wird.


.Informationen zu diesem Vorgang
Sie konfigurieren Ereignisbenachrichtigungen, indem Sie die Benachrichtigungskonfigurations-XML mit einem Quell-Bucket verknüpfen. Die XML-Benachrichtigungskonfiguration folgt den S3-Konventionen zum Konfigurieren von Bucket-Benachrichtigungen, wobei das Zielthema Kafka oder Amazon SNS als URN eines Endpunkts angegeben ist.

Allgemeine Informationen zu Ereignisbenachrichtigungen und deren Konfiguration finden Sie im https://docs.aws.amazon.com/s3/["Amazon-Dokumentation"^] .  Informationen zur Implementierung der S3-Bucket-Benachrichtigungskonfigurations-API durch StorageGRID finden Sie imlink:../s3/index.html["Anweisungen zur Implementierung von S3-Clientanwendungen"] .

Beachten Sie beim Konfigurieren von Ereignisbenachrichtigungen für einen Bucket die folgenden Anforderungen und Merkmale:

* Wenn Sie eine gültige XML-Benachrichtigungskonfiguration erstellen und anwenden, muss für jedes Ziel die URN eines Endpunkts für Ereignisbenachrichtigungen verwendet werden.
* Obwohl die Ereignisbenachrichtigung für einen Bucket mit aktivierter S3-Objektsperre konfiguriert werden kann, werden die S3-Objektsperre-Metadaten (einschließlich „Aufbewahrungsdatum“ und „Legal Hold“-Status) der Objekte nicht in die Benachrichtigungsnachrichten aufgenommen.
* Nachdem Sie Ereignisbenachrichtigungen konfiguriert haben, wird jedes Mal, wenn ein bestimmtes Ereignis für ein Objekt im Quell-Bucket eintritt, eine Benachrichtigung generiert und an das als Zielendpunkt verwendete Amazon SNS- oder Kafka-Thema gesendet.
* Wenn Sie Ereignisbenachrichtigungen für einen Bucket aktivieren, der Objekte enthält, werden Benachrichtigungen nur für Aktionen gesendet, die nach dem Speichern der Benachrichtigungskonfiguration ausgeführt werden.


.Schritte
. Aktivieren Sie Benachrichtigungen für Ihren Quell-Bucket:
+
** Verwenden Sie einen Texteditor, um die zum Aktivieren von Ereignisbenachrichtigungen erforderliche XML-Benachrichtigungskonfiguration zu erstellen, wie in der S3-Benachrichtigungs-API angegeben.
** Verwenden Sie beim Konfigurieren des XML die URN eines Endpunkts für Ereignisbenachrichtigungen als Zielthema.
+
[listing]
----
<NotificationConfiguration>
  <TopicConfiguration>
     <Id>Image-created</Id>
     <Filter>
        <S3Key>
          <FilterRule>
            <Name>prefix</Name>
            <Value>images/</Value>
          </FilterRule>
        </S3Key>
    </Filter>
    <Topic>arn:aws:sns:us-east-1:050340950352:sgws-topic</Topic>
    <Event>s3:ObjectCreated:*</Event>
   </TopicConfiguration>
 </NotificationConfiguration>
----


. Wählen Sie im Mandanten-Manager *STORAGE (S3)* > *Buckets*.
. Wählen Sie den Namen des Quell-Buckets aus.
+
Die Bucket-Detailseite wird angezeigt.

. Wählen Sie *Plattformdienste* > *Ereignisbenachrichtigungen*.
. Aktivieren Sie das Kontrollkästchen *Ereignisbenachrichtigungen aktivieren*.
. Fügen Sie die XML-Benachrichtigungskonfiguration in das Textfeld ein und wählen Sie *Änderungen speichern*.
+

NOTE: Plattformdienste müssen für jedes Mandantenkonto von einem StorageGRID Administrator mithilfe des Grid Managers oder der Grid Management-API aktiviert werden.  Wenden Sie sich an Ihren StorageGRID -Administrator, wenn beim Speichern der XML-Konfiguration ein Fehler auftritt.

. Überprüfen Sie, ob die Ereignisbenachrichtigungen richtig konfiguriert sind:
+
.. Führen Sie eine Aktion für ein Objekt im Quell-Bucket aus, das die Anforderungen zum Auslösen einer Benachrichtigung erfüllt, wie in der Konfigurations-XML konfiguriert.
+
Im Beispiel wird eine Ereignisbenachrichtigung gesendet, wenn ein Objekt mit dem `images/` Präfix.

.. Bestätigen Sie, dass eine Benachrichtigung an das Zielthema Amazon SNS oder Kafka übermittelt wurde.
+
Wenn Ihr Zielthema beispielsweise auf Amazon SNS gehostet wird, können Sie den Dienst so konfigurieren, dass er Ihnen eine E-Mail sendet, wenn die Benachrichtigung zugestellt wird.

+
[listing]
----
{
   "Records":[
      {
         "eventVersion":"2.0",
         "eventSource":"sgws:s3",
         "eventTime":"2017-08-08T23:52:38Z",
         "eventName":"ObjectCreated:Put",
         "userIdentity":{
            "principalId":"1111111111111111111"
         },
         "requestParameters":{
            "sourceIPAddress":"193.51.100.20"
         },
         "responseElements":{
            "x-amz-request-id":"122047343"
         },
         "s3":{
            "s3SchemaVersion":"1.0",
            "configurationId":"Image-created",
            "bucket":{
               "name":"test1",
               "ownerIdentity":{
                  "principalId":"1111111111111111111"
               },
               "arn":"arn:sgws:s3:::test1"
            },
            "object":{
               "key":"images/cat.jpg",
               "size":0,
               "eTag":"d41d8cd98f00b204e9800998ecf8427e",
               "sequencer":"14D90402421461C7"
            }
         }
      }
   ]
}
----
+
Wenn die Benachrichtigung beim Zielthema empfangen wird, haben Sie Ihren Quell-Bucket erfolgreich für StorageGRID -Benachrichtigungen konfiguriert.





.Ähnliche Informationen
link:understanding-notifications-for-buckets.html["Benachrichtigungen für Buckets verstehen"]

link:../s3/index.html["Verwenden Sie die S3 REST-API"]

link:creating-platform-services-endpoint.html["Plattformdienst-Endpunkt erstellen"]
