---
permalink: tenant/creating-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create your own S3 access key 
summary: Wenn Sie einen S3-Mandanten verwenden und über die entsprechende Berechtigung verfügen, können Sie Ihre eigenen S3-Zugriffsschlüssel erstellen.  Sie benötigen einen Zugriffsschlüssel, um auf Ihre Buckets und Objekte zugreifen zu können. 
---
= Erstellen Sie Ihre eigenen S3-Zugriffsschlüssel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen S3-Mandanten verwenden und über die entsprechende Berechtigung verfügen, können Sie Ihre eigenen S3-Zugriffsschlüssel erstellen.  Sie benötigen einen Zugriffsschlüssel, um auf Ihre Buckets und Objekte zugreifen zu können.

.Bevor Sie beginnen
* Sie sind beim Tenant Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie gehören einer Benutzergruppe an, die über dielink:tenant-management-permissions.html["Verwalten Sie Ihre eigenen S3-Anmeldeinformationen oder Root-Zugriffsberechtigungen"] .


.Informationen zu diesem Vorgang
Sie können einen oder mehrere S3-Zugriffsschlüssel erstellen, mit denen Sie Buckets für Ihr Mandantenkonto erstellen und verwalten können.  Nachdem Sie einen neuen Zugriffsschlüssel erstellt haben, aktualisieren Sie die Anwendung mit Ihrer neuen Zugriffsschlüssel-ID und Ihrem geheimen Zugriffsschlüssel.  Erstellen Sie aus Sicherheitsgründen nicht mehr Schlüssel als nötig und löschen Sie die Schlüssel, die Sie nicht verwenden.  Wenn Sie nur einen Schlüssel haben und dieser bald abläuft, erstellen Sie einen neuen Schlüssel, bevor der alte abläuft, und löschen Sie dann den alten.

Jeder Schlüssel kann eine bestimmte Ablaufzeit haben oder nicht ablaufen.  Befolgen Sie diese Richtlinien für die Ablaufzeit:

* Legen Sie eine Ablaufzeit für Ihre Schlüssel fest, um Ihren Zugriff auf einen bestimmten Zeitraum zu beschränken.  Durch das Festlegen einer kurzen Ablaufzeit können Sie Ihr Risiko verringern, wenn Ihre Zugriffsschlüssel-ID und Ihr geheimer Zugriffsschlüssel versehentlich offengelegt werden.  Abgelaufene Schlüssel werden automatisch entfernt.
* Wenn das Sicherheitsrisiko in Ihrer Umgebung gering ist und Sie nicht regelmäßig neue Schlüssel erstellen müssen, müssen Sie für Ihre Schlüssel keine Ablaufzeit festlegen.  Wenn Sie sich später entscheiden, neue Schlüssel zu erstellen, löschen Sie die alten Schlüssel manuell.



CAUTION: Auf die zu Ihrem Konto gehörenden S3-Buckets und -Objekte kann mithilfe der Zugriffsschlüssel-ID und des geheimen Zugriffsschlüssels zugegriffen werden, die für Ihr Konto im Tenant Manager angezeigt werden.  Schützen Sie daher Zugriffsschlüssel wie ein Passwort.  Wechseln Sie die Zugriffsschlüssel regelmäßig, entfernen Sie alle nicht verwendeten Schlüssel aus Ihrem Konto und geben Sie sie niemals an andere Benutzer weiter.

.Schritte
. Wählen Sie *SPEICHER (S3)* > *Meine Zugriffsschlüssel*.
+
Die Seite „Meine Zugriffsschlüssel“ wird angezeigt und listet alle vorhandenen Zugriffsschlüssel auf.

. Wählen Sie *Schlüssel erstellen*.
. Führen Sie einen der folgenden Schritte aus:
+
** Wählen Sie *Keine Ablaufzeit festlegen*, um einen Schlüssel zu erstellen, der nicht abläuft.  (Standard)
** Wählen Sie *Ablaufzeit festlegen* und legen Sie das Ablaufdatum und die Ablaufzeit fest.
+

NOTE: Das Ablaufdatum kann maximal fünf Jahre ab dem aktuellen Datum liegen.  Die Ablaufzeit kann mindestens eine Minute nach der aktuellen Zeit liegen.



. Wählen Sie *Zugriffsschlüssel erstellen*.
+
Das Dialogfeld „Zugriffsschlüssel herunterladen“ wird angezeigt und listet Ihre Zugriffsschlüssel-ID und Ihren geheimen Zugriffsschlüssel auf.

. Kopieren Sie die Zugriffsschlüssel-ID und den geheimen Zugriffsschlüssel an einen sicheren Ort oder wählen Sie *.csv herunterladen*, um eine Tabellenkalkulationsdatei mit der Zugriffsschlüssel-ID und dem geheimen Zugriffsschlüssel zu speichern.
+

CAUTION: Schließen Sie dieses Dialogfeld nicht, bis Sie diese Informationen kopiert oder heruntergeladen haben.  Sie können keine Schlüssel kopieren oder herunterladen, nachdem das Dialogfeld geschlossen wurde.

. Wählen Sie *Fertig*.
+
Der neue Schlüssel wird auf der Seite „Meine Zugriffsschlüssel“ aufgeführt.

. Wenn Ihr Mandantenkonto über die Berechtigung *Grid-Föderationsverbindung verwenden* verfügt, können Sie optional die Mandantenverwaltungs-API verwenden, um S3-Zugriffsschlüssel vom Mandanten im Quell-Grid manuell auf den Mandanten im Ziel-Grid zu klonen. Sehen link:grid-federation-clone-keys-with-api.html["Klonen Sie S3-Zugriffsschlüssel mithilfe der API"] .

