---
permalink: tenant/deleting-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete S3 access key 
summary: Wenn Sie einen S3-Mandanten verwenden und über die entsprechende Berechtigung verfügen, können Sie Ihre eigenen S3-Zugriffsschlüssel löschen.  Nachdem ein Zugriffsschlüssel gelöscht wurde, kann er nicht mehr für den Zugriff auf die Objekte und Buckets im Mandantenkonto verwendet werden. 
---
= Löschen Sie Ihre eigenen S3-Zugriffsschlüssel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen S3-Mandanten verwenden und über die entsprechende Berechtigung verfügen, können Sie Ihre eigenen S3-Zugriffsschlüssel löschen.  Nachdem ein Zugriffsschlüssel gelöscht wurde, kann er nicht mehr für den Zugriff auf die Objekte und Buckets im Mandantenkonto verwendet werden.

.Bevor Sie beginnen
* Sie sind beim Tenant Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie haben dielink:tenant-management-permissions.html["Verwalten Sie Ihre eigenen S3-Anmeldeinformationen"] .



CAUTION: Auf die zu Ihrem Konto gehörenden S3-Buckets und -Objekte kann mithilfe der Zugriffsschlüssel-ID und des geheimen Zugriffsschlüssels zugegriffen werden, die für Ihr Konto im Tenant Manager angezeigt werden.  Schützen Sie daher Zugriffsschlüssel wie ein Passwort.  Wechseln Sie die Zugriffsschlüssel regelmäßig, entfernen Sie alle nicht verwendeten Schlüssel aus Ihrem Konto und geben Sie sie niemals an andere Benutzer weiter.

.Schritte
. Wählen Sie *SPEICHER (S3)* > *Meine Zugriffsschlüssel*.
. Aktivieren Sie auf der Seite „Meine Zugriffsschlüssel“ das Kontrollkästchen für jeden Zugriffsschlüssel, den Sie entfernen möchten.
. Wählen Sie *Löschtaste*.
. Wählen Sie im Bestätigungsdialogfeld *Schlüssel löschen* aus.
+
In der oberen rechten Ecke der Seite wird eine Bestätigungsmeldung angezeigt.


