---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: 'Wenn Grid-Administratoren die Regeln für das Information Lifecycle Management (ILM) für ein StorageGRID System erstellen, können sie optional angeben, dass der Zeitpunkt des letzten Zugriffs auf ein Objekt verwendet werden soll, um zu bestimmen, ob dieses Objekt an einen anderen Speicherort verschoben werden soll.  Wenn Sie einen S3-Mandanten verwenden, können Sie solche Regeln nutzen, indem Sie Aktualisierungen der letzten Zugriffszeit für die Objekte in einem S3-Bucket aktivieren.' 
---
= Aktivieren oder Deaktivieren der Aktualisierung der letzten Zugriffszeit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Grid-Administratoren die Regeln für das Information Lifecycle Management (ILM) für ein StorageGRID System erstellen, können sie optional angeben, dass der Zeitpunkt des letzten Zugriffs auf ein Objekt verwendet werden soll, um zu bestimmen, ob dieses Objekt an einen anderen Speicherort verschoben werden soll.  Wenn Sie einen S3-Mandanten verwenden, können Sie solche Regeln nutzen, indem Sie Aktualisierungen der letzten Zugriffszeit für die Objekte in einem S3-Bucket aktivieren.

Diese Anweisungen gelten nur für StorageGRID -Systeme, die mindestens eine ILM-Regel enthalten, die die Option *Letzter Zugriffszeitpunkt* als erweiterten Filter oder als Referenzzeit verwendet.  Sie können diese Anweisungen ignorieren, wenn Ihr StorageGRID System keine solche Regel enthält. Sehenlink:../ilm/using-last-access-time-in-ilm-rules.html["Verwenden der letzten Zugriffszeit in ILM-Regeln"] für Details.

.Bevor Sie beginnen
* Sie sind beim Tenant Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie gehören einer Benutzergruppe an, die über dielink:tenant-management-permissions.html["Verwalten Sie alle Buckets oder Root-Zugriffsberechtigungen"] . Diese Berechtigungen überschreiben die Berechtigungseinstellungen in Gruppen- oder Bucket-Richtlinien.


.Informationen zu diesem Vorgang
*Letzter Zugriffszeitpunkt* ist eine der verfügbaren Optionen für die Platzierungsanweisung *Referenzzeitpunkt* für eine ILM-Regel.  Durch Festlegen der Referenzzeit für eine Regel auf „Letzter Zugriffszeitpunkt“ können Grid-Administratoren festlegen, dass Objekte an bestimmten Speicherorten abgelegt werden, basierend auf dem Zeitpunkt, zu dem diese Objekte zuletzt abgerufen (gelesen oder angezeigt) wurden.

Um beispielsweise sicherzustellen, dass kürzlich angezeigte Objekte auf einem schnelleren Speicher verbleiben, kann ein Grid-Administrator eine ILM-Regel erstellen, die Folgendes angibt:

* Objekte, die im letzten Monat abgerufen wurden, sollten auf lokalen Speicherknoten verbleiben.
* Objekte, die im letzten Monat nicht abgeholt wurden, sollten an einen externen Standort gebracht werden.


Standardmäßig sind Aktualisierungen der letzten Zugriffszeit deaktiviert.  Wenn Ihr StorageGRID System eine ILM-Regel enthält, die die Option *Letzter Zugriffszeitpunkt* verwendet, und Sie möchten, dass diese Option auf Objekte in diesem Bucket angewendet wird, müssen Sie Aktualisierungen des letzten Zugriffszeitpunkts für die in dieser Regel angegebenen S3-Buckets aktivieren.


CAUTION: Das Aktualisieren der letzten Zugriffszeit beim Abrufen eines Objekts kann die StorageGRID Leistung verringern, insbesondere bei kleinen Objekten.

Bei Aktualisierungen der letzten Zugriffszeit kommt es zu Leistungseinbußen, da StorageGRID bei jedem Abrufen von Objekten die folgenden zusätzlichen Schritte ausführen muss:

* Aktualisieren Sie die Objekte mit neuen Zeitstempeln
* Fügen Sie die Objekte zur ILM-Warteschlange hinzu, damit sie anhand der aktuellen ILM-Regeln und -Richtlinien neu bewertet werden können


Die Tabelle fasst das Verhalten zusammen, das auf alle Objekte im Bucket angewendet wird, wenn die letzte Zugriffszeit deaktiviert oder aktiviert ist.

[cols="1a,1a,1a,1a,1a"]
|===


.2+| Art der Anfrage 2+| Verhalten, wenn die letzte Zugriffszeit deaktiviert ist (Standard) 2+| Verhalten bei aktivierter letzter Zugriffszeit 


| Letzte Zugriffszeit aktualisiert? | Objekt zur ILM-Auswertungswarteschlange hinzugefügt? | Letzte Zugriffszeit aktualisiert? | Objekt zur ILM-Auswertungswarteschlange hinzugefügt? 


 a| 
Anforderung zum Abrufen eines Objekts, seiner Zugriffskontrollliste oder seiner Metadaten
 a| 
Nein
 a| 
Nein
 a| 
Ja
 a| 
Ja



 a| 
Anforderung zum Aktualisieren der Metadaten eines Objekts
 a| 
Ja
 a| 
Ja
 a| 
Ja
 a| 
Ja



 a| 
Anfrage zum Auflisten von Objekten oder Objektversionen
 a| 
Nein
 a| 
Nein
 a| 
Nein
 a| 
Nein



 a| 
Anforderung zum Kopieren eines Objekts von einem Bucket in einen anderen
 a| 
* Nein, für die Quellkopie
* Ja, für die Zielkopie

 a| 
* Nein, für die Quellkopie
* Ja, für die Zielkopie

 a| 
* Ja, für die Quellkopie
* Ja, für die Zielkopie

 a| 
* Ja, für die Quellkopie
* Ja, für die Zielkopie




 a| 
Anfrage zum Abschließen eines mehrteiligen Uploads
 a| 
Ja, für das montierte Objekt
 a| 
Ja, für das montierte Objekt
 a| 
Ja, für das montierte Objekt
 a| 
Ja, für das montierte Objekt

|===
.Schritte
. Wählen Sie im Dashboard *Buckets anzeigen* oder wählen Sie *STORAGE (S3)* > *Buckets*.
. Wählen Sie den Bucket-Namen aus der Tabelle aus.
+
Die Bucket-Detailseite wird angezeigt.

. Wählen Sie auf der Registerkarte *Bucket-Optionen* das Akkordeon *Aktualisierungen der letzten Zugriffszeit* aus.
. Aktivieren oder deaktivieren Sie Aktualisierungen der letzten Zugriffszeit.
. Wählen Sie *Änderungen speichern*.

