---
permalink: tenant/manage-bucket-policy.html 
sidebar: sidebar 
keywords: how to create S3 tenant groups, federated group, local group 
summary: Sie können den Benutzerzugriff für einen S3-Bucket und die Objekte in diesem Bucket steuern. 
---
= Bucket-Richtlinie verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Benutzerzugriff für einen S3-Bucket und die Objekte in diesem Bucket steuern.

.Bevor Sie beginnen
* Sie sind beim Tenant Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie gehören einer Benutzergruppe an, die über dielink:tenant-management-permissions.html["Root-Zugriffsberechtigung"] .  Die Berechtigungen „Alle Buckets anzeigen“ und „Alle Buckets verwalten“ erlauben nur das Anzeigen.
* Sie haben überprüft, dass die erforderliche Anzahl an Speicherknoten und Sites verfügbar ist.  Wenn an einem Standort zwei oder mehr Speicherknoten nicht verfügbar sind oder ein Standort nicht verfügbar ist, können diese Einstellungen möglicherweise nicht geändert werden.


.Schritte
. Wählen Sie *Buckets* und dann den Bucket aus, den Sie verwalten möchten.
. Wählen Sie auf der Bucket-Detailseite *Bucket-Zugriff* > *Bucket-Richtlinie* aus.
. Führen Sie einen der folgenden Schritte aus:
+
** Geben Sie eine Bucket-Richtlinie ein, indem Sie das Kontrollkästchen *Richtlinie aktivieren* aktivieren.  Geben Sie dann eine gültige Zeichenfolge im JSON-Format ein.
+
Jede Bucket-Richtlinie hat eine Größenbeschränkung von 20.480 Bytes.

** Ändern Sie eine vorhandene Richtlinie, indem Sie die Zeichenfolge bearbeiten.
** Deaktivieren Sie eine Richtlinie, indem Sie die Option *Richtlinie aktivieren* abwählen.




Ausführliche Informationen zu Bucket-Richtlinien, einschließlich Sprachsyntax und Beispielen, finden Sie unterlink:../s3/example-bucket-policies.html["Beispiele für Bucket-Richtlinien"] .
