---
permalink: tenant/managing-s3-access-keys.html 
sidebar: sidebar 
keywords: how to manage s3 access key 
summary: Jeder Benutzer eines S3-Mandantenkontos muss über einen Zugriffsschlüssel verfügen, um Objekte im StorageGRID System zu speichern und abzurufen.  Ein Zugriffsschlüssel besteht aus einer Zugriffsschlüssel-ID und einem geheimen Zugriffsschlüssel. 
---
= S3-Zugriffsschlüssel verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jeder Benutzer eines S3-Mandantenkontos muss über einen Zugriffsschlüssel verfügen, um Objekte im StorageGRID System zu speichern und abzurufen.  Ein Zugriffsschlüssel besteht aus einer Zugriffsschlüssel-ID und einem geheimen Zugriffsschlüssel.

S3-Zugriffsschlüssel können wie folgt verwaltet werden:

* Benutzer mit der Berechtigung *Eigene S3-Anmeldeinformationen verwalten* können ihre eigenen S3-Zugriffsschlüssel erstellen oder entfernen.
* Benutzer mit der Berechtigung *Root-Zugriff* können die Zugriffsschlüssel für das S3-Root-Konto und alle anderen Benutzer verwalten.  Root-Zugriffsschlüssel bieten dem Mandanten vollständigen Zugriff auf alle Buckets und Objekte, sofern dies nicht ausdrücklich durch eine Bucket-Richtlinie deaktiviert wird.


StorageGRID unterstützt die Authentifizierung mit Signature Version 2 und Signature Version 4.  Der kontoübergreifende Zugriff ist nicht zulässig, es sei denn, er wird ausdrücklich durch eine Bucket-Richtlinie aktiviert.
