---
permalink: rhel/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create red hat linux node configuration files, port, remap, port remap 
summary: Knotenkonfigurationsdateien sind kleine Textdateien, die die Informationen bereitstellen, die der StorageGRID Hostdienst benötigt, um einen Knoten zu starten und ihn mit den entsprechenden Netzwerk- und Blockspeicherressourcen zu verbinden.  Knotenkonfigurationsdateien werden für virtuelle Knoten verwendet und nicht für Appliance-Knoten. 
---
= Erstellen Sie Knotenkonfigurationsdateien für Red Hat Enterprise Linux-Bereitstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Knotenkonfigurationsdateien sind kleine Textdateien, die die Informationen bereitstellen, die der StorageGRID Hostdienst benötigt, um einen Knoten zu starten und ihn mit den entsprechenden Netzwerk- und Blockspeicherressourcen zu verbinden.  Knotenkonfigurationsdateien werden für virtuelle Knoten verwendet und nicht für Appliance-Knoten.



== Speicherort für Knotenkonfigurationsdateien

Platzieren Sie die Konfigurationsdatei für jeden StorageGRID -Knoten im `/etc/storagegrid/nodes` Verzeichnis auf dem Host, auf dem der Knoten ausgeführt wird.  Wenn Sie beispielsweise planen, einen Admin-Knoten, einen Gateway-Knoten und einen Storage-Knoten auf HostA auszuführen, müssen Sie drei Knotenkonfigurationsdateien in `/etc/storagegrid/nodes` auf HostA.

Sie können die Konfigurationsdateien mit einem Texteditor wie vim oder nano direkt auf jedem Host erstellen oder sie an einem anderen Ort erstellen und auf jeden Host verschieben.



== Benennung von Knotenkonfigurationsdateien

Die Namen der Konfigurationsdateien sind aussagekräftig.  Das Format ist `node-name.conf` , Wo `node-name` ist ein Name, den Sie dem Knoten zuweisen.  Dieser Name wird im StorageGRID Installationsprogramm angezeigt und für Knotenwartungsvorgänge wie die Knotenmigration verwendet.

Knotennamen müssen diesen Regeln entsprechen:

* Muss eindeutig sein
* Muss mit einem Buchstaben beginnen
* Kann die Zeichen A bis Z und a bis z enthalten
* Kann die Zahlen 0 bis 9 enthalten
* Kann einen oder mehrere Bindestriche (-) enthalten
* Darf nicht mehr als 32 Zeichen umfassen, ohne die `.conf` Verlängerung


Alle Dateien in `/etc/storagegrid/nodes` die diesen Namenskonventionen nicht folgen, werden vom Hostdienst nicht analysiert.

Wenn Sie für Ihr Grid eine Multi-Site-Topologie planen, könnte ein typisches Knotenbenennungsschema wie folgt aussehen:

`site-nodetype-nodenumber.conf`

Sie könnten beispielsweise verwenden `dc1-adm1.conf` für den ersten Admin-Knoten im Rechenzentrum 1 und `dc2-sn3.conf` für den dritten Speicherknoten im Rechenzentrum 2.  Sie können jedoch jedes beliebige Schema verwenden, solange alle Knotennamen den Namensregeln entsprechen.



== Inhalt einer Knotenkonfigurationsdatei

Eine Konfigurationsdatei enthält Schlüssel-/Wertpaare mit einem Schlüssel und einem Wert pro Zeile.  Befolgen Sie für jedes Schlüssel-/Wertpaar die folgenden Regeln:

* Der Schlüssel und der Wert müssen durch ein Gleichheitszeichen getrennt sein(`=` ) und optionalem Leerzeichen.
* Die Schlüssel dürfen keine Leerzeichen enthalten.
* Die Werte können eingebettete Leerzeichen enthalten.
* Vorangehende oder nachfolgende Leerzeichen werden ignoriert.


Die folgende Tabelle definiert die Werte für alle unterstützten Schlüssel.  Jeder Schlüssel hat eine der folgenden Bezeichnungen:

* *Erforderlich*: Erforderlich für jeden Knoten oder für die angegebenen Knotentypen
* *Best Practice*: Optional, aber empfohlen
* *Optional*: Optional für alle Knoten




=== Admin-Netzwerkschlüssel



==== ADMIN_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Grid-Netzwerk-IPv4-Adresse des primären Admin-Knotens für das Grid, zu dem dieser Knoten gehört.  Verwenden Sie denselben Wert, den Sie für GRID_NETWORK_IP für den Grid-Knoten mit NODE_TYPE = VM_Admin_Node und ADMIN_ROLE = Primary angegeben haben. Wenn Sie diesen Parameter weglassen, versucht der Knoten, mithilfe von mDNS einen primären Admin-Knoten zu ermitteln.

link:how-grid-nodes-discover-primary-admin-node.html["So erkennen Grid-Knoten den primären Admin-Knoten"]

*Hinweis*: Dieser Wert wird auf dem primären Admin-Knoten ignoriert und ist möglicherweise verboten.
 a| 
Bewährte Methode

|===


==== ADMIN_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
DHCP, STATISCH oder DEAKTIVIERT
 a| 
Optional

|===


==== ADMIN_NETWORK_ESL

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Durch Kommas getrennte Liste von Subnetzen in CIDR-Notation, mit denen dieser Knoten über das Admin-Netzwerk-Gateway kommunizieren soll.

Beispiel: `172.16.0.0/21,172.17.0.0/21`
 a| 
Optional

|===


==== ADMIN_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse des lokalen Admin-Netzwerk-Gateways für diesen Knoten.  Muss sich im durch ADMIN_NETWORK_IP und ADMIN_NETWORK_MASK definierten Subnetz befinden.  Dieser Wert wird für DHCP-konfigurierte Netzwerke ignoriert.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn `ADMIN_NETWORK_ESL` angegeben ist.  Andernfalls optional.

|===


==== ADMIN_NETWORK_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse dieses Knotens im Admin-Netzwerk.  Dieser Schlüssel ist nur erforderlich, wenn ADMIN_NETWORK_CONFIG = STATIC ist. Geben Sie ihn nicht für andere Werte an.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn ADMIN_NETWORK_CONFIG = STATIC.

Andernfalls optional.

|===


==== ADMIN_NETWORK_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die MAC-Adresse für die Admin-Netzwerkschnittstelle im Container.

Dieses Feld ist optional.  Wenn es weggelassen wird, wird automatisch eine MAC-Adresse generiert.

Muss aus 6 Paaren hexadezimaler Ziffern bestehen, die durch Doppelpunkte getrennt sind.

Beispiel: `b2:9c:02:c2:27:10`
 a| 
Optional

|===


==== ADMIN_NETWORK_MASK

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Netzmaske für diesen Knoten im Admin-Netzwerk.  Geben Sie diesen Schlüssel an, wenn ADMIN_NETWORK_CONFIG = STATIC ist. Geben Sie ihn nicht für andere Werte an.

Beispiele:

`255.255.255.0`

`255.255.248.0`
 a| 
Erforderlich, wenn ADMIN_NETWORK_IP angegeben ist und ADMIN_NETWORK_CONFIG = STATIC.

Andernfalls optional.

|===


==== ADMIN_NETWORK_MTU

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die maximale Übertragungseinheit (MTU) für diesen Knoten im Admin-Netzwerk.  Nicht angeben, wenn ADMIN_NETWORK_CONFIG = DHCP.  Falls angegeben, muss der Wert zwischen 1280 und 9216 liegen.  Wenn es weggelassen wird, wird 1500 verwendet.

Wenn Sie Jumbo-Frames verwenden möchten, legen Sie die MTU auf einen für Jumbo-Frames geeigneten Wert fest, beispielsweise 9000.  Andernfalls behalten Sie den Standardwert bei.

*WICHTIG*: Der MTU-Wert des Netzwerks muss mit dem Wert übereinstimmen, der auf dem Switch-Port konfiguriert ist, mit dem der Knoten verbunden ist.  Andernfalls kann es zu Problemen mit der Netzwerkleistung oder zu Paketverlusten kommen.

Beispiele:

`1500`

`8192`
 a| 
Optional

|===


==== ADMIN_NETWORK_TARGET

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name des Hostgeräts, das Sie für den Admin-Netzwerkzugriff durch den StorageGRID -Knoten verwenden.  Es werden nur Netzwerkschnittstellennamen unterstützt.  Normalerweise verwenden Sie einen anderen Schnittstellennamen als den, der für GRID_NETWORK_TARGET oder CLIENT_NETWORK_TARGET angegeben wurde.

*Hinweis*: Verwenden Sie keine Bond- oder Bridge-Geräte als Netzwerkziel.  Konfigurieren Sie entweder ein VLAN (oder eine andere virtuelle Schnittstelle) über dem Bond-Gerät oder verwenden Sie ein Bridge- und Virtual-Ethernet-Paar (veth).

*Best Practice*: Geben Sie einen Wert an, auch wenn dieser Knoten zunächst keine Admin-Netzwerk-IP-Adresse hat.  Dann können Sie später eine Admin-Netzwerk-IP-Adresse hinzufügen, ohne den Knoten auf dem Host neu konfigurieren zu müssen.

Beispiele:

`bond0.1002`

`ens256`
 a| 
Bewährte Methode

|===


==== ADMIN_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Schnittstelle (Dies ist der einzige unterstützte Wert.)
 a| 
Optional

|===


==== ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Wahr oder Falsch

Setzen Sie den Schlüssel auf „true“, damit der StorageGRID -Container die MAC-Adresse der Host-Zielschnittstelle im Admin-Netzwerk verwendet.

*Best Practice:* Verwenden Sie in Netzwerken, in denen der Promiscuous-Modus erforderlich wäre, stattdessen den Schlüssel ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Weitere Einzelheiten zum MAC-Klonen:

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen (Ubuntu oder Debian)"]

 a| 
Bewährte Methode

|===


==== ADMIN_ROLE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Primär oder nicht primär

Dieser Schlüssel ist nur erforderlich, wenn NODE_TYPE = VM_Admin_Node; geben Sie ihn nicht für andere Knotentypen an.
 a| 
Erforderlich, wenn NODE_TYPE = VM_Admin_Node

Andernfalls optional.

|===


=== Geräteschlüssel sperren



==== BLOCK_DEVICE_AUDIT_LOGS

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der speziellen Blockgerätedatei, die dieser Knoten zur dauerhaften Speicherung von Prüfprotokollen verwendet.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
Erforderlich für Knoten mit NODE_TYPE = VM_Admin_Node.  Geben Sie es nicht für andere Knotentypen an.

|===


==== BLOCK_DEVICE_RANGEDB_nnn

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der speziellen Blockgerätedatei, die dieser Knoten für die dauerhafte Objektspeicherung verwendet.  Dieser Schlüssel ist nur für Knoten mit NODE_TYPE = VM_Storage_Node erforderlich. Geben Sie ihn nicht für andere Knotentypen an.

Nur BLOCK_DEVICE_RANGEDB_000 ist erforderlich, der Rest ist optional.  Das für BLOCK_DEVICE_RANGEDB_000 angegebene Blockgerät muss mindestens 4 TB groß sein, die anderen können kleiner sein.

Lassen Sie keine Lücken.  Wenn Sie BLOCK_DEVICE_RANGEDB_005 angeben, müssen Sie auch BLOCK_DEVICE_RANGEDB_004 angeben.

*Hinweis*: Aus Kompatibilitätsgründen mit vorhandenen Bereitstellungen werden für aktualisierte Knoten zweistellige Schlüssel unterstützt.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
Erforderlich:

BLOCK_DEVICE_RANGEDB_000

Optional:

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== BLOCK_DEVICE_TABLES

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der speziellen Blockgerätedatei, die dieser Knoten zur dauerhaften Speicherung von Datenbanktabellen verwendet.  Dieser Schlüssel ist nur für Knoten mit NODE_TYPE = VM_Admin_Node erforderlich. Geben Sie ihn nicht für andere Knotentypen an.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
Erforderlich

|===


==== BLOCK_DEVICE_VAR_LOCAL

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der speziellen Blockgerätedatei, die dieser Knoten für seine `/var/local` dauerhafter Speicher.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
Erforderlich

|===


=== Client-Netzwerkschlüssel



==== CLIENT_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
DHCP, STATISCH oder DEAKTIVIERT
 a| 
Optional

|===


==== CLIENT_NETWORK_GATEWAY

[cols="4a,2a"]
|===


 a| 
Wert
 a| 
Bezeichnung



 a| 
IPv4-Adresse des lokalen Client-Netzwerk-Gateways für diesen Knoten, das sich im durch CLIENT_NETWORK_IP und CLIENT_NETWORK_MASK definierten Subnetz befinden muss.  Dieser Wert wird für DHCP-konfigurierte Netzwerke ignoriert.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Optional

|===


==== CLIENT_NETWORK_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse dieses Knotens im Client-Netzwerk.

Dieser Schlüssel ist nur erforderlich, wenn CLIENT_NETWORK_CONFIG = STATIC ist. Geben Sie ihn nicht für andere Werte an.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn CLIENT_NETWORK_CONFIG = STATIC

Andernfalls optional.

|===


==== CLIENT_NETWORK_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die MAC-Adresse für die Client-Netzwerkschnittstelle im Container.

Dieses Feld ist optional.  Wenn es weggelassen wird, wird automatisch eine MAC-Adresse generiert.

Muss aus 6 Paaren hexadezimaler Ziffern bestehen, die durch Doppelpunkte getrennt sind.

Beispiel: `b2:9c:02:c2:27:20`
 a| 
Optional

|===


==== CLIENT_NETWORK_MASK

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Netzmaske für diesen Knoten im Client-Netzwerk.

Geben Sie diesen Schlüssel an, wenn CLIENT_NETWORK_CONFIG = STATIC ist. Geben Sie ihn nicht für andere Werte an.

Beispiele:

`255.255.255.0`

`255.255.248.0`
 a| 
Erforderlich, wenn CLIENT_NETWORK_IP angegeben ist und CLIENT_NETWORK_CONFIG = STATIC

Andernfalls optional.

|===


==== CLIENT_NETWORK_MTU

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die maximale Übertragungseinheit (MTU) für diesen Knoten im Client-Netzwerk.  Nicht angeben, wenn CLIENT_NETWORK_CONFIG = DHCP.  Falls angegeben, muss der Wert zwischen 1280 und 9216 liegen.  Wenn es weggelassen wird, wird 1500 verwendet.

Wenn Sie Jumbo-Frames verwenden möchten, legen Sie die MTU auf einen für Jumbo-Frames geeigneten Wert fest, beispielsweise 9000.  Andernfalls behalten Sie den Standardwert bei.

*WICHTIG*: Der MTU-Wert des Netzwerks muss mit dem Wert übereinstimmen, der auf dem Switch-Port konfiguriert ist, mit dem der Knoten verbunden ist.  Andernfalls kann es zu Problemen mit der Netzwerkleistung oder zu Paketverlusten kommen.

Beispiele:

`1500`

`8192`
 a| 
Optional

|===


==== CLIENT_NETWORK_TARGET

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name des Hostgeräts, das Sie für den Client-Netzwerkzugriff durch den StorageGRID -Knoten verwenden.  Es werden nur Netzwerkschnittstellennamen unterstützt.  Normalerweise verwenden Sie einen anderen Schnittstellennamen als den, der für GRID_NETWORK_TARGET oder ADMIN_NETWORK_TARGET angegeben wurde.

*Hinweis*: Verwenden Sie keine Bond- oder Bridge-Geräte als Netzwerkziel.  Konfigurieren Sie entweder ein VLAN (oder eine andere virtuelle Schnittstelle) über dem Bond-Gerät oder verwenden Sie ein Bridge- und Virtual-Ethernet-Paar (veth).

*Best Practice:* Geben Sie einen Wert an, auch wenn dieser Knoten zunächst keine Client-Netzwerk-IP-Adresse hat.  Dann können Sie später eine Client-Netzwerk-IP-Adresse hinzufügen, ohne den Knoten auf dem Host neu konfigurieren zu müssen.

Beispiele:

`bond0.1003`

`ens423`
 a| 
Bewährte Methode

|===


==== CLIENT_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Schnittstelle (Dies ist der einzige unterstützte Wert.)
 a| 
Optional

|===


==== CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Wahr oder Falsch

Setzen Sie den Schlüssel auf „true“, damit der StorageGRID Container die MAC-Adresse der Host-Zielschnittstelle im Client-Netzwerk verwendet.

*Best Practice:* Verwenden Sie in Netzwerken, in denen der Promiscuous-Modus erforderlich wäre, stattdessen den Schlüssel CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Weitere Einzelheiten zum MAC-Klonen:

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen (Ubuntu oder Debian)"]

 a| 
Bewährte Methode

|===


=== Grid-Netzwerkschlüssel



==== GRID_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
STATISCH oder DHCP

Der Standardwert ist STATIC, wenn nicht anders angegeben.
 a| 
Bewährte Methode

|===


==== GRID_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse des lokalen Grid-Netzwerk-Gateways für diesen Knoten, das sich im durch GRID_NETWORK_IP und GRID_NETWORK_MASK definierten Subnetz befinden muss.  Dieser Wert wird für DHCP-konfigurierte Netzwerke ignoriert.

Wenn das Grid-Netzwerk ein einzelnes Subnetz ohne Gateway ist, verwenden Sie entweder die Standard-Gateway-Adresse für das Subnetz (XYZ1) oder den GRID_NETWORK_IP-Wert dieses Knotens. Beide Werte vereinfachen mögliche zukünftige Erweiterungen des Grid-Netzwerks.
 a| 
Erforderlich

|===


==== GRID_NETWORK_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse dieses Knotens im Grid-Netzwerk.  Dieser Schlüssel ist nur erforderlich, wenn GRID_NETWORK_CONFIG = STATIC ist. Geben Sie ihn nicht für andere Werte an.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn GRID_NETWORK_CONFIG = STATIC

Andernfalls optional.

|===


==== GRID_NETWORK_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die MAC-Adresse für die Grid-Netzwerkschnittstelle im Container.

Muss aus 6 Paaren hexadezimaler Ziffern bestehen, die durch Doppelpunkte getrennt sind.

Beispiel: `b2:9c:02:c2:27:30`
 a| 
Optional

Wenn es weggelassen wird, wird automatisch eine MAC-Adresse generiert.

|===


==== GRID_NETWORK_MASK

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Netzmaske für diesen Knoten im Grid-Netzwerk.  Geben Sie diesen Schlüssel an, wenn GRID_NETWORK_CONFIG = STATIC ist. Geben Sie ihn nicht für andere Werte an.

Beispiele:

`255.255.255.0`

`255.255.248.0`
 a| 
Erforderlich, wenn GRID_NETWORK_IP angegeben ist und GRID_NETWORK_CONFIG = STATIC.

Andernfalls optional.

|===


==== GRID_NETWORK_MTU

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die maximale Übertragungseinheit (MTU) für diesen Knoten im Grid-Netzwerk.  Nicht angeben, wenn GRID_NETWORK_CONFIG = DHCP.  Falls angegeben, muss der Wert zwischen 1280 und 9216 liegen.  Wenn es weggelassen wird, wird 1500 verwendet.

Wenn Sie Jumbo-Frames verwenden möchten, legen Sie die MTU auf einen für Jumbo-Frames geeigneten Wert fest, beispielsweise 9000.  Andernfalls behalten Sie den Standardwert bei.

*WICHTIG*: Der MTU-Wert des Netzwerks muss mit dem Wert übereinstimmen, der auf dem Switch-Port konfiguriert ist, mit dem der Knoten verbunden ist.  Andernfalls kann es zu Problemen mit der Netzwerkleistung oder zu Paketverlusten kommen.

*WICHTIG*: Für die beste Netzwerkleistung sollten alle Knoten mit ähnlichen MTU-Werten auf ihren Grid-Netzwerkschnittstellen konfiguriert werden.  Die Warnung *MTU-Fehlanpassung des Grid-Netzwerks* wird ausgelöst, wenn es bei den MTU-Einstellungen für das Grid-Netzwerk auf einzelnen Knoten einen signifikanten Unterschied gibt.  Die MTU-Werte müssen nicht für alle Netzwerktypen gleich sein.

Beispiele:

`1500`

`8192`
 a| 
Optional

|===


==== GRID_NETWORK_TARGET

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name des Hostgeräts, das Sie für den Grid-Netzwerkzugriff durch den StorageGRID -Knoten verwenden.  Es werden nur Netzwerkschnittstellennamen unterstützt.  Normalerweise verwenden Sie einen anderen Schnittstellennamen als den, der für ADMIN_NETWORK_TARGET oder CLIENT_NETWORK_TARGET angegeben wurde.

*Hinweis*: Verwenden Sie keine Bond- oder Bridge-Geräte als Netzwerkziel.  Konfigurieren Sie entweder ein VLAN (oder eine andere virtuelle Schnittstelle) über dem Bond-Gerät oder verwenden Sie ein Bridge- und Virtual-Ethernet-Paar (veth).

Beispiele:

`bond0.1001`

`ens192`
 a| 
Erforderlich

|===


==== GRID_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Schnittstelle (Dies ist der einzige unterstützte Wert.)
 a| 
Optional

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Wahr oder Falsch

Setzen Sie den Wert des Schlüssels auf „true“, damit der StorageGRID Container die MAC-Adresse der Host-Zielschnittstelle im Grid-Netzwerk verwendet.

*Best Practice:* Verwenden Sie in Netzwerken, in denen der Promiscuous-Modus erforderlich wäre, stattdessen den Schlüssel GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Weitere Einzelheiten zum MAC-Klonen:

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen (Ubuntu oder Debian)"]

 a| 
Bewährte Methode

|===


=== Installationskennwortschlüssel (temporär)



==== BENUTZERDEFINIERTER_TEMPORÄRER_PASSWORT_HASH

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Legen Sie für den primären Admin-Knoten während der Installation ein temporäres Standardkennwort für die StorageGRID -Installations-API fest.

*Hinweis*: Legen Sie nur auf dem primären Admin-Knoten ein Installationskennwort fest.  Wenn Sie versuchen, ein Kennwort für einen anderen Knotentyp festzulegen, schlägt die Validierung der Knotenkonfigurationsdatei fehl.

Das Festlegen dieses Werts hat nach Abschluss der Installation keine Auswirkungen mehr.

Wenn dieser Schlüssel weggelassen wird, wird standardmäßig kein temporäres Passwort festgelegt.  Alternativ können Sie mithilfe der StorageGRID Installations-API ein temporäres Passwort festlegen.

Muss ein `crypt()` SHA-512-Passwort-Hash mit Format `$6$<salt>$<password hash>` für ein Passwort mit mindestens 8 und höchstens 32 Zeichen.

Dieser Hash kann mit CLI-Tools generiert werden, wie zum Beispiel dem `openssl passwd` Befehl im SHA-512-Modus.
 a| 
Bewährte Methode

|===


=== Schnittstellenschlüssel



==== SCHNITTSTELLENZIEL_nnnn

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name und optionale Beschreibung für eine zusätzliche Schnittstelle, die Sie diesem Knoten hinzufügen möchten.  Sie können jedem Knoten mehrere zusätzliche Schnittstellen hinzufügen.

Geben Sie für _nnnn_ eine eindeutige Nummer für jeden INTERFACE_TARGET-Eintrag an, den Sie hinzufügen.

Geben Sie als Wert den Namen der physischen Schnittstelle auf dem Bare-Metal-Host an.  Fügen Sie dann optional ein Komma hinzu und geben Sie eine Beschreibung der Schnittstelle ein, die auf der Seite „VLAN-Schnittstellen“ und der Seite „HA-Gruppen“ angezeigt wird.

Beispiel: `INTERFACE_TARGET_0001=ens256, Trunk`

Wenn Sie eine Trunk-Schnittstelle hinzufügen, müssen Sie eine VLAN-Schnittstelle in StorageGRID konfigurieren.  Wenn Sie eine Zugriffsschnittstelle hinzufügen, können Sie die Schnittstelle direkt zu einer HA-Gruppe hinzufügen. Sie müssen keine VLAN-Schnittstelle konfigurieren.
 a| 
Optional

|===


=== Maximaler RAM-Schlüssel



==== MAXIMALER RAM

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die maximale RAM-Menge, die dieser Knoten verbrauchen darf.  Wenn dieser Schlüssel weggelassen wird, unterliegt der Knoten keinen Speicherbeschränkungen.  Wenn Sie dieses Feld für einen Knoten auf Produktionsebene festlegen, geben Sie einen Wert an, der mindestens 24 GB und 16 bis 32 GB weniger als der gesamte System-RAM beträgt.

*Hinweis*: Der RAM-Wert wirkt sich auf den tatsächlich für Metadaten reservierten Speicherplatz eines Knotens aus. Siehe dielink:../admin/managing-object-metadata-storage.html["Beschreibung, was Metadata Reserved Space ist"] .

Das Format für dieses Feld ist `_numberunit_` , Wo `_unit_` kann sein `b` , `k` , `m` , oder `g` .

Beispiele:

`24g`

`38654705664b`

*Hinweis*: Wenn Sie diese Option verwenden möchten, müssen Sie die Kernel-Unterstützung für Speicher-Cgroups aktivieren.
 a| 
Optional

|===


=== Knotentypschlüssel



==== KNOTENTYP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Knotentyp:

* VM_Admin_Node
* VM_Speicherknoten
* VM_Archive_Node
* VM_API_Gateway

 a| 
Erforderlich

|===


==== SPEICHERTYP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Definiert den Objekttyp, den ein Speicherknoten enthält. Weitere Informationen finden Sie unter link:../primer/what-storage-node-is.html#types-of-storage-nodes["Arten von Speicherknoten"] .  Dieser Schlüssel ist nur für Knoten mit NODE_TYPE = VM_Storage_Node erforderlich. Geben Sie ihn nicht für andere Knotentypen an.  Speichertypen:

* kombiniert
* Daten
* Metadaten


*Hinweis*: Wenn STORAGE_TYPE nicht angegeben ist, wird der Speicherknotentyp standardmäßig auf „Kombiniert (Daten und Metadaten)“ eingestellt.
 a| 
Optional

|===


=== Port-Neuzuordnungsschlüssel



==== PORT_REMAP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Ordnet jeden Port neu zu, der von einem Knoten für die interne oder externe Grid-Knotenkommunikation verwendet wird.  Eine Neuzuordnung der Ports ist erforderlich, wenn die Netzwerkrichtlinien des Unternehmens einen oder mehrere von StorageGRID verwendete Ports einschränken, wie in beschrieben.link:../network/internal-grid-node-communications.html["Interne Grid-Knoten-Kommunikation"] oderlink:../network/external-communications.html["Externe Kommunikation"] .

*WICHTIG*: Ordnen Sie die Ports, die Sie zum Konfigurieren der Endpunkte des Lastenausgleichs verwenden möchten, nicht neu zu.

*Hinweis*: Wenn nur PORT_REMAP festgelegt ist, wird die von Ihnen angegebene Zuordnung sowohl für eingehende als auch für ausgehende Kommunikation verwendet.  Wenn auch PORT_REMAP_INBOUND angegeben ist, gilt PORT_REMAP nur für ausgehende Kommunikation.

Das verwendete Format ist: `_network type_/_protocol_/_default port used by grid node_/_new port_` , Wo `_network type_` ist Grid, Admin oder Client und `_protocol_` ist TCP oder UDP.

Beispiel: `PORT_REMAP = client/tcp/18082/443`

Sie können auch mehrere Ports mithilfe einer durch Kommas getrennten Liste neu zuordnen.

Beispiel: `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
Optional

|===


==== PORT_REMAP_INBOUND

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Ordnet eingehende Kommunikation dem angegebenen Port neu zu.  Wenn Sie PORT_REMAP_INBOUND angeben, aber keinen Wert für PORT_REMAP angeben, bleibt die ausgehende Kommunikation für den Port unverändert.

*WICHTIG*: Ordnen Sie die Ports, die Sie zum Konfigurieren der Endpunkte des Lastenausgleichs verwenden möchten, nicht neu zu.

Das verwendete Format ist: `_network type_/_protocol_/_remapped port_/_default port used by grid node_` , Wo `_network type_` ist Grid, Admin oder Client und `_protocol_` ist TCP oder UDP.

Beispiel: `PORT_REMAP_INBOUND = grid/tcp/3022/22`

Sie können auch mehrere eingehende Ports mithilfe einer durch Kommas getrennten Liste neu zuordnen.

Beispiel: `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
Optional

|===