---
permalink: admin/administering-storagegrid-system.html 
sidebar: sidebar 
keywords: administration overview 
summary: Verwenden Sie diese Anweisungen, um ein StorageGRID -System zu konfigurieren und zu verwalten. 
---
= Verwalten eines StorageGRID -Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie diese Anweisungen, um ein StorageGRID -System zu konfigurieren und zu verwalten.

Diese Anweisungen beschreiben, wie Sie mit dem Grid Manager Gruppen und Benutzer einrichten, Mandantenkonten erstellen, um S3-Clientanwendungen das Speichern und Abrufen von Objekten zu ermöglichen, StorageGRID -Netzwerke konfigurieren und verwalten, AutoSupport konfigurieren, Knoteneinstellungen verwalten und vieles mehr.

Diese Anweisungen richten sich an technisches Personal, das ein StorageGRID -System nach der Installation konfiguriert, verwaltet und unterstützt.

.Bevor Sie beginnen
* Sie verfügen über ein allgemeines Verständnis des StorageGRID -Systems.
* Sie verfügen über ziemlich detaillierte Kenntnisse zu Linux-Befehlsshells, Netzwerken sowie der Einrichtung und Konfiguration von Serverhardware.

