---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Wenn Sie ein lokaler Benutzer des Grid Managers sind, können Sie Ihr eigenes Passwort ändern. 
---
= Ändern Sie Ihr Passwort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein lokaler Benutzer des Grid Managers sind, können Sie Ihr eigenes Passwort ändern.

.Bevor Sie beginnen
Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .

.Informationen zu diesem Vorgang
Wenn Sie sich als Verbundbenutzer bei StorageGRID anmelden oder Single Sign-On (SSO) aktiviert ist, können Sie Ihr Kennwort im Grid Manager nicht ändern.  Stattdessen müssen Sie Ihr Kennwort in der externen Identitätsquelle ändern, beispielsweise Active Directory oder OpenLDAP.

.Schritte
. Wählen Sie in der Kopfzeile des Grid Managers *_Ihr Name_* > *Passwort ändern*.
. Geben Sie Ihr aktuelles Passwort ein.
. Geben Sie ein neues Passwort ein.
+
Ihr Passwort muss mindestens 8 und darf nicht mehr als 32 Zeichen enthalten.  Bei Passwörtern wird zwischen Groß- und Kleinschreibung unterschieden.

. Geben Sie das neue Passwort erneut ein.
. Wählen Sie *Speichern*.

