---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: Durch das Ändern der SSH-Zugriffskennwörter für Admin-Knoten werden auch die eindeutigen Sätze interner SSH-Schlüssel für jeden Knoten im Raster aktualisiert.  Der primäre Admin-Knoten verwendet diese SSH-Schlüssel, um mithilfe einer sicheren, passwortlosen Authentifizierung auf Knoten zuzugreifen. 
---
= SSH-Zugriffskennwörter für Admin-Knoten ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das Ändern der SSH-Zugriffskennwörter für Admin-Knoten werden auch die eindeutigen Sätze interner SSH-Schlüssel für jeden Knoten im Raster aktualisiert.  Der primäre Admin-Knoten verwendet diese SSH-Schlüssel, um mithilfe einer sicheren, passwortlosen Authentifizierung auf Knoten zuzugreifen.

Verwenden Sie einen SSH-Schlüssel, um sich bei einem Knoten anzumelden als `admin` oder an den Root-Benutzer einer VM oder einer physischen Konsolenverbindung.

.Bevor Sie beginnen
* Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie haben dielink:admin-group-permissions.html["Wartungs- oder Root-Zugriffsberechtigung"] .
* Sie verfügen über die aktuelle Bereitstellungspassphrase.


.Informationen zu diesem Vorgang
Die neuen Zugangspasswörter für Admin-Knoten und die neuen internen Schlüssel für jeden Knoten werden im `Passwords.txt` Datei im Wiederherstellungspaket. Die Schlüssel sind in der Spalte „Passwort“ dieser Datei aufgeführt.

Für die SSH-Schlüssel, die für die Kommunikation zwischen Knoten verwendet werden, gibt es separate SSH-Zugriffskennwörter.  Diese werden durch dieses Verfahren nicht verändert.



== Zugriff auf den Assistenten

.Schritte
. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Grid-Passwörter*.
. Wählen Sie unter *SSH-Schlüssel ändern* die Option *Änderung vornehmen*.




== [[download-current]]Laden Sie das aktuelle Wiederherstellungspaket herunter

Laden Sie vor dem Ändern der SSH-Zugriffsschlüssel das aktuelle Wiederherstellungspaket herunter. Sie können die Schlüssel in dieser Datei verwenden, wenn der Schlüsseländerungsprozess für einen beliebigen Knoten fehlschlägt.

.Schritte
. Geben Sie die Bereitstellungspassphrase für Ihr Grid ein.
. Wählen Sie *Wiederherstellungspaket herunterladen*.
. Kopieren Sie die Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Die Datei des Wiederherstellungspakets muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.

. Wählen Sie *Weiter*.
. Wenn das Bestätigungsdialogfeld angezeigt wird, wählen Sie *Ja*, wenn Sie bereit sind, mit der Änderung der SSH-Zugriffsschlüssel zu beginnen.
+

CAUTION: Sie können diesen Vorgang nach dem Start nicht mehr abbrechen.





== SSH-Zugriffsschlüssel ändern

Wenn der Prozess zum Ändern der SSH-Zugriffsschlüssel beginnt, wird ein neues Wiederherstellungspaket generiert, das die neuen Schlüssel enthält. Anschließend werden die Schlüssel auf jedem Knoten aktualisiert.

.Schritte
. Warten Sie, bis das neue Wiederherstellungspaket generiert wurde. Dies kann einige Minuten dauern.
. Wenn die Schaltfläche „Neues Wiederherstellungspaket herunterladen“ aktiviert ist, wählen Sie „Neues Wiederherstellungspaket herunterladen“ und speichern Sie die neue Wiederherstellungspaketdatei.(`.zip` ) an zwei sichere und getrennte Orte.
. Wenn der Download abgeschlossen ist:
+
.. Öffnen Sie die `.zip` Datei.
.. Bestätigen Sie, dass Sie auf die Inhalte zugreifen können, einschließlich der `Passwords.txt` Datei, die die neuen SSH-Zugriffsschlüssel enthält.
.. Kopieren Sie die neue Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Überschreiben Sie nicht das alte Wiederherstellungspaket.

+
Die Datei des Wiederherstellungspakets muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.



. Warten Sie, bis die Schlüssel auf jedem Knoten aktualisiert wurden. Dies kann einige Minuten dauern.
+
Wenn die Schlüssel für alle Knoten geändert werden, wird ein grünes Erfolgsbanner angezeigt.

+
Wenn während des Aktualisierungsvorgangs ein Fehler auftritt, wird in einer Bannermeldung die Anzahl der Knoten aufgelistet, deren Schlüssel nicht geändert werden konnten.  Das System wiederholt den Vorgang automatisch auf jedem Knoten, dessen Schlüssel nicht geändert werden konnte.  Wenn der Vorgang endet und einige Knoten immer noch keinen geänderten Schlüssel haben, wird die Schaltfläche *Wiederholen* angezeigt.

+
Wenn die Schlüsselaktualisierung für einen oder mehrere Knoten fehlgeschlagen ist:

+
.. Überprüfen Sie die in der Tabelle aufgeführten Fehlermeldungen.
.. Lösen Sie die Probleme.
.. Wählen Sie *Wiederholen*.
+
Durch einen erneuten Versuch werden nur die SSH-Zugriffsschlüssel auf den Knoten geändert, bei denen bei vorherigen Schlüsseländerungsversuchen ein Fehler aufgetreten ist.



. Nachdem die SSH-Zugriffsschlüssel für alle Knoten geändert wurden, löschen Sie die<<download-current,erstes Wiederherstellungspaket, das Sie heruntergeladen haben>> .
. Wählen Sie optional *WARTUNG* > *System* > *Wiederherstellungspaket*, um eine zusätzliche Kopie des neuen Wiederherstellungspakets herunterzuladen.

