---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Jeder Knoten in Ihrem Grid verfügt über ein eindeutiges Knotenkonsolenkennwort, das Sie zum Anmelden beim Knoten benötigen.  Verwenden Sie diese Schritte, um das Knotenkonsolenkennwort für jeden Knoten in Ihrem Raster zu ändern.  Die Passwörter werden im Wiederherstellungspaket gespeichert. 
---
= Ändern der Knotenkonsolenkennwörter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jeder Knoten in Ihrem Grid verfügt über ein eindeutiges Knotenkonsolenkennwort, das Sie zum Anmelden am Knoten benötigen.  Verwenden Sie diese Schritte, um jedes eindeutige Knotenkonsolenkennwort für jeden Knoten in Ihrem Raster zu ändern.

.Bevor Sie beginnen
* Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie haben dielink:admin-group-permissions.html["Wartungs- oder Root-Zugriffsberechtigung"] .
* Sie verfügen über die aktuelle Bereitstellungspassphrase.


.Informationen zu diesem Vorgang
Verwenden Sie das Kennwort der Knotenkonsole, um sich per SSH als „Administrator“ bei einem Knoten oder als Root-Benutzer bei einer VM-/physischen Konsolenverbindung anzumelden.  Der Prozess zum Ändern des Knotenkonsolenkennworts erstellt neue Kennwörter für jeden Knoten in Ihrem Raster und speichert die Kennwörter in einer aktualisierten `Passwords.txt` Datei im Wiederherstellungspaket.  Die Passwörter sind in der Spalte „Passwort“ in der Datei „Passwords.txt“ aufgeführt.


NOTE: Für die SSH-Schlüssel, die für die Kommunikation zwischen Knoten verwendet werden, gibt es separate SSH-Zugriffskennwörter.  Die SSH-Zugangspasswörter werden durch dieses Verfahren nicht geändert.



== Zugriff auf den Assistenten

.Schritte
. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Grid-Passwörter*.
. Wählen Sie unter *Passwörter der Knotenkonsole ändern* die Option *Änderung vornehmen* aus.




== Geben Sie die Bereitstellungspassphrase ein

.Schritte
. Geben Sie die Bereitstellungspassphrase für Ihr Grid ein.
. Wählen Sie *Weiter*.




== [[download-current]]Laden Sie das aktuelle Wiederherstellungspaket herunter

Laden Sie das aktuelle Wiederherstellungspaket herunter, bevor Sie die Passwörter der Knotenkonsole ändern. Sie können die Passwörter in dieser Datei verwenden, wenn der Passwortänderungsprozess für einen beliebigen Knoten fehlschlägt.

.Schritte
. Wählen Sie *Wiederherstellungspaket herunterladen*.
. Kopieren Sie die Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Die Datei des Wiederherstellungspakets muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.

. Wählen Sie *Weiter*.
. Wenn das Bestätigungsdialogfeld angezeigt wird, wählen Sie *Ja*, wenn Sie bereit sind, mit der Änderung der Knotenkonsolenkennwörter zu beginnen.
+
Sie können diesen Vorgang nach dem Start nicht mehr abbrechen.





== Ändern der Knotenkonsolenkennwörter

Wenn der Kennwortprozess der Knotenkonsole startet, wird ein neues Wiederherstellungspaket generiert, das die neuen Kennwörter enthält.  Anschließend werden die Passwörter auf jedem Knoten aktualisiert.

.Schritte
. Warten Sie, bis das neue Wiederherstellungspaket generiert wurde. Dies kann einige Minuten dauern.
. Wählen Sie *Neues Wiederherstellungspaket herunterladen*.
. Wenn der Download abgeschlossen ist:
+
.. Öffnen Sie die `.zip` Datei.
.. Bestätigen Sie, dass Sie auf die Inhalte zugreifen können, einschließlich der `Passwords.txt` Datei, die die neuen Passwörter für die Knotenkonsole enthält.
.. Kopieren Sie die neue Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Überschreiben Sie nicht das alte Wiederherstellungspaket.

+
Die Datei des Wiederherstellungspakets muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.



. Aktivieren Sie das Kontrollkästchen, um anzugeben, dass Sie das neue Wiederherstellungspaket heruntergeladen und den Inhalt überprüft haben.
. Wählen Sie *Passwörter der Knotenkonsole ändern* und warten Sie, bis alle Knoten mit den neuen Passwörtern aktualisiert wurden.  Dies kann einige Minuten dauern.
+
Wenn die Passwörter für alle Knoten geändert werden, wird ein grünes Erfolgsbanner angezeigt.  Fahren Sie mit dem nächsten Schritt fort.

+
Wenn während des Aktualisierungsvorgangs ein Fehler auftritt, wird in einer Bannermeldung die Anzahl der Knoten aufgelistet, deren Passwörter nicht geändert werden konnten. Das System wiederholt den Vorgang automatisch auf jedem Knoten, dessen Kennwort nicht geändert werden konnte. Wenn der Vorgang endet und einige Knoten immer noch kein geändertes Kennwort haben, wird die Schaltfläche *Wiederholen* angezeigt.

+
Wenn die Kennwortaktualisierung für einen oder mehrere Knoten fehlgeschlagen ist:

+
.. Überprüfen Sie die in der Tabelle aufgeführten Fehlermeldungen.
.. Lösen Sie die Probleme.
.. Wählen Sie *Wiederholen*.
+

NOTE: Durch einen erneuten Versuch werden nur die Knotenkonsolenkennwörter auf den Knoten geändert, bei denen bei vorherigen Kennwortänderungsversuchen ein Fehler aufgetreten ist.



. Nachdem die Passwörter der Knotenkonsole für alle Knoten geändert wurden, löschen Sie die<<download-current,erstes Wiederherstellungspaket, das Sie heruntergeladen haben>> .
. Verwenden Sie optional den Link *Wiederherstellungspaket*, um eine zusätzliche Kopie des neuen Wiederherstellungspakets herunterzuladen.

