---
permalink: admin/configuring-admin-proxy-settings.html 
sidebar: sidebar 
keywords: admin proxy, autosupport, non-transparent proxy 
summary: 'Wenn Sie AutoSupport Pakete über HTTP oder HTTPS senden, können Sie einen nicht transparenten Proxyserver zwischen Admin-Knoten und dem technischen Support \(AutoSupport\) konfigurieren.' 
---
= Konfigurieren der Administratorproxyeinstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie AutoSupport Pakete über HTTP oder HTTPS senden, können Sie einen nicht transparenten Proxyserver zwischen Admin-Knoten und technischem Support (AutoSupport) konfigurieren.

Weitere Informationen zu AutoSupport finden Sie unterlink:configure-autosupport-grid-manager.html["Konfigurieren Sie AutoSupport"] .

.Bevor Sie beginnen
* Du hastlink:admin-group-permissions.html["spezifische Zugriffsberechtigungen"] .
* Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .


.Informationen zu diesem Vorgang
Sie können die Einstellungen für einen einzelnen Admin-Proxy konfigurieren.

.Schritte
. Wählen Sie *KONFIGURATION* > *Sicherheit* > *Proxy-Einstellungen*.
+
Die Seite „Proxy-Einstellungen“ wird angezeigt.  Standardmäßig ist im Registerkartenmenü „Speicher“ ausgewählt.

. Wählen Sie die Registerkarte *Admin*.
. Aktivieren Sie das Kontrollkästchen *Admin-Proxy aktivieren*.
. Geben Sie den Hostnamen oder die IP-Adresse des Proxyservers ein.
. Geben Sie den Port ein, der für die Verbindung mit dem Proxyserver verwendet wird.
. Geben Sie optional einen Benutzernamen und ein Kennwort für den Proxyserver ein.
+
Lassen Sie diese Felder leer, wenn Ihr Proxyserver weder einen Benutzernamen noch ein Passwort erfordert.

. Wähle eine der folgenden:
+
** Wenn Sie die Verbindung zum Admin-Proxy sichern möchten, wählen Sie *Proxy-Zertifikat überprüfen*.  Laden Sie ein CA-Paket hoch, um die Authentizität der vom Admin-Proxyserver bereitgestellten SSL-Zertifikate zu überprüfen.
+

CAUTION: AutoSupport on Demand, E-Series AutoSupport über StorageGRID und die Update-Pfadbestimmung auf der StorageGRID -Upgrade-Seite funktionieren nicht, wenn ein Proxy-Zertifikat verifiziert wird.

+
Nachdem Sie das CA-Paket hochgeladen haben, werden dessen Metadaten angezeigt.

** Wenn Sie bei der Kommunikation mit dem Admin-Proxyserver keine Zertifikate validieren möchten, wählen Sie *Proxy-Zertifikat nicht überprüfen*.


. Wählen Sie *Speichern*.
+
Nachdem der Admin-Proxy gespeichert wurde, wird der Proxy-Server zwischen Admin-Knoten und technischem Support konfiguriert.

+

NOTE: Es kann bis zu 10 Minuten dauern, bis Proxy-Änderungen wirksam werden.

. Wenn Sie den Admin-Proxy deaktivieren müssen, deaktivieren Sie das Kontrollkästchen *Admin-Proxy aktivieren* und wählen Sie dann *Speichern*.

