---
permalink: admin/configuring-stored-object-compression.html 
sidebar: sidebar 
keywords: object compression, compress stored objects 
summary: Sie können die Objektkomprimierung aktivieren, um die Größe der in StorageGRID gespeicherten Objekte zu reduzieren, sodass die Objekte weniger Speicherplatz belegen. 
---
= Gespeicherte Objekte komprimieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Objektkomprimierung aktivieren, um die Größe der in StorageGRID gespeicherten Objekte zu reduzieren, sodass die Objekte weniger Speicherplatz belegen.

.Bevor Sie beginnen
* Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Du hastlink:admin-group-permissions.html["spezifische Zugriffsberechtigungen"] .


.Informationen zu diesem Vorgang
Standardmäßig ist die Objektkomprimierung deaktiviert.  Wenn Sie die Komprimierung aktivieren, versucht StorageGRID, jedes Objekt beim Speichern verlustfrei zu komprimieren.


NOTE: Wenn Sie diese Einstellung ändern, dauert es etwa eine Minute, bis die neue Einstellung übernommen wird.  Der konfigurierte Wert wird aus Leistungs- und Skalierungsgründen zwischengespeichert.

Bevor Sie die Objektkomprimierung aktivieren, beachten Sie Folgendes:

* Sie sollten *Gespeicherte Objekte komprimieren* nur auswählen, wenn Sie wissen, dass die gespeicherten Daten komprimierbar sind.
* Anwendungen, die Objekte in StorageGRID speichern, komprimieren Objekte möglicherweise vor dem Speichern.  Wenn eine Clientanwendung ein Objekt bereits komprimiert hat, bevor es in StorageGRID gespeichert wurde, wird die Größe eines Objekts durch Auswahl dieser Option nicht weiter reduziert.
* Wählen Sie *Gespeicherte Objekte komprimieren* nicht aus, wenn Sie NetApp FabricPool mit StorageGRID verwenden.
* Wenn *Gespeicherte Objekte komprimieren* ausgewählt ist, sollten S3-Clientanwendungen die Durchführung von GetObject-Operationen vermeiden, die einen zurückzugebenden Bytebereich angeben.  Diese „Range Read“-Operationen sind ineffizient, da StorageGRID die Objekte effektiv dekomprimieren muss, um auf die angeforderten Bytes zuzugreifen.  GetObject-Operationen, die einen kleinen Bytebereich aus einem sehr großen Objekt anfordern, sind besonders ineffizient. Beispielsweise ist es ineffizient, einen 10 MB großen Bereich aus einem komprimierten 50 GB-Objekt zu lesen.
+
Wenn Bereiche aus komprimierten Objekten gelesen werden, kann es bei Clientanforderungen zu einer Zeitüberschreitung kommen.

+

NOTE: Wenn Sie Objekte komprimieren müssen und Ihre Clientanwendung Bereichslesevorgänge verwenden muss, erhöhen Sie das Lesezeitlimit für die Anwendung.



.Schritte
. Wählen Sie *KONFIGURATION* > *System* > *Speichereinstellungen* > *Objektkomprimierung*.
. Aktivieren Sie das Kontrollkästchen *Gespeicherte Objekte komprimieren*.
. Wählen Sie *Speichern*.

