---
permalink: admin/controlling-access-through-firewalls.html 
sidebar: sidebar 
keywords: firewall access, firewall ports, external firewall 
summary: Sie können bestimmte Ports an der externen Firewall öffnen oder schließen. 
---
= Zugriffskontrolle an externer Firewall
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können bestimmte Ports an der externen Firewall öffnen oder schließen.

Sie können den Zugriff auf die Benutzeroberflächen und APIs auf StorageGRID Admin-Knoten steuern, indem Sie bestimmte Ports an der externen Firewall öffnen oder schließen.  Beispielsweise möchten Sie möglicherweise verhindern, dass Mandanten über die Firewall eine Verbindung zum Grid Manager herstellen können, und zusätzlich andere Methoden zur Kontrolle des Systemzugriffs verwenden.

Wenn Sie die interne Firewall von StorageGRID konfigurieren möchten, lesen Sielink:../admin/configure-firewall-controls.html["Konfigurieren der internen Firewall"] .

[cols="1a,1a,2a"]
|===
| Hafen | Beschreibung | Wenn der Port offen ist ... 


 a| 
443
 a| 
Standard-HTTPS-Port für Admin-Knoten
 a| 
Webbrowser und Management-API-Clients können auf den Grid Manager, die Grid Management API, den Tenant Manager und die Tenant Management API zugreifen.

*Hinweis:* Port 443 wird auch für einen Teil des internen Datenverkehrs verwendet.



 a| 
8443
 a| 
Eingeschränkter Grid Manager-Port auf Admin-Knoten
 a| 
* Webbrowser und Management-API-Clients können über HTTPS auf den Grid Manager und die Grid Management API zugreifen.
* Webbrowser und Management-API-Clients können nicht auf den Tenant Manager oder die Tenant Management API zugreifen.
* Anfragen nach internen Inhalten werden abgelehnt.




 a| 
9443
 a| 
Eingeschränkter Tenant Manager-Port auf Admin-Knoten
 a| 
* Webbrowser und Management-API-Clients können über HTTPS auf den Tenant Manager und die Tenant Management API zugreifen.
* Webbrowser und Management-API-Clients können nicht auf den Grid Manager oder die Grid Management API zugreifen.
* Anfragen nach internen Inhalten werden abgelehnt.


|===

TIP: Single Sign-On (SSO) ist auf den eingeschränkten Grid Manager- oder Tenant Manager-Ports nicht verfügbar.  Sie müssen den Standard-HTTPS-Port (443) verwenden, wenn Sie möchten, dass sich Benutzer per Single Sign-On authentifizieren.

.Ähnliche Informationen
* link:signing-in-to-grid-manager.html["Sign in"]
* link:creating-tenant-account.html["Mieterkonto erstellen"]
* link:../network/external-communications.html["Externe Kommunikation"]

