---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: Sie können die Grid Management API verwenden, um bestimmte Funktionen im StorageGRID -System vollständig zu deaktivieren.  Wenn eine Funktion deaktiviert ist, können niemandem Berechtigungen zum Ausführen der mit dieser Funktion verbundenen Aufgaben zugewiesen werden. 
---
= Funktionen mit der API deaktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Grid Management API verwenden, um bestimmte Funktionen im StorageGRID -System vollständig zu deaktivieren.  Wenn eine Funktion deaktiviert ist, können niemandem Berechtigungen zum Ausführen der mit dieser Funktion verbundenen Aufgaben zugewiesen werden.

.Informationen zu diesem Vorgang
Mit dem System „Deaktivierte Funktionen“ können Sie den Zugriff auf bestimmte Funktionen im StorageGRID -System verhindern.  Das Deaktivieren einer Funktion ist die einzige Möglichkeit, den Root-Benutzer oder Benutzer, die zu Administratorgruppen mit der Berechtigung *Root-Zugriff* gehören, daran zu hindern, diese Funktion zu verwenden.

Um zu verstehen, wie nützlich diese Funktionalität sein kann, betrachten Sie das folgende Szenario:

_Unternehmen A ist ein Dienstanbieter, der die Speicherkapazität seines StorageGRID -Systems durch die Erstellung von Mieterkonten mietet.  Um die Sicherheit der Objekte ihrer Mieter zu gewährleisten, möchte Unternehmen A sicherstellen, dass seine eigenen Mitarbeiter nach der Bereitstellung des Kontos niemals auf ein Mieterkonto zugreifen können._

_Unternehmen A kann dieses Ziel erreichen, indem es das System zum Deaktivieren von Funktionen in der Grid Management-API verwendet.  Durch die vollständige Deaktivierung der Funktion *Root-Passwort des Mandanten ändern* im Grid Manager (sowohl in der Benutzeroberfläche als auch in der API) stellt Unternehmen A sicher, dass Administratorbenutzer – einschließlich des Root-Benutzers und Benutzer, die zu Gruppen mit der Berechtigung *Root-Zugriff* gehören – das Passwort für den Root-Benutzer eines Mandantenkontos nicht ändern können._

.Schritte
. Greifen Sie auf die Swagger-Dokumentation für die Grid Management API zu. Sehen link:using-grid-management-api.html["Verwenden Sie die Grid Management API"] .
. Suchen Sie den Endpunkt „Funktionen deaktivieren“.
. Um eine Funktion zu deaktivieren, z. B. „Stammkennwort des Mandanten ändern“, senden Sie einen Text wie diesen an die API:
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
Wenn die Anfrage abgeschlossen ist, wird die Funktion „Stammkennwort des Mandanten ändern“ deaktiviert.  Die Verwaltungsberechtigung *Stammkennwort des Mandanten ändern* wird nicht mehr in der Benutzeroberfläche angezeigt und jede API-Anforderung, die versucht, das Stammkennwort für einen Mandanten zu ändern, schlägt mit „403 Forbidden“ fehl.





== Deaktivierte Funktionen reaktivieren

Standardmäßig können Sie die Grid Management API verwenden, um eine deaktivierte Funktion wieder zu aktivieren.  Wenn Sie jedoch verhindern möchten, dass deaktivierte Funktionen jemals wieder aktiviert werden, können Sie die Funktion *activateFeatures* selbst deaktivieren.


CAUTION: Die Funktion *activateFeatures* kann nicht erneut aktiviert werden.  Wenn Sie sich entscheiden, diese Funktion zu deaktivieren, beachten Sie, dass Sie dadurch dauerhaft die Möglichkeit verlieren, andere deaktivierte Funktionen wieder zu aktivieren.  Sie müssen sich an den technischen Support wenden, um verlorene Funktionen wiederherzustellen.

.Schritte
. Greifen Sie auf die Swagger-Dokumentation für die Grid Management API zu.
. Suchen Sie den Endpunkt „Funktionen deaktivieren“.
. Um alle Funktionen wieder zu aktivieren, senden Sie einen Text wie diesen an die API:
+
`{ "grid": null }`

+
Wenn diese Anforderung abgeschlossen ist, werden alle Funktionen, einschließlich der Funktion „Stammkennwort des Mandanten ändern“, wieder aktiviert.  Die Verwaltungsberechtigung *Root-Passwort des Mandanten ändern* wird jetzt in der Benutzeroberfläche angezeigt und jede API-Anforderung, die versucht, das Root-Passwort für einen Mandanten zu ändern, ist erfolgreich, vorausgesetzt, der Benutzer verfügt über die Verwaltungsberechtigung *Root-Zugriff* oder *Root-Passwort des Mandanten ändern*.




TIP: Das vorherige Beispiel bewirkt, dass _alle_ deaktivierten Funktionen wieder aktiviert werden.  Wenn andere Funktionen deaktiviert wurden und deaktiviert bleiben sollen, müssen Sie diese in der PUT-Anforderung explizit angeben.  Um beispielsweise die Funktion „Stammkennwort des Mandanten ändern“ erneut zu aktivieren und die Verwaltungsberechtigung „storageAdmin“ weiterhin zu deaktivieren, senden Sie diese PUT-Anfrage: +
`{ "grid": {"storageAdmin": true} }`
