---
permalink: admin/disabling-single-sign-on.html 
sidebar: sidebar 
keywords: disable sso, disable single sign on 
summary: 'Sie können Single Sign-On (SSO) deaktivieren, wenn Sie diese Funktion nicht mehr verwenden möchten.  Sie müssen die einmalige Anmeldung deaktivieren, bevor Sie die Identitätsföderation deaktivieren können.' 
---
= Deaktivieren der einmaligen Anmeldung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Single Sign-On (SSO) deaktivieren, wenn Sie diese Funktion nicht mehr verwenden möchten.  Sie müssen die einmalige Anmeldung deaktivieren, bevor Sie die Identitätsföderation deaktivieren können.

.Bevor Sie beginnen
* Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Du hastlink:admin-group-permissions.html["spezifische Zugriffsberechtigungen"] .


.Schritte
. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Einmaliges Anmelden*.
+
Die Single Sign-On-Seite wird angezeigt.

. Wählen Sie die Option *Deaktiviert*.
. Wählen Sie *Speichern*.
+
Es wird eine Warnmeldung angezeigt, die darauf hinweist, dass sich lokale Benutzer jetzt anmelden können.

. Wählen Sie *OK*.
+
Wenn Sie sich das nächste Mal bei StorageGRID anmelden, wird die StorageGRID Sign in angezeigt und Sie müssen den Benutzernamen und das Kennwort für einen lokalen oder föderierten StorageGRID Benutzer eingeben.


