---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: 'Sie können Hochverfügbarkeitsgruppen (HA) verwenden, um hochverfügbare Verbindungen zu StorageGRID für Objektdaten und zur administrativen Verwendung bereitzustellen.' 
---
= Wie werden HA-Gruppen verwendet?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Hochverfügbarkeitsgruppen (HA) verwenden, um hochverfügbare Verbindungen zu StorageGRID für Objektdaten und zur administrativen Verwendung bereitzustellen.

* Eine HA-Gruppe kann hochverfügbare administrative Verbindungen zum Grid Manager oder Tenant Manager bereitstellen.
* Eine HA-Gruppe kann hochverfügbare Datenverbindungen für S3-Clients bereitstellen.
* Eine HA-Gruppe, die nur eine Schnittstelle enthält, ermöglicht Ihnen die Bereitstellung vieler VIP-Adressen und die explizite Festlegung von IPv6-Adressen.


Eine HA-Gruppe kann nur dann eine hohe Verfügbarkeit bieten, wenn alle in der Gruppe enthaltenen Knoten dieselben Dienste bereitstellen.  Wenn Sie eine HA-Gruppe erstellen, fügen Sie Schnittstellen von den Knotentypen hinzu, die die von Ihnen benötigten Dienste bereitstellen.

* *Admin-Knoten*: Schließen Sie den Load Balancer-Dienst ein und ermöglichen Sie den Zugriff auf den Grid Manager oder den Tenant Manager.
* *Gateway-Knoten*: Schließen Sie den Load Balancer-Dienst ein.


[cols="1a,2a"]
|===
| Zweck der HA-Gruppe | Knoten dieses Typs zur HA-Gruppe hinzufügen 


 a| 
Zugriff auf Grid Manager
 a| 
* Primärer Admin-Knoten (*Primär*)
* Nicht-primäre Admin-Knoten


*Hinweis:* Der primäre Admin-Knoten muss die primäre Schnittstelle sein.  Einige Wartungsvorgänge können nur vom primären Admin-Knoten aus durchgeführt werden.



 a| 
Zugriff nur auf den Mandantenmanager
 a| 
* Primäre oder nicht-primäre Admin-Knoten




 a| 
S3-Clientzugriff – Load Balancer-Dienst
 a| 
* Admin-Knoten
* Gateway-Knoten




 a| 
S3-Client-Zugriff fürlink:../admin/manage-s3-select-for-tenant-accounts.html["S3 Auswählen"]
 a| 
* Servicegeräte
* VMware-basierte Softwareknoten


*Hinweis*: HA-Gruppen werden bei der Verwendung von S3 Select empfohlen, sind aber nicht erforderlich.

|===


== Einschränkungen bei der Verwendung von HA-Gruppen mit Grid Manager oder Tenant Manager

Wenn ein Grid Manager- oder Tenant Manager-Dienst ausfällt, wird kein HA-Gruppen-Failover ausgelöst.

Wenn Sie beim Failover beim Grid Manager oder Tenant Manager angemeldet sind, werden Sie abgemeldet und müssen sich erneut anmelden, um Ihre Aufgabe fortzusetzen.

Einige Wartungsverfahren können nicht durchgeführt werden, wenn der primäre Admin-Knoten nicht verfügbar ist.  Während des Failovers können Sie den Grid Manager verwenden, um Ihr StorageGRID System zu überwachen.
