---
permalink: admin/index.html 
sidebar: sidebar 
keywords: how to administer storagegrid 
summary: Verwenden Sie diese Anweisungen, um ein StorageGRID -System zu konfigurieren und zu verwalten. 
---
= StorageGRID verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie diese Anweisungen, um ein StorageGRID -System zu konfigurieren und zu verwalten.



== Zu dieser Anleitung

Die wichtigsten Aufgaben zur Konfiguration und Verwaltung von StorageGRID ermöglichen Ihnen:

* Verwenden Sie den Grid Manager, um Gruppen und Benutzer einzurichten
* Erstellen Sie Mandantenkonten, um S3-Clientanwendungen das Speichern und Abrufen von Objekten zu ermöglichen
* Konfigurieren und Verwalten von StorageGRID -Netzwerken
* Konfigurieren Sie AutoSupport
* Knoteneinstellungen verwalten




== Bevor Sie beginnen

* Sie verfügen über ein allgemeines Verständnis des StorageGRID -Systems.
* Sie verfügen über ziemlich detaillierte Kenntnisse zu Linux-Befehlsshells, Netzwerken sowie der Einrichtung und Konfiguration von Serverhardware.

