---
permalink: admin/networking-and-ports-for-platform-services.html 
sidebar: sidebar 
keywords: platform services, ports for platform services, 443, 80 
summary: Wenn Sie einem S3-Mandanten die Verwendung von Plattformdiensten gestatten, müssen Sie die Vernetzung für das Grid konfigurieren, um sicherzustellen, dass Nachrichten der Plattformdienste an ihre Ziele übermittelt werden können. 
---
= Netzwerk und Ports für Plattformdienste
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einem S3-Mandanten die Verwendung von Plattformdiensten gestatten, müssen Sie die Vernetzung für das Grid konfigurieren, um sicherzustellen, dass Nachrichten der Plattformdienste an ihre Ziele übermittelt werden können.

Sie können Plattformdienste für ein S3-Mandantenkonto aktivieren, wenn Sie das Mandantenkonto erstellen oder aktualisieren.  Wenn Plattformdienste aktiviert sind, kann der Mandant Endpunkte erstellen, die als Ziel für CloudMirror-Replikation, Ereignisbenachrichtigungen oder Suchintegrationsnachrichten aus seinen S3-Buckets dienen.  Diese Plattformdienstnachrichten werden von Speicherknoten, die den ADC-Dienst ausführen, an die Zielendpunkte gesendet.

Beispielsweise können Mandanten die folgenden Arten von Zielendpunkten konfigurieren:

* Ein lokal gehosteter Elasticsearch-Cluster
* Eine lokale Anwendung, die den Empfang von Amazon Simple Notification Service-Nachrichten unterstützt
* Ein lokal gehosteter Kafka-Cluster
* Ein lokal gehosteter S3-Bucket auf derselben oder einer anderen Instanz von StorageGRID
* Ein externer Endpunkt, z. B. ein Endpunkt auf Amazon Web Services.


Um sicherzustellen, dass Nachrichten der Plattformdienste zugestellt werden können, müssen Sie das Netzwerk oder die Netzwerke konfigurieren, die die ADC-Speicherknoten enthalten.  Sie müssen sicherstellen, dass die folgenden Ports zum Senden von Plattformdienstnachrichten an die Zielendpunkte verwendet werden können.

Standardmäßig werden Nachrichten der Plattformdienste über die folgenden Ports gesendet:

* *80*: Für Endpunkt-URIs, die mit http beginnen (die meisten Endpunkte)
* *443*: Für Endpunkt-URIs, die mit https beginnen (die meisten Endpunkte)
* *9092*: Für Endpunkt-URIs, die mit http oder https beginnen (nur Kafka-Endpunkte)


Mandanten können beim Erstellen oder Bearbeiten eines Endpunkts einen anderen Port angeben.


NOTE: Wenn eine StorageGRID Bereitstellung als Ziel für die CloudMirror-Replikation verwendet wird, werden Replikationsnachrichten möglicherweise auf einem anderen Port als 80 oder 443 empfangen.  Stellen Sie sicher, dass der von der StorageGRID Zielbereitstellung für S3 verwendete Port im Endpunkt angegeben ist.

Wenn Sie einen nicht-transparenten Proxy-Server verwenden, müssen Sie außerdemlink:configuring-storage-proxy-settings.html["Konfigurieren der Speicherproxyeinstellungen"] um das Senden von Nachrichten an externe Endpunkte zu ermöglichen, beispielsweise an einen Endpunkt im Internet.

.Ähnliche Informationen
link:../tenant/index.html["Verwenden eines Mandantenkontos"]
