---
permalink: s3/deprecated-put-bucket-request-modifications-for-compliance.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated bucket requests for compliance 
summary: Das XML-Element SGCompliance ist veraltet.  Bisher konnten Sie dieses benutzerdefinierte StorageGRID Element in den optionalen XML-Anforderungstext von CreateBucket-Anforderungen aufnehmen, um einen konformen Bucket zu erstellen. 
---
= Veraltet: CreateBucket-Anforderungsänderungen zur Einhaltung der Vorschriften
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das XML-Element SGCompliance ist veraltet.  Bisher konnten Sie dieses benutzerdefinierte StorageGRID Element in den optionalen XML-Anforderungstext von CreateBucket-Anforderungen aufnehmen, um einen konformen Bucket zu erstellen.

[NOTE]
====
Die StorageGRID Compliance-Funktion, die in früheren StorageGRID Versionen verfügbar war, ist veraltet und wurde durch S3 Object Lock ersetzt.  Weitere Einzelheiten finden Sie im Folgenden:

* link:../s3/use-s3-api-for-s3-object-lock.html["Verwenden Sie die S3 REST API, um S3 Object Lock zu konfigurieren"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp Knowledge Base: So verwalten Sie ältere konforme Buckets in StorageGRID 11.5"^]


====
Sie können keine neuen Buckets mehr erstellen, wenn Compliance aktiviert ist.  Die folgende Fehlermeldung wird zurückgegeben, wenn Sie versuchen, mithilfe der CreateBucket-Anforderungsänderungen für die Konformität einen neuen konformen Bucket zu erstellen:

[listing]
----
The Compliance feature is deprecated.
Contact your StorageGRID administrator if you need to create new Compliant buckets.
----