---
permalink: s3/get-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket consistency 
summary: Mit der Anforderung „GET Bucket Consistency“ können Sie die Konsistenz ermitteln, die auf einen bestimmten Bucket angewendet wird. 
---
= GET Bucket-Konsistenz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Anforderung „GET Bucket Consistency“ können Sie die Konsistenz ermitteln, die auf einen bestimmten Bucket angewendet wird.

Die Standardkonsistenz ist so eingestellt, dass für neu erstellte Objekte das Lesen nach dem Schreiben gewährleistet ist.

Sie müssen über die Berechtigung s3:GetBucketConsistency verfügen oder Root-Kontoinhaber sein, um diesen Vorgang abzuschließen.



== Anforderungsbeispiel

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Antwort

In der Antwort-XML `<Consistency>` gibt einen der folgenden Werte zurück:

[cols="1a,2a"]
|===
| Konsistenz | Beschreibung 


 a| 
alle
 a| 
Alle Knoten empfangen die Daten sofort, andernfalls schlägt die Anforderung fehl.



 a| 
stark-global
 a| 
Garantiert Lese- und Schreibkonsistenz für alle Clientanforderungen auf allen Sites.



 a| 
starke Site
 a| 
Garantiert die Lese- und Schreibkonsistenz für alle Clientanforderungen innerhalb einer Site.



 a| 
Lesen nach neuem Schreiben
 a| 
(Standard) Bietet Read-After-Write-Konsistenz für neue Objekte und letztendliche Konsistenz für Objektaktualisierungen.  Bietet hohe Verfügbarkeit und Datenschutzgarantien.  Für die meisten Fälle empfohlen.



 a| 
verfügbar
 a| 
Bietet letztendliche Konsistenz sowohl für neue Objekte als auch für Objektaktualisierungen.  Verwenden Sie es für S3-Buckets nur nach Bedarf (z. B. für einen Bucket, der Protokollwerte enthält, die selten gelesen werden, oder für HEAD- oder GET-Operationen für nicht vorhandene Schlüssel).  Wird für S3 FabricPool Buckets nicht unterstützt.

|===


== Antwortbeispiel

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.Ähnliche Informationen
link:consistency-controls.html["Konsistenzwerte"]
