---
permalink: s3/operations-on-the-service.html 
sidebar: sidebar 
keywords: listbuckets, get service, operations on the service 
summary: Das StorageGRID -System unterstützt Vorgänge auf dem Dienst. 
---
= Vorgänge für den Dienst
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das StorageGRID -System unterstützt die folgenden Vorgänge für den Dienst.

[cols="1a,2a"]
|===
| Betrieb | Durchführung 


 a| 
Buckets auflisten

(früher GET-Dienst genannt)
 a| 
Implementiert mit dem gesamten Amazon S3 REST API-Verhalten.  Änderungen vorbehalten.



 a| 
GET-Speichernutzung
 a| 
Das StorageGRIDlink:get-storage-usage-request.html["GET-Speichernutzung"] Die Anfrage gibt Auskunft über die Gesamtmenge des von einem Konto und jedem mit dem Konto verknüpften Bucket verwendeten Speichers.  Dies ist eine Operation für den Dienst mit einem Pfad von / und einem benutzerdefinierten Abfrageparameter(`?x-ntap-sg-usage` ) hinzugefügt.



 a| 
OPTIONEN /
 a| 
Clientanwendungen können `OPTIONS /` Anfragen an den S3-Port eines Speicherknotens, ohne S3-Authentifizierungsdaten anzugeben, um festzustellen, ob der Speicherknoten verfügbar ist.  Sie können diese Anfrage zur Überwachung verwenden oder um externen Lastenausgleichsmodulen zu ermöglichen, zu erkennen, wenn ein Speicherknoten ausgefallen ist.

|===