---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, RestoreObject, object 
summary: Sie können die S3 RestoreObject-Anforderung verwenden, um ein Objekt wiederherzustellen, das in einem Cloud-Speicherpool gespeichert ist. 
---
= RestoreObject
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die S3 RestoreObject-Anforderung verwenden, um ein Objekt wiederherzustellen, das in einem Cloud-Speicherpool gespeichert ist.



== Unterstützter Anfragetyp

StorageGRID unterstützt nur RestoreObject-Anfragen zum Wiederherstellen eines Objekts.  Es unterstützt nicht die `SELECT` Art der Restaurierung.  Wählen Sie Anfragen zurück `XNotImplemented` .



== Versionierung

Geben Sie optional an `versionId` um eine bestimmte Version eines Objekts in einem versionierten Bucket wiederherzustellen.  Wenn Sie nicht angeben `versionId` wird die aktuellste Version des Objekts wiederhergestellt



== Verhalten von RestoreObject bei Cloud Storage Pool-Objekten

Wenn ein Objekt in einemlink:../ilm/what-cloud-storage-pool-is.html["Cloud-Speicherpool"] , eine RestoreObject-Anforderung weist basierend auf dem Status des Objekts das folgende Verhalten auf. Sehenlink:head-object.html["HeadObject"] für weitere Details.


NOTE: Wenn ein Objekt in einem Cloud-Speicherpool gespeichert ist und eine oder mehrere Kopien des Objekts auch im Grid vorhanden sind, ist es nicht erforderlich, das Objekt durch Ausgeben einer RestoreObject-Anforderung wiederherzustellen.  Stattdessen kann die lokale Kopie direkt mithilfe einer GetObject-Anforderung abgerufen werden.

[cols="1a,2a"]
|===
| Zustand des Objekts | Verhalten von RestoreObject 


 a| 
Objekt in StorageGRID aufgenommen, aber noch nicht von ILM ausgewertet, oder Objekt befindet sich nicht in einem Cloud-Speicherpool
 a| 
`403 Forbidden` ,  `InvalidObjectState`



 a| 
Objekt im Cloud-Speicherpool, aber noch nicht in einen nicht abrufbaren Zustand übergegangen
 a| 
`200 OK`Es werden keine Änderungen vorgenommen.

*Hinweis*: Bevor ein Objekt in einen nicht abrufbaren Zustand überführt wurde, können Sie seine `expiry-date` .



 a| 
Objekt in einen nicht abrufbaren Zustand überführt
 a| 
`202 Accepted`Stellt eine abrufbare Kopie des Objekts für die im Anforderungstext angegebene Anzahl von Tagen im Cloud-Speicherpool wieder her.  Am Ende dieses Zeitraums wird das Objekt in einen nicht abrufbaren Zustand zurückversetzt.

Optional können Sie die `Tier` Anforderungselement, um zu bestimmen, wie lange es dauert, bis der Wiederherstellungsjob abgeschlossen ist(`Expedited` , `Standard` , oder `Bulk` ).  Wenn Sie nicht angeben `Tier` , Die `Standard` Ebene verwendet wird.

*Wichtig*: Wenn ein Objekt in das S3 Glacier Deep Archive verschoben wurde oder der Cloud Storage Pool Azure Blob Storage verwendet, können Sie es nicht mit dem `Expedited` Stufe.  Der folgende Fehler wird zurückgegeben `403 Forbidden` , `InvalidTier` : `Retrieval option is not supported by this storage class` .



 a| 
Objekt wird gerade aus einem nicht abrufbaren Zustand wiederhergestellt
 a| 
`409 Conflict` ,  `RestoreAlreadyInProgress`



 a| 
Objekt vollständig im Cloud-Speicherpool wiederhergestellt
 a| 
`200 OK`

*Hinweis:* Wenn ein Objekt in einen abrufbaren Zustand zurückversetzt wurde, können Sie seine `expiry-date` durch erneutes Ausgeben der RestoreObject-Anforderung mit einem neuen Wert für `Days` .  Das Wiederherstellungsdatum wird relativ zum Zeitpunkt der Anfrage aktualisiert.

|===