---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: Der Vorgang „UploadPart“ lädt einen Teil in einem mehrteiligen Upload für ein Objekt hoch. 
---
= UploadPart
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Vorgang „UploadPart“ lädt einen Teil in einem mehrteiligen Upload für ein Objekt hoch.



== Unterstützte Anforderungsheader

Die folgenden Anforderungsheader werden unterstützt:

* `x-amz-checksum-sha256`
* `Content-Length`
* `Content-MD5`




== Anforderungsheader für serverseitige Verschlüsselung

Wenn Sie für die CreateMultipartUpload-Anforderung die SSE-C-Verschlüsselung angegeben haben, müssen Sie in jede UploadPart-Anforderung auch die folgenden Anforderungsheader einfügen:

* `x-amz-server-side-encryption-customer-algorithm`: Angeben `AES256` .
* `x-amz-server-side-encryption-customer-key`: Geben Sie denselben Verschlüsselungsschlüssel an, den Sie in der CreateMultipartUpload-Anforderung angegeben haben.
* `x-amz-server-side-encryption-customer-key-MD5`: Geben Sie denselben MD5-Digest an, den Sie in der CreateMultipartUpload-Anforderung angegeben haben.



CAUTION: Die von Ihnen bereitgestellten Verschlüsselungsschlüssel werden niemals gespeichert.  Wenn Sie einen Verschlüsselungsschlüssel verlieren, verlieren Sie das entsprechende Objekt.  Bevor Sie vom Kunden bereitgestellte Schlüssel zum Sichern von Objektdaten verwenden, lesen Sie die Hinweise inlink:using-server-side-encryption.html["Verwenden Sie serverseitige Verschlüsselung"] .

Wenn Sie während der CreateMultipartUpload-Anforderung eine SHA-256-Prüfsumme angegeben haben, müssen Sie in jede UploadPart-Anforderung auch den folgenden Anforderungsheader einfügen:

* `x-amz-checksum-sha256`: Geben Sie die SHA-256-Prüfsumme für diesen Teil an.




== Nicht unterstützte Anforderungsheader

Die folgenden Anforderungsheader werden nicht unterstützt:

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== Versionierung

Der mehrteilige Upload besteht aus separaten Vorgängen zum Starten des Uploads, Auflisten der Uploads, Hochladen von Teilen, Zusammenstellen der hochgeladenen Teile und Abschließen des Uploads.  Objekte werden erstellt (und gegebenenfalls versioniert), wenn der Vorgang CompleteMultipartUpload ausgeführt wird.
