---
permalink: s3/use-s3-select.html 
sidebar: sidebar 
keywords: use S3 Select, S3 Select 
summary: StorageGRID unterstützt die folgenden Amazon S3 Select-Klauseln, Datentypen, Operatoren und reservierten Schlüsselwörter für den Befehl „SelectObjectContent“. 
---
= Verwenden Sie S3 Select
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID unterstützt die folgenden Amazon S3 Select-Klauseln, Datentypen und Operatoren für dielink:select-object-content.html["SelectObjectContent-Befehl"] .


NOTE: Nicht aufgeführte Artikel werden nicht unterstützt.

Informationen zur Syntax finden Sie unterlink:select-object-content.html["SelectObjectContent"] .  Weitere Informationen zu S3 Select finden Sie im https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html["AWS-Dokumentation für S3 Select"^] .

Nur Mandantenkonten, bei denen S3 Select aktiviert ist, können SelectObjectContent-Abfragen ausgeben. Siehe dielink:../admin/manage-s3-select-for-tenant-accounts.html["Überlegungen und Anforderungen zur Verwendung von S3 Select"] .



== Klauseln

* SELECT-Liste
* FROM-Klausel
* WHERE-Klausel
* LIMIT-Klausel




== Datentypen

* bool
* ganze Zahl
* Schnur
* schweben
* Dezimal, numerisch
* Zeitstempel




== Betreiber



=== Logische Operatoren

* UND
* NICHT
* ODER




=== Vergleichsoperatoren

* <
* >
* <=
* >=
* =
* =
* <>
* !=
* ZWISCHEN
* IN




=== Mustervergleichsoperatoren

* WIE
* _
* %




=== Unitäre Operatoren

* IST NULL
* IST NICHT NULL




=== Mathematische Operatoren

* +
* -
* *
* /
* %


StorageGRID folgt der Priorität des Amazon S3 Select-Operators.



== Aggregatfunktionen

* AVG()
* ZÄHLEN(*)
* MAX()
* MIN()
* SUMME()




== Bedingte Funktionen

* FALL
* VERSCHMELZEN
* NULLIF




== Konvertierungsfunktionen

* CAST (für unterstützten Datentyp)




== Datumsfunktionen

* DATE_ADD
* DATE_DIFF
* EXTRAKT
* TO_STRING
* TO_TIMESTAMP
* UTCNOW




== Zeichenfolgenfunktionen

* CHAR_LENGTH, CHARACTER_LENGTH
* UNTERE
* TEILZEICHENKETTE
* TRIMMEN
* OBERE

