---
permalink: monitor/about-bycast-log.html 
sidebar: sidebar 
keywords: bycast, log 
summary: 'Die Datei /var/local/log/bycast.log ist die primäre Fehlerbehebungsdatei für die StorageGRID -Software.  Es gibt eine `bycast.log` Datei für jeden Rasterknoten.  Die Datei enthält Nachrichten, die für diesen Grid-Knoten spezifisch sind.' 
---
= Über das bycast.log
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Datei `/var/local/log/bycast.log` ist die primäre Fehlerbehebungsdatei für die StorageGRID -Software.  Es gibt eine `bycast.log` Datei für jeden Rasterknoten.  Die Datei enthält Nachrichten, die für diesen Grid-Knoten spezifisch sind.

Die Datei `/var/local/log/bycast-err.log` ist eine Teilmenge von `bycast.log` .  Es enthält Meldungen mit den Schweregraden FEHLER und KRITISCH.

Optional können Sie das Ziel der Überwachungsprotokolle ändern und Überwachungsinformationen an einen externen Syslog-Server senden. Wenn ein externer Syslog-Server konfiguriert ist, werden weiterhin lokale Protokolle von Prüfdatensätzen generiert und gespeichert. Sehen link:../monitor/configure-audit-messages.html["Konfigurieren von Überwachungsmeldungen und Protokollzielen"] .



== Dateirotation für bycast.log

Wenn die `bycast.log` Wenn die Datei 1 GB erreicht, wird die vorhandene Datei gespeichert und eine neue Protokolldatei gestartet.

Die gespeicherte Datei wird umbenannt `bycast.log.1` und die neue Datei heißt `bycast.log` .  Wenn das neue `bycast.log` erreicht 1 GB, `bycast.log.1` wird umbenannt und komprimiert und wird `bycast.log.2.gz` , Und `bycast.log` wird umbenannt `bycast.log.1` .

Die Rotationsgrenze für `bycast.log` sind 21 Dateien.  Als die 22. Version des `bycast.log` Datei erstellt wird, wird die älteste Datei gelöscht.

Die Rotationsgrenze für `bycast-err.log` sind sieben Dateien.


NOTE: Wenn eine Protokolldatei komprimiert wurde, dürfen Sie sie nicht an denselben Speicherort dekomprimieren, an dem sie geschrieben wurde.  Das Dekomprimieren der Datei an denselben Speicherort kann die Protokollrotationsskripte beeinträchtigen.

Optional können Sie das Ziel der Überwachungsprotokolle ändern und Überwachungsinformationen an einen externen Syslog-Server senden. Wenn ein externer Syslog-Server konfiguriert ist, werden weiterhin lokale Protokolle von Prüfdatensätzen generiert und gespeichert. Sehen link:../monitor/configure-audit-messages.html["Konfigurieren von Überwachungsmeldungen und Protokollzielen"] .

.Ähnliche Informationen
link:collecting-log-files-and-system-data.html["Erfassen von Protokolldateien und Systemdaten"]



== Nachrichten im bycast.log

Nachrichten in `bycast.log` werden von der ADE (Asynchronous Distributed Environment) geschrieben.  ADE ist die Laufzeitumgebung, die von den Diensten jedes Grid-Knotens verwendet wird.

Beispiel einer ADE-Nachricht:

[listing]
----
May 15 14:07:11 um-sec-rg1-agn3 ADE: |12455685    0357819531
SVMR EVHR 2019-05-05T27T17:10:29.784677| ERROR 0906 SVMR: Health
check on volume 3 has failed with reason 'TOUT'
----
ADE-Nachrichten enthalten die folgenden Informationen:

[cols="1a,2a"]
|===
| Nachrichtensegment | Wert im Beispiel 


 a| 
Knoten-ID
| 12455685 


 a| 
ADE-Prozess-ID
| 0357819531 


 a| 
Modulname
| SVMR 


 a| 
Nachrichtenkennung
| EVHR 


 a| 
UTC-Systemzeit
| 2019-05-05T27T17:10:29.784677 (JJJJ-MM-TTTHH:MM:SS.uuuuuu) 


 a| 
Schweregrad
| FEHLER 


 a| 
Interne Trackingnummer
| 0906 


 a| 
Nachricht
| SVMR: Integritätsprüfung auf Datenträger 3 ist mit der Begründung „TOUT“ fehlgeschlagen 
|===


== Schweregrade der Nachrichten in bycast.log

Die Nachrichten in `bycast.log` werden Schweregrade zugewiesen.

Beispiel:

* *HINWEIS* – Ein Ereignis ist eingetreten, das aufgezeichnet werden sollte.  Die meisten Protokollnachrichten befinden sich auf dieser Ebene.
* *WARNUNG* – Es ist ein unerwarteter Zustand aufgetreten.
* *FEHLER* – Es ist ein schwerwiegender Fehler aufgetreten, der den Betrieb beeinträchtigen wird.
* *KRITISCH* – Es ist ein anormaler Zustand aufgetreten, der den normalen Betrieb gestoppt hat.  Sie sollten sich sofort um die zugrunde liegende Erkrankung kümmern.




== Fehlercodes in `bycast.log`

Die meisten Fehlermeldungen in `bycast.log` enthalten Fehlercodes.

Die folgende Tabelle listet häufige nicht-numerische Codes in `bycast.log` Die genaue Bedeutung eines nicht numerischen Codes hängt vom Kontext ab, in dem er gemeldet wird.

[cols="1a,1a"]
|===
| Fehlercode | Bedeutung 


 a| 
SUCS
 a| 
Kein Fehler



 a| 
GERR
 a| 
Unbekannt



 a| 
CANC
 a| 
Abgesagt



 a| 
ABRT
 a| 
Abgebrochen



 a| 
TOUT
 a| 
Time-out



 a| 
INVL
 a| 
Ungültig



 a| 
NFND
 a| 
Nicht gefunden



 a| 
VERS
 a| 
Version



 a| 
KONF
 a| 
Konfiguration



 a| 
SCHEITERN
 a| 
Fehlgeschlagen



 a| 
ICPL
 a| 
Unvollständig



 a| 
ERLEDIGT
 a| 
Erledigt



 a| 
SUNV
 a| 
Dienst nicht verfügbar

|===
Die folgende Tabelle listet die numerischen Fehlercodes in `bycast.log` .

[cols="1a,2a,3a"]
|===
| Fehlernummer | Fehlercode | Bedeutung 


 a| 
001
 a| 
EPERM
 a| 
Betrieb nicht zulässig



 a| 
002
 a| 
ENOENT
 a| 
Keine solche Datei oder Verzeichnis



 a| 
003
 a| 
ESRCH
 a| 
Kein solcher Prozess



 a| 
004
 a| 
EINTR
 a| 
Unterbrochener Systemaufruf



 a| 
005
 a| 
EIO
 a| 
E/A-Fehler



 a| 
006
 a| 
ENXIO
 a| 
Kein solches Gerät oder keine solche Adresse



 a| 
007
 a| 
E2BIG
 a| 
Argumentliste zu lang



 a| 
008
 a| 
ENOEXEC
 a| 
Exec-Formatfehler



 a| 
009
 a| 
EBADF
 a| 
Ungültige Dateinummer



 a| 
010
 a| 
ECHILD
 a| 
Keine untergeordneten Prozesse



 a| 
011
 a| 
WIEDER
 a| 
Versuchen Sie es erneut



 a| 
012
 a| 
ENOMEM
 a| 
Nicht genügend Arbeitsspeicher



 a| 
013
 a| 
EACCES
 a| 
Zugriff verweigert



 a| 
014
 a| 
EFAULT
 a| 
Falsche Adresse



 a| 
015
 a| 
ENOTBLK
 a| 
Blockgerät erforderlich



 a| 
016
 a| 
EBUSY
 a| 
Gerät oder Ressource beschäftigt



 a| 
017
 a| 
EEXIST
 a| 
Datei existiert



 a| 
018
 a| 
EXDEV
 a| 
Geräteübergreifende Verknüpfung



 a| 
019
 a| 
ENODEV
 a| 
Kein solches Gerät



 a| 
020
 a| 
ENOTDIR
 a| 
Kein Verzeichnis



 a| 
021
 a| 
EISDIR
 a| 
Ist ein Verzeichnis



 a| 
022
 a| 
EINVAL
 a| 
Ungültiges Argument



 a| 
023
 a| 
ENFILE
 a| 
Dateitabellenüberlauf



 a| 
024
 a| 
EMFILE
 a| 
Zu viele geöffnete Dateien



 a| 
025
 a| 
ENOTTY
 a| 
Keine Schreibmaschine



 a| 
026
 a| 
ETXTBSY
 a| 
Textdatei belegt



 a| 
027
 a| 
EFBIG
 a| 
Datei zu groß



 a| 
028
 a| 
ENOSPC
 a| 
Kein Speicherplatz mehr auf dem Gerät



 a| 
029
 a| 
ESPEIPE
 a| 
Unerlaubte Suche



 a| 
030
 a| 
EROFS
 a| 
Schreibgeschütztes Dateisystem



 a| 
031
 a| 
EMLINK
 a| 
Zu viele Links



 a| 
032
 a| 
EPIPE
 a| 
Rohrbruch



 a| 
033
 a| 
EDOM
 a| 
Mathematisches Argument außerhalb des Funktionsumfangs



 a| 
034
 a| 
ERANGE
 a| 
Matheergebnis nicht darstellbar



 a| 
035
 a| 
EDEADLK
 a| 
Es kommt zu einem Ressourcen-Deadlock



 a| 
036
 a| 
ENAMETOOLONG
 a| 
Dateiname zu lang



 a| 
037
 a| 
ENOLCK
 a| 
Keine Datensatzsperren verfügbar



 a| 
038
 a| 
ENOSYS
 a| 
Funktion nicht implementiert



 a| 
039
 a| 
VERFÜHRUNG
 a| 
Verzeichnis nicht leer



 a| 
040
 a| 
ELOOP
 a| 
Zu viele symbolische Links gefunden



 a| 
041
 a| 
 a| 



 a| 
042
 a| 
ENOMSG
 a| 
Keine Nachricht des gewünschten Typs



 a| 
043
 a| 
EIDRM
 a| 
Kennung entfernt



 a| 
044
 a| 
EMHRNG
 a| 
Kanalnummer außerhalb des gültigen Bereichs



 a| 
045
 a| 
EL2NSYNC
 a| 
Ebene 2 nicht synchronisiert



 a| 
046
 a| 
EL3HLT
 a| 
Level 3 gestoppt



 a| 
047
 a| 
EL3RST
 a| 
Level 3 zurücksetzen



 a| 
048
 a| 
ELNRNG
 a| 
Linknummer außerhalb des gültigen Bereichs



 a| 
049
 a| 
EUNATCH
 a| 
Protokolltreiber nicht angeschlossen



 a| 
050
 a| 
ENOCSI
 a| 
Keine CSI-Struktur verfügbar



 a| 
051
 a| 
EL2HLT
 a| 
Level 2 gestoppt



 a| 
052
 a| 
EBADE
 a| 
Ungültiger Umtausch



 a| 
053
 a| 
EBADR
 a| 
Ungültiger Anforderungsdeskriptor



 a| 
054
 a| 
EXFULL
 a| 
Austausch voll



 a| 
055
 a| 
ENOANO
 a| 
Keine Anode



 a| 
056
 a| 
EBADRQC
 a| 
Ungültiger Anforderungscode



 a| 
057
 a| 
EBADSLT
 a| 
Ungültiger Steckplatz



 a| 
058
 a| 
 a| 



 a| 
059
 a| 
EBFONT
 a| 
Ungültiges Schriftartdateiformat



 a| 
060
 a| 
ENOSTR
 a| 
Gerät ist kein Stream



 a| 
061
 a| 
ENODATA
 a| 
Keine Daten verfügbar



 a| 
062
 a| 
ETIME
 a| 
Timer abgelaufen



 a| 
063
 a| 
ENOSR
 a| 
Keine Stream-Ressourcen mehr vorhanden



 a| 
064
 a| 
ENONET
 a| 
Maschine ist nicht im Netzwerk



 a| 
065
 a| 
ENOPKG
 a| 
Paket nicht installiert



 a| 
066
 a| 
EREMOTE
 a| 
Objekt ist remote



 a| 
067
 a| 
ENOLINK
 a| 
Die Verbindung wurde getrennt



 a| 
068
 a| 
EADV
 a| 
Fehler melden



 a| 
069
 a| 
ESRMNT
 a| 
Srmount-Fehler



 a| 
070
 a| 
ECOMM
 a| 
Kommunikationsfehler beim Senden



 a| 
071
 a| 
EPROTO
 a| 
Protokollfehler



 a| 
072
 a| 
EMULTIHOP
 a| 
Multihop versucht



 a| 
073
 a| 
EDOTDOT
 a| 
RFS-spezifischer Fehler



 a| 
074
 a| 
EBADMSG
 a| 
Keine Datennachricht



 a| 
075
 a| 
ÜBERLAUF
 a| 
Wert zu groß für definierten Datentyp



 a| 
076
 a| 
ENOTUNIQ
 a| 
Name im Netzwerk nicht eindeutig



 a| 
077
 a| 
EBADFD
 a| 
Dateideskriptor in fehlerhaftem Zustand



 a| 
078
 a| 
EREMCHG
 a| 
Remote-Adresse geändert



 a| 
079
 a| 
ELIBACC
 a| 
Auf eine benötigte gemeinsam genutzte Bibliothek kann nicht zugegriffen werden



 a| 
080
 a| 
ELIBBAD
 a| 
Zugriff auf eine beschädigte gemeinsam genutzte Bibliothek



 a| 
081
 a| 
ELIBSCN
 a| 



 a| 
082
 a| 
ELIBMAX
 a| 
Versuch, zu viele gemeinsam genutzte Bibliotheken einzubinden



 a| 
083
 a| 
ELIBEXEC
 a| 
Eine gemeinsam genutzte Bibliothek kann nicht direkt ausgeführt werden



 a| 
084
 a| 
EILSEQ
 a| 
Unzulässige Bytefolge



 a| 
085
 a| 
ERESTART
 a| 
Unterbrochener Systemaufruf sollte neu gestartet werden



 a| 
086
 a| 
ESTRPIPE
 a| 
Streams-Pipe-Fehler



 a| 
087
 a| 
EUSERS
 a| 
Zu viele Benutzer



 a| 
088
 a| 
ENOTSOCK
 a| 
Socket-Operation auf Nicht-Socket



 a| 
089
 a| 
EDESTADDRREQ
 a| 
Zieladresse erforderlich



 a| 
090
 a| 
EMSGSIZE
 a| 
Nachricht zu lang



 a| 
091
 a| 
EPROTOTYP
 a| 
Falscher Protokolltyp für Socket



 a| 
092
 a| 
ENOPROTOOPT
 a| 
Protokoll nicht verfügbar



 a| 
093
 a| 
EPROTONOSUPPORT
 a| 
Protokoll nicht unterstützt



 a| 
094
 a| 
ESOCKTNOSUPPORT
 a| 
Socket-Typ wird nicht unterstützt



 a| 
095
 a| 
EOPNOTSUPP
 a| 
Vorgang wird am Transportendpunkt nicht unterstützt



 a| 
096
 a| 
EPFNOSUPPORT
 a| 
Protokollfamilie wird nicht unterstützt



 a| 
097
 a| 
EAFNOSUPPORT
 a| 
Adressfamilie wird vom Protokoll nicht unterstützt



 a| 
098
 a| 
EADDRINUSE
 a| 
Adresse bereits verwendet



 a| 
099
 a| 
EADDRNOTAVAIL
 a| 
Die angeforderte Adresse kann nicht zugewiesen werden



 a| 
100
 a| 
ENETDOWN
 a| 
Das Netzwerk ist ausgefallen



 a| 
101
 a| 
ENETUNREACH
 a| 
Netzwerk ist nicht erreichbar



 a| 
102
 a| 
ENETRESET
 a| 
Die Netzwerkverbindung wurde aufgrund eines Resets unterbrochen



 a| 
103
 a| 
ABGEBROCHEN
 a| 
Software verursachte Verbindungsabbruch



 a| 
104
 a| 
ECONNRESET
 a| 
Verbindung vom Peer zurückgesetzt



 a| 
105
 a| 
ENOBUFS
 a| 
Kein Pufferspeicher verfügbar



 a| 
106
 a| 
EISCONN
 a| 
Transportendpunkt ist bereits verbunden



 a| 
107
 a| 
ENOTCONN
 a| 
Transportendpunkt ist nicht verbunden



 a| 
108
 a| 
ESHUTDOWN
 a| 
Nach dem Herunterfahren des Transportendpunkts kann nicht gesendet werden



 a| 
109
 a| 
ETOOMANYREFS
 a| 
Zu viele Referenzen: kann nicht zusammengefügt werden



 a| 
110
 a| 
ETIMEDOUT
 a| 
Verbindungs-Timeout



 a| 
111
 a| 
ECONNREFUSED
 a| 
Verbindung abgelehnt



 a| 
112
 a| 
EHOSTDOWN
 a| 
Host ist ausgefallen



 a| 
113
 a| 
EHOSTUNREACH
 a| 
Keine Route zum Host



 a| 
114
 a| 
BEREITS
 a| 
Vorgang läuft bereits



 a| 
115
 a| 
EINPROGRESS
 a| 
Der Vorgang läuft derzeit



 a| 
116
 a| 
 a| 



 a| 
117
 a| 
EUCLEAN
 a| 
Struktur muss gereinigt werden



 a| 
118
 a| 
ENOTNAM
 a| 
Keine XENIX-Datei mit benanntem Typ



 a| 
119
 a| 
ENAVAIL
 a| 
Keine XENIX-Semaphoren verfügbar



 a| 
120
 a| 
EISNAM
 a| 
Ist eine benannte Typdatei



 a| 
121
 a| 
EREMOTEIO
 a| 
Remote-E/A-Fehler



 a| 
122
 a| 
EDQUOT
 a| 
Kontingent überschritten



 a| 
123
 a| 
ENOMEDIUM
 a| 
Kein Medium gefunden



 a| 
124
 a| 
EMEDIUMTYPE
 a| 
Falscher Medientyp



 a| 
125
 a| 
ABGESAGT
 a| 
Vorgang abgebrochen



 a| 
126
 a| 
ENOKEY
 a| 
Erforderlicher Schlüssel nicht verfügbar



 a| 
127
 a| 
EKEY ABGELAUFEN
 a| 
Schlüssel ist abgelaufen



 a| 
128
 a| 
EKEY WIDERRUFEN
 a| 
Schlüssel wurde widerrufen



 a| 
129
 a| 
EKEYABGELEHNT
 a| 
Der Schlüssel wurde vom Dienst abgelehnt



 a| 
130
 a| 
EOWNERDEAD
 a| 
Für robuste Mutexe: Besitzer gestorben



 a| 
131
 a| 
NICHT WIEDERHERSTELLBAR
 a| 
Für robuste Mutexe: Zustand nicht wiederherstellbar

|===