---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: MIB-Dateien enthalten Definitionen und Informationen zu den Eigenschaften verwalteter Ressourcen und Dienste für die Knoten in Ihrem Grid.  Sie können auf MIB-Dateien zugreifen, die die Objekte und Benachrichtigungen für StorageGRID definieren.  Diese Dateien können für die Überwachung Ihres Netzes nützlich sein. 
---
= Zugriff auf MIB-Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MIB-Dateien enthalten Definitionen und Informationen zu den Eigenschaften verwalteter Ressourcen und Dienste für die Knoten in Ihrem Grid.  Sie können auf MIB-Dateien zugreifen, die die Objekte und Benachrichtigungen für StorageGRID definieren.  Diese Dateien können für die Überwachung Ihres Netzes nützlich sein.

Sehenlink:using-snmp-monitoring.html["Verwenden Sie die SNMP-Überwachung"] Weitere Informationen zu SNMP- und MIB-Dateien.



== Zugriff auf MIB-Dateien

Befolgen Sie diese Schritte, um auf die MIB-Dateien zuzugreifen.

.Schritte
. Wählen Sie *KONFIGURATION* > *Überwachung* > *SNMP-Agent*.
. Wählen Sie auf der SNMP-Agent-Seite die Datei aus, die Sie herunterladen möchten:
+
** *NETAPP-STORAGEGRID-MIB.txt*: Definiert die Warntabelle und Benachrichtigungen (Traps), auf die auf allen Admin-Knoten zugegriffen werden kann.
** *ES-NETAPP-06-MIB.mib*: Definiert Objekte und Benachrichtigungen für Geräte auf Basis der E-Serie.
** *MIB_1_10.zip*: Definiert Objekte und Benachrichtigungen für Appliances mit einer BMC Schnittstelle.
+
[]
====

TIP: Sie können auf jedem StorageGRID -Knoten auch am folgenden Speicherort auf MIB-Dateien zugreifen: `/usr/share/snmp/mibs`

====


. So extrahieren Sie die StorageGRID OIDs aus der MIB-Datei:
+
.. Holen Sie sich die OID des Stammverzeichnisses der StorageGRID -MIB:
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
Ergebnis: `.1.3.6.1.4.1.789.28669` (`28669` ist immer die OID für StorageGRID)

.. Suchen Sie im gesamten Baum nach der StorageGRID -OID (mithilfe `paste` zum Verbinden von Zeilen):
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`






TIP: Der `snmptranslate` Der Befehl verfügt über viele Optionen, die zum Erkunden der MIB nützlich sind.  Dieser Befehl ist auf jedem StorageGRID -Knoten verfügbar.



== Inhalt der MIB-Datei

Alle Objekte befinden sich unter der StorageGRID -OID.

[cols="1a,1a,2a"]
|===
| Objektname | Objekt-ID (OID) | Beschreibung 


| .iso.org.dod.internet.  + private.Unternehmen.  + netapp.storagegrid | .1.3.6.1.4.1.789.28669  a| 
Das MIB-Modul für NetApp StorageGRID Einheiten.

|===


== MIB-Objekte

[cols="1a,1a,2a"]
|===
| Objektname | Objekt-ID (OID) | Beschreibung 


| activeAlertCount | .1.3.6.1.4.1. + 789.28669.1.3  a| 
Die Anzahl der aktiven Warnungen in der activeAlertTable.



| aktiveAlarmtabelle | .1.3.6.1.4.1. + 789.28669.1.4  a| 
Eine Tabelle mit aktiven Warnungen in StorageGRID.



| aktiveAlertId | .1.3.6.1.4.1. + 789.28669.1.4.1.1  a| 
Die ID der Warnung.  Nur im aktuellen Satz aktiver Warnungen eindeutig.



| activeAlertName | .1.3.6.1.4.1. + 789.28669.1.4.1.2  a| 
Der Name der Warnung.



| activeAlertInstance | .1.3.6.1.4.1. + 789.28669.1.4.1.3  a| 
Der Name der Entität, die die Warnung generiert hat, normalerweise der Knotenname.



| activeAlertSeverity | .1.3.6.1.4.1. + 789.28669.1.4.1.4  a| 
Der Schweregrad der Warnung.



| activeAlertStartTime | .1.3.6.1.4.1. + 789.28669.1.4.1.5  a| 
Datum und Uhrzeit der Auslösung des Alarms.

|===


== Benachrichtigungstypen (Traps)

Alle Benachrichtigungen enthalten die folgenden Variablen als Varbinds:

* aktiveAlertId
* activeAlertName
* activeAlertInstance
* activeAlertSeverity
* activeAlertStartTime


[cols="1a,1a,2a"]
|===
| Benachrichtigungstyp | Objekt-ID (OID) | Beschreibung 


| aktiver MinorAlarm | .1.3.6.1.4.1. + 789.28669.0.6  a| 
Eine Warnung mit geringem Schweregrad



| aktiver MajorAlert | .1.3.6.1.4.1. + 789.28669.0.7  a| 
Eine Warnung mit hohem Schweregrad



| aktivKritischerAlarm | .1.3.6.1.4.1. + 789.28669.0.8  a| 
Eine Warnung mit kritischem Schweregrad

|===