---
permalink: monitor/removing-custom-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: Sie können eine benutzerdefinierte Warnregel entfernen, wenn Sie sie nicht mehr verwenden möchten. 
---
= Entfernen benutzerdefinierter Warnregeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine benutzerdefinierte Warnregel entfernen, wenn Sie sie nicht mehr verwenden möchten.

.Bevor Sie beginnen
* Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie haben dielink:../admin/admin-group-permissions.html["Verwalten von Warnungen oder Root-Zugriffsberechtigungen"] .


.Schritte
. Wählen Sie *WARNUNGEN* > *Regeln*.
+
Die Seite „Warnregeln“ wird angezeigt.

. Wählen Sie das Optionsfeld für die benutzerdefinierte Warnregel aus, die Sie entfernen möchten.
+
Sie können eine Standardwarnregel nicht entfernen.

. Wählen Sie *Benutzerdefinierte Regel entfernen*.
+
Ein Bestätigungsdialogfeld wird angezeigt.

. Wählen Sie *OK*, um die Warnregel zu entfernen.
+
Alle aktiven Instanzen der Warnung werden innerhalb von 10 Minuten behoben.


