---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: Sie können die Netzwerkkonfiguration durchführen, indem Sie mit dem Tool „IP ändern“ IP-Adressen für Grid-Knoten konfigurieren. 
---
= Richtlinien für IP-Adressen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Netzwerkkonfiguration durchführen, indem Sie mit dem Tool „IP ändern“ IP-Adressen für Grid-Knoten konfigurieren.

Sie müssen das Tool „IP ändern“ verwenden, um die meisten Änderungen an der Netzwerkkonfiguration vorzunehmen, die ursprünglich während der Grid-Bereitstellung festgelegt wurde.  Manuelle Änderungen mithilfe von standardmäßigen Linux-Netzwerkbefehlen und -dateien werden möglicherweise nicht auf alle StorageGRID -Dienste übertragen und bleiben möglicherweise bei Upgrades, Neustarts oder Knotenwiederherstellungsverfahren nicht erhalten.


NOTE: Das Verfahren zur Änderung der IP-Adresse kann ein störender Vorgang sein.  Teile des Rasters sind möglicherweise nicht verfügbar, bis die neue Konfiguration angewendet wird.


NOTE: Wenn Sie nur Änderungen an der Grid-Netzwerk-Subnetzliste vornehmen, verwenden Sie den Grid-Manager, um die Netzwerkkonfiguration hinzuzufügen oder zu ändern.  Verwenden Sie andernfalls das Tool „IP ändern“, wenn auf den Grid Manager aufgrund eines Netzwerkkonfigurationsproblems nicht zugegriffen werden kann oder Sie gleichzeitig eine Änderung der Grid-Netzwerkweiterleitung und andere Netzwerkänderungen durchführen.


TIP: Wenn Sie die Grid-Netzwerk-IP-Adresse für alle Knoten im Grid ändern möchten, verwenden Sie dielink:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["Sonderverfahren für netzweite Änderungen"] .



== Ethernet-Schnittstellen

Die eth0 zugewiesene IP-Adresse ist immer die Grid-Netzwerk-IP-Adresse des Grid-Knotens.  Die eth1 zugewiesene IP-Adresse ist immer die Admin-Netzwerk-IP-Adresse des Grid-Knotens.  Die eth2 zugewiesene IP-Adresse ist immer die Client-Netzwerk-IP-Adresse des Grid-Knotens.

Beachten Sie, dass es sich bei eth0, eth1 und eth2 auf einigen Plattformen, z. B. StorageGRID -Geräten, möglicherweise um aggregierte Schnittstellen handelt, die aus untergeordneten Brücken oder Verbindungen von physischen oder VLAN-Schnittstellen bestehen.  Auf diesen Plattformen werden auf der Registerkarte *SSM* > *Ressourcen* möglicherweise die Grid-, Admin- und Client-Netzwerk-IP-Adressen angezeigt, die zusätzlich zu eth0, eth1 oder eth2 anderen Schnittstellen zugewiesen sind.



== DHCP

Sie können DHCP nur während der Bereitstellungsphase einrichten.  Sie können DHCP während der Konfiguration nicht einrichten.  Sie müssen die Verfahren zum Ändern der IP-Adresse verwenden, wenn Sie IP-Adressen, Subnetzmasken und Standard-Gateways für einen Grid-Knoten ändern möchten.  Durch die Verwendung des Tools „IP ändern“ werden DHCP-Adressen statisch.



== Hochverfügbarkeitsgruppen (HA)

* Wenn eine Client-Netzwerkschnittstelle in einer HA-Gruppe enthalten ist, können Sie die Client-Netzwerk-IP-Adresse für diese Schnittstelle nicht in eine Adresse ändern, die außerhalb des für die HA-Gruppe konfigurierten Subnetzes liegt.
* Sie können die Client-Netzwerk-IP-Adresse nicht in den Wert einer vorhandenen virtuellen IP-Adresse ändern, die einer auf der Client-Netzwerkschnittstelle konfigurierten HA-Gruppe zugewiesen ist.
* Wenn eine Grid-Netzwerkschnittstelle in einer HA-Gruppe enthalten ist, können Sie die Grid-Netzwerk-IP-Adresse für diese Schnittstelle nicht in eine Adresse ändern, die außerhalb des für die HA-Gruppe konfigurierten Subnetzes liegt.
* Sie können die Grid-Netzwerk-IP-Adresse nicht in den Wert einer vorhandenen virtuellen IP-Adresse ändern, die einer auf der Grid-Netzwerkschnittstelle konfigurierten HA-Gruppe zugewiesen ist.

