---
permalink: maintain/gathering-required-materials-site-decom.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: Bevor Sie eine Site außer Betrieb nehmen, müssen Sie die folgenden Materialien beschaffen. 
---
= Benötigte Materialien zusammenstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine Site außer Betrieb nehmen, müssen Sie die folgenden Materialien beschaffen.

[cols="1a,2a"]
|===
| Artikel | Hinweise 


 a| 
Wiederherstellungspaket `.zip` Datei
 a| 
Sie müssen das neueste Wiederherstellungspaket herunterladen `.zip` Datei(`sgws-recovery-package-id-revision.zip` ).  Mit der Wiederherstellungspaketdatei können Sie das System im Falle eines Fehlers wiederherstellen.

link:downloading-recovery-package.html["Laden Sie das Wiederherstellungspaket herunter"]



 a| 
`Passwords.txt`Datei
 a| 
Diese Datei enthält die für den Zugriff auf Grid-Knoten über die Befehlszeile erforderlichen Passwörter und ist im Wiederherstellungspaket enthalten.



 a| 
Bereitstellungspassphrase
 a| 
Die Passphrase wird bei der Erstinstallation des StorageGRID -Systems erstellt und dokumentiert.  Die Bereitstellungspassphrase ist nicht in der `Passwords.txt` Datei.



 a| 
Beschreibung der Topologie des StorageGRID -Systems vor der Außerbetriebnahme
 a| 
Besorgen Sie sich, sofern verfügbar, alle Unterlagen, die die aktuelle Topologie des Systems beschreiben.

|===
.Ähnliche Informationen
link:../admin/web-browser-requirements.html["Anforderungen an den Webbrowser"]
