---
permalink: maintain/powering-off-and-on-all-nodes-in-grid.html 
sidebar: sidebar 
keywords: storagegrid, recover, power nodes, power on nodes, power off nodes, power down nodes 
summary: Möglicherweise müssen Sie Ihr gesamtes StorageGRID -System herunterfahren, beispielsweise wenn Sie ein Rechenzentrum verlegen.  Diese Schritte bieten einen allgemeinen Überblick über die empfohlene Reihenfolge zum Durchführen eines kontrollierten Herunterfahrens und Startens. 
---
= Schalten Sie alle Knoten im Netz aus und wieder ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie Ihr gesamtes StorageGRID -System herunterfahren, beispielsweise wenn Sie ein Rechenzentrum verlegen.  Diese Schritte bieten einen allgemeinen Überblick über die empfohlene Reihenfolge zum Durchführen eines kontrollierten Herunterfahrens und Startens.

Wenn Sie alle Knoten in einer Site oder einem Grid ausschalten, können Sie nicht auf aufgenommene Objekte zugreifen, während die Speicherknoten offline sind.



== Dienste stoppen und Grid-Knoten herunterfahren

Bevor Sie ein StorageGRID -System ausschalten können, müssen Sie alle auf jedem Grid-Knoten ausgeführten Dienste stoppen und dann alle virtuellen VMware-Maschinen, Container-Engines und StorageGRID Geräte herunterfahren.

.Informationen zu diesem Vorgang
Stoppen Sie zuerst die Dienste auf den Admin-Knoten und Gateway-Knoten und dann die Dienste auf den Speicherknoten.

Mit diesem Ansatz können Sie den primären Admin-Knoten verwenden, um den Status der anderen Grid-Knoten so lange wie möglich zu überwachen.


NOTE: Wenn ein einzelner Host mehr als einen Grid-Knoten enthält, fahren Sie den Host erst herunter, wenn Sie alle Knoten auf diesem Host gestoppt haben.  Wenn der Host den primären Admin-Knoten enthält, fahren Sie diesen Host zuletzt herunter.


NOTE: Bei Bedarf können Sielink:linux-migrating-grid-node-to-new-host.html["Knoten von einem Linux-Host auf einen anderen migrieren"] um Host-Wartungsarbeiten durchzuführen, ohne die Funktionalität oder Verfügbarkeit Ihres Grids zu beeinträchtigen.

.Schritte
. Verhindern Sie, dass alle Clientanwendungen auf das Grid zugreifen.
. [[log_in_to_gn]]Melden Sie sich bei jedem Gateway-Knoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das Passwort ein, das in der `Passwords.txt` Datei.
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das Passwort ein, das in der `Passwords.txt` Datei.


+
Wenn Sie als Root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Zu `#` .

. [[stop_all_services]]Stoppen Sie alle auf dem Knoten laufenden Dienste: `service servermanager stop`
+
Das Herunterfahren von Diensten kann bis zu 15 Minuten dauern. Sie möchten sich möglicherweise per Fernzugriff beim System anmelden, um den Herunterfahrvorgang zu überwachen.

. Wiederholen Sie die beiden vorherigen Schritte, um die Dienste auf allen Speicherknoten und nicht primären Admin-Knoten zu stoppen.
+
Sie können die Dienste auf diesen Knoten in beliebiger Reihenfolge stoppen.

+

NOTE: Wenn Sie die `service servermanager stop` Befehl zum Stoppen der Dienste auf einem Appliance-Speicherknoten. Sie müssen die Appliance aus- und wieder einschalten, um den Knoten neu zu starten.

. Für den primären Admin-Knoten wiederholen Sie die Schritte für<<log_in_to_gn,Anmelden am Knoten>> Und<<stop_all_services,Stoppen aller Dienste auf dem Knoten>> .
. Für Knoten, die auf Linux-Hosts ausgeführt werden:
+
.. Melden Sie sich beim Host-Betriebssystem an.
.. Stoppen Sie den Knoten: `storagegrid node stop`
.. Fahren Sie das Host-Betriebssystem herunter.


. Geben Sie für Knoten, die auf virtuellen VMware-Maschinen ausgeführt werden, und für Appliance-Speicherknoten den Befehl „shutdown“ ein: `shutdown -h now`
+
Führen Sie diesen Schritt unabhängig vom Ergebnis der `service servermanager stop` Befehl.

+
Für die Appliance fährt dieser Befehl den Compute-Controller herunter, die Appliance bleibt jedoch weiterhin eingeschaltet.  Sie müssen den nächsten Schritt abschließen.

. Wenn Sie über Appliance-Knoten verfügen, befolgen Sie die Schritte für Ihre Appliance.
+
[role="tabbed-block"]
====
.SG110 oder SG1100
--
.. Schalten Sie die Stromversorgung des Geräts aus.
.. Warten Sie, bis die blaue Betriebs-LED erlischt.


--
.SG100 oder SG1000
--
.. Schalten Sie die Stromversorgung des Geräts aus.
.. Warten Sie, bis die blaue Betriebs-LED erlischt.


--
.SG6160
--
.. Schalten Sie die Stromversorgung des SG6100-CN-Speichercontrollers aus.
.. Warten Sie, bis die blaue Betriebs-LED am SG6100-CN-Speichercontroller erlischt.


--
.SGF6112
--
.. Schalten Sie die Stromversorgung des Geräts aus.
.. Warten Sie, bis die blaue Betriebs-LED erlischt.


--
.SG6000
--
.. Warten Sie, bis die grüne Cache Active-LED auf der Rückseite der Speichercontroller erlischt.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen.  Sie müssen warten, bis diese LED erlischt, bevor Sie die Stromversorgung ausschalten.

.. Schalten Sie das Gerät aus und warten Sie, bis die blaue Betriebs-LED erlischt.


--
.SG5800
--
.. Warten Sie, bis die grüne Cache Active-LED auf der Rückseite des Speichercontrollers erlischt.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen.  Sie müssen warten, bis diese LED erlischt, bevor Sie die Stromversorgung ausschalten.

.. Wählen Sie auf der Startseite des SANtricity System Managers *Laufende Vorgänge anzeigen* aus.
.. Bestätigen Sie, dass alle Vorgänge abgeschlossen sind, bevor Sie mit dem nächsten Schritt fortfahren.
.. Schalten Sie beide Netzschalter am Controller-Regal aus und warten Sie, bis alle LEDs am Controller-Regal erloschen sind.


--
.SG5700
--
.. Warten Sie, bis die grüne Cache Active-LED auf der Rückseite des Speichercontrollers erlischt.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen.  Sie müssen warten, bis diese LED erlischt, bevor Sie die Stromversorgung ausschalten.

.. Schalten Sie das Gerät aus und warten Sie, bis alle LED- und Siebensegmentanzeigen nicht mehr aktiv sind.


--
====
. Melden Sie sich bei Bedarf von der Befehlsshell ab: `exit`
+
Das StorageGRID -Netz wurde inzwischen abgeschaltet.





== Grid-Knoten starten


CAUTION: Wenn das gesamte Netz länger als 15 Tage heruntergefahren war, müssen Sie sich an den technischen Support wenden, bevor Sie Netzknoten hochfahren.  Versuchen Sie nicht, die Wiederherstellungsverfahren zum Wiederherstellen von Cassandra-Daten durchzuführen.  Dies kann zu Datenverlust führen.

Schalten Sie die Netzknoten nach Möglichkeit in dieser Reihenfolge ein:

* Schalten Sie zuerst die Admin-Knoten ein.
* Schalten Sie die Gateway-Knoten zuletzt ein.



NOTE: Wenn ein Host mehrere Grid-Knoten enthält, werden die Knoten automatisch wieder online geschaltet, wenn Sie den Host einschalten.

.Schritte
. Schalten Sie die Hosts für den primären Admin-Knoten und alle nicht primären Admin-Knoten ein.
+

NOTE: Sie können sich erst bei den Admin-Knoten anmelden, wenn die Speicherknoten neu gestartet wurden.

. Schalten Sie die Hosts für alle Speicherknoten ein.
+
Sie können diese Knoten in beliebiger Reihenfolge einschalten.

. Schalten Sie die Hosts für alle Gateway-Knoten ein.
. Sign in .
. Wählen Sie *NODES* aus und überwachen Sie den Status der Grid-Knoten. Stellen Sie sicher, dass neben den Knotennamen keine Warnsymbole angezeigt werden.


.Ähnliche Informationen
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112 und SG6160 Speichergeräte"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110 und SG1100 Servicegeräte"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100 und SG1000 Servicegeräte"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000-Speichergeräte"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["SG5800-Speichergeräte"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700-Speichergeräte"^]

