---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: Sie müssen eine Reihe von Aufgaben ausführen, um einen softwarebasierten Speicherknoten wiederherzustellen, bei dem ein oder mehrere Speichervolumes auf dem Speicherknoten ausgefallen sind, das Systemlaufwerk jedoch intakt ist.  Wenn nur Speichervolumes ausgefallen sind, steht der Speicherknoten dem StorageGRID -System weiterhin zur Verfügung. 
---
= Wiederherstellung nach einem Speichervolume-Fehler, wenn das Systemlaufwerk intakt ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen eine Reihe von Aufgaben ausführen, um einen softwarebasierten Speicherknoten wiederherzustellen, bei dem ein oder mehrere Speichervolumes auf dem Speicherknoten ausgefallen sind, das Systemlaufwerk jedoch intakt ist.  Wenn nur Speichervolumes ausgefallen sind, steht der Speicherknoten dem StorageGRID -System weiterhin zur Verfügung.


NOTE: Dieses Wiederherstellungsverfahren gilt nur für softwarebasierte Speicherknoten.  Wenn Speichervolumes auf einem Appliance-Speicherknoten ausgefallen sind, verwenden Sie stattdessen das Appliance-Verfahren:link:recovering-storagegrid-appliance-storage-node.html["Wiederherstellen des Appliance-Speicherknotens"] .

Dieses Wiederherstellungsverfahren umfasst die folgenden Aufgaben:

* link:reviewing-warnings-about-storage-volume-recovery.html["Überprüfen Sie die Warnungen zur Wiederherstellung des Speichervolumes"]
* link:identifying-and-unmounting-failed-storage-volumes.html["Identifizieren und Unmounten fehlerhafter Speichervolumes"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Stellen Sie die Volumes wieder her und erstellen Sie die Cassandra-Datenbank neu"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Objektdaten wiederherstellen"]
* link:checking-storage-state-after-recovering-storage-volumes.html["Überprüfen Sie den Speicherstatus"]

