---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: Wenn Sie die historischen Informationen zu Attributen und Warnungen auf einem nicht primären Admin-Knoten, der ausgefallen ist, behalten möchten, können Sie die Admin-Knoten-Datenbank vom primären Admin-Knoten wiederherstellen. 
---
= Wiederherstellen der Admin-Knoten-Datenbank beim Wiederherstellen eines nicht primären Admin-Knotens
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die historischen Informationen zu Attributen und Warnungen auf einem nicht primären Admin-Knoten, der ausgefallen ist, behalten möchten, können Sie die Admin-Knoten-Datenbank vom primären Admin-Knoten wiederherstellen.

.Bevor Sie beginnen
* Der wiederhergestellte Admin-Knoten ist installiert und läuft.
* Das StorageGRID -System umfasst mindestens zwei Admin-Knoten.
* Sie haben die `Passwords.txt` Datei.
* Sie haben die Bereitstellungspassphrase.


.Informationen zu diesem Vorgang
Wenn ein Admin-Knoten ausfällt, gehen die in seiner Admin-Knoten-Datenbank gespeicherten historischen Informationen verloren.  Diese Datenbank enthält die folgenden Informationen:

* Alarmverlauf
* Historische Attributdaten, die in Diagrammen im Legacy-Stil auf der Seite „Knoten“ verwendet werden


Wenn Sie einen Admin-Knoten wiederherstellen, erstellt der Softwareinstallationsprozess eine leere Admin-Knoten-Datenbank auf dem wiederhergestellten Knoten.  Die neue Datenbank enthält jedoch nur Informationen zu Servern und Diensten, die derzeit Teil des Systems sind oder später hinzugefügt werden.

Wenn Sie einen nicht primären Admin-Knoten wiederhergestellt haben, können Sie die historischen Informationen wiederherstellen, indem Sie die Admin-Knoten-Datenbank vom primären Admin-Knoten (dem _Quell-Admin-Knoten_) auf den wiederhergestellten Knoten kopieren.


NOTE: Das Kopieren der Admin-Knoten-Datenbank kann mehrere Stunden dauern.  Einige Grid Manager-Funktionen sind nicht verfügbar, während die Dienste auf dem Quellknoten angehalten sind.

.Schritte
. Melden Sie sich beim Quelladministratorknoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das Passwort ein, das in der `Passwords.txt` Datei.
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das Passwort ein, das in der `Passwords.txt` Datei.


. Führen Sie den folgenden Befehl vom Quelladministratorknoten aus.  Geben Sie dann die Bereitstellungspassphrase ein, wenn Sie dazu aufgefordert werden. `recover-access-points`
. Stoppen Sie den MI-Dienst vom Quell-Admin-Knoten aus: `service mi stop`
. Stoppen Sie vom Quelladministratorknoten aus den Dienst „Management Application Program Interface“ (mgmt-api): `service mgmt-api stop`
. Führen Sie auf dem wiederhergestellten Admin-Knoten die folgenden Schritte aus:
+
.. Melden Sie sich beim wiederhergestellten Admin-Knoten an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das Passwort ein, das in der `Passwords.txt` Datei.
... Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
... Geben Sie das Passwort ein, das in der `Passwords.txt` Datei.


.. Beenden Sie den MI-Dienst: `service mi stop`
.. Stoppen Sie den mgmt-api-Dienst: `service mgmt-api stop`
.. Fügen Sie dem SSH-Agenten den privaten SSH-Schlüssel hinzu.  Eingeben:``ssh-add``
.. Geben Sie das SSH-Zugriffskennwort ein, das im `Passwords.txt` Datei.
.. Kopieren Sie die Datenbank vom Quell-Admin-Knoten auf den wiederhergestellten Admin-Knoten: `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. Bestätigen Sie bei der entsprechenden Aufforderung, dass Sie die MI-Datenbank auf dem wiederhergestellten Admin-Knoten überschreiben möchten.
+
Die Datenbank und ihre historischen Daten werden auf den wiederhergestellten Admin-Knoten kopiert.  Wenn der Kopiervorgang abgeschlossen ist, startet das Skript den wiederhergestellten Admin-Knoten.

.. Wenn Sie keinen passwortlosen Zugriff auf andere Server mehr benötigen, entfernen Sie den privaten Schlüssel aus dem SSH-Agenten.  Eingeben:``ssh-add -D``


. Starten Sie die Dienste auf dem Quelladministratorknoten neu: `service servermanager start`

