---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: Wenn Sie planen, einen Speicherknoten außer Betrieb zu nehmen, sollten Sie die ILM-Richtlinie Ihres StorageGRID Systems überprüfen, bevor Sie mit dem Außerbetriebnahmeprozess beginnen. 
---
= Überprüfen der ILM-Richtlinie und Speicherkonfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie planen, einen Speicherknoten außer Betrieb zu nehmen, sollten Sie die ILM-Richtlinie Ihres StorageGRID Systems überprüfen, bevor Sie mit dem Außerbetriebnahmeprozess beginnen.

Während der Außerbetriebnahme werden alle Objektdaten vom außer Betrieb genommenen Speicherknoten auf andere Speicherknoten migriert.


NOTE: Die ILM-Richtlinie, die Sie _während_ der Außerbetriebnahme haben, wird auch _nach_ der Außerbetriebnahme verwendet.  Sie müssen sicherstellen, dass diese Richtlinie Ihren Datenanforderungen sowohl vor Beginn der Außerbetriebnahme als auch nach Abschluss der Außerbetriebnahme entspricht.

Sie sollten die Regeln in jedemlink:../ilm/creating-ilm-policy.html["aktive ILM-Richtlinie"] um sicherzustellen, dass das StorageGRID -System weiterhin über genügend Kapazität des richtigen Typs und an den richtigen Standorten verfügt, um die Außerbetriebnahme eines Speicherknotens zu ermöglichen.

Beachten Sie Folgendes:

* Wird es ILM-Auswertungsdiensten möglich sein, Objektdaten so zu kopieren, dass die ILM-Regeln eingehalten werden?
* Was passiert, wenn ein Standort während der Stilllegung vorübergehend nicht verfügbar ist?  Können zusätzliche Kopien an einem anderen Ort erstellt werden?
* Welche Auswirkungen hat der Außerbetriebnahmeprozess auf die endgültige Verbreitung der Inhalte?  Wie beschrieben inlink:consolidating-storage-nodes.html["Konsolidieren Sie Speicherknoten"] , Du solltestlink:../expand/index.html["neue Speicherknoten hinzufügen"] bevor Sie alte außer Betrieb nehmen.  Wenn Sie nach der Außerbetriebnahme eines kleineren Speicherknotens einen größeren Ersatzspeicherknoten hinzufügen, ist die Kapazität der alten Speicherknoten möglicherweise fast erschöpft und der neue Speicherknoten enthält möglicherweise fast keinen Inhalt.  Die meisten Schreibvorgänge für neue Objektdaten würden dann auf den neuen Speicherknoten gerichtet, was die Gesamteffizienz der Systemvorgänge verringern würde.
* Verfügt das System jederzeit über genügend Speicherknoten, um die aktiven ILM-Richtlinien zu erfüllen?
+

NOTE: Eine ILM-Richtlinie, die nicht erfüllt werden kann, führt zu Rückständen und Warnungen und kann den Betrieb des StorageGRID -Systems stoppen.



Überprüfen Sie, ob die vorgeschlagene Topologie, die sich aus dem Außerbetriebnahmeprozess ergibt, der ILM-Richtlinie entspricht, indem Sie die in der Tabelle aufgeführten Bereiche bewerten.

[cols="1a,2a"]
|===
| Zu bewertender Bereich | Was ist zu beachten 


 a| 
Verfügbare Kapazität
 a| 
Wird genügend Speicherkapazität vorhanden sein, um alle im StorageGRID System gespeicherten Objektdaten aufzunehmen, einschließlich der permanenten Kopien der Objektdaten, die derzeit auf dem zu stilllegenden Storage Node gespeichert sind?

Wird es für einen angemessenen Zeitraum nach der Stilllegung genügend Kapazität geben, um das erwartete Wachstum der gespeicherten Objektdaten zu bewältigen?



 a| 
Speicherort
 a| 
Wenn im StorageGRID -System als Ganzes genügend Kapazität verbleibt, ist die Kapazität dann an den richtigen Standorten, um die Geschäftsregeln des StorageGRID Systems zu erfüllen?



 a| 
Speichertyp
 a| 
Wird es nach der Stilllegung genügend Lagerkapazitäten des entsprechenden Typs geben?

Beispielsweise können ILM-Regeln Inhalte von einem Speichertyp auf einen anderen verschieben, wenn sie älter werden.  In diesem Fall müssen Sie sicherstellen, dass in der endgültigen Konfiguration des StorageGRID -Systems genügend Speicher des entsprechenden Typs verfügbar ist.

|===