---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: 'In Schritt 3 (ILM-Richtlinien überarbeiten) des Assistenten „Site außer Betrieb nehmen“ können Sie feststellen, ob auf die Site eine ILM-Richtlinie verweist.' 
---
= Schritt 3: ILM-Richtlinien überarbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Schritt 3 (ILM-Richtlinien überarbeiten) des Assistenten „Site außer Betrieb nehmen“ können Sie feststellen, ob auf die Site eine ILM-Richtlinie verweist.

.Bevor Sie beginnen
Sie haben ein gutes Verständnis dafür, wie manlink:../ilm/index.html["Objekte mit ILM verwalten"] .  Sie sind mit der Erstellung von Speicherpools und ILM-Regeln sowie mit der Simulation und Aktivierung einer ILM-Richtlinie vertraut.

.Informationen zu diesem Vorgang
StorageGRID kann eine Site nicht außer Betrieb nehmen, wenn eine ILM-Regel in einer Richtlinie (aktiv oder inaktiv) auf diese Site verweist.

Wenn sich eine ILM-Richtlinie auf die Site bezieht, die Sie außer Betrieb nehmen möchten, müssen Sie diese Richtlinien entfernen oder bearbeiten, sodass sie die folgenden Anforderungen erfüllen:

* Vollständiger Schutz aller Objektdaten.
* Beziehen Sie sich nicht auf die Site, die Sie außer Betrieb nehmen.
* Verwenden Sie keine Speicherpools, die auf die Site verweisen, und verwenden Sie nicht die Option „Alle Sites“.
* Verwenden Sie keine Erasure-Coding-Profile, die sich auf die Site beziehen.
* Verwenden Sie nicht die Regel „2 Kopien erstellen“ aus StorageGRID 11.6 oder früheren Installationen.



CAUTION: Erstellen Sie niemals eine ILM-Regel für eine einzelne Kopie, um die Entfernung einer Site zu ermöglichen.  Eine ILM-Regel, die für einen bestimmten Zeitraum nur eine replizierte Kopie erstellt, birgt das Risiko eines dauerhaften Datenverlusts.  Wenn nur eine replizierte Kopie eines Objekts vorhanden ist, geht dieses Objekt verloren, wenn ein Speicherknoten ausfällt oder einen schwerwiegenden Fehler aufweist.  Auch während Wartungsvorgängen wie Upgrades verlieren Sie vorübergehend den Zugriff auf das Objekt.


TIP: Wenn Sie eine _Außerbetriebnahme einer verbundenen Site_ durchführen, müssen Sie berücksichtigen, wie StorageGRID die Objektdaten verwalten soll, die sich derzeit auf der Site befinden, die Sie entfernen möchten.  Je nach Ihren Datenschutzanforderungen können neue Regeln vorhandene Objektdaten an andere Standorte verschieben oder zusätzliche Objektkopien löschen, die nicht mehr benötigt werden.

Wenden Sie sich an den technischen Support, wenn Sie Hilfe beim Entwerfen einer neuen Richtlinie benötigen.

.Schritte
. Stellen Sie in Schritt 3 (ILM-Richtlinien überarbeiten) fest, ob sich ILM-Richtlinien auf die Site beziehen, die Sie zur Außerbetriebnahme ausgewählt haben.
. Wenn keine Richtlinien aufgelistet sind, wählen Sie *Weiter*, um zulink:step-4-remove-ilm-references.html["Schritt 4: ILM-Referenzen entfernen"] .
. Wenn eine oder mehrere _aktive_ ILM-Richtlinien aufgelistet sind, klonen Sie jede vorhandene Richtlinie oder erstellen Sie neue Richtlinien, die nicht auf die Site verweisen, die außer Betrieb genommen wird:
+
.. Wählen Sie den Link für die Richtlinie in der Spalte „Richtlinienname“ aus.
+
Die Detailseite der ILM-Richtlinie für die Richtlinie wird in einem neuen Browser-Tab angezeigt.  Die Seite „Standort außer Betrieb nehmen“ bleibt auf der anderen Registerkarte geöffnet.

.. Befolgen Sie bei Bedarf diese Richtlinien und Anweisungen:
+
*** Arbeiten mit ILM-Regeln:
+
**** link:../ilm/creating-storage-pool.html["Erstellen Sie einen oder mehrere Speicherpools"]die sich nicht auf die Site beziehen.
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["Regeln bearbeiten oder ersetzen"]die auf die Site verweisen.
+

NOTE: Wählen Sie nicht die Regel *2 Kopien erstellen* aus, da diese Regel den Speicherpool *Alle Speicherknoten* verwendet, was nicht zulässig ist.



*** Arbeiten mit ILM-Richtlinien:
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["Klonen einer vorhandenen ILM-Richtlinie"]oderlink:../ilm/creating-ilm-policy.html["Erstellen einer neuen ILM-Richtlinie"] .
**** Stellen Sie sicher, dass sich die Standardregel und andere Regeln nicht auf die Site beziehen.
+

CAUTION: Sie müssen bestätigen, dass die ILM-Regeln in der richtigen Reihenfolge sind.  Wenn die Richtlinie aktiviert ist, werden neue und vorhandene Objekte von den Regeln in der aufgeführten Reihenfolge (von oben beginnend) ausgewertet.





.. Nehmen Sie Testobjekte auf und simulieren Sie die Richtlinie, um sicherzustellen, dass die richtigen Regeln angewendet werden.
+

CAUTION: Fehler in einer ILM-Richtlinie können zu nicht wiederherstellbarem Datenverlust führen.  Überprüfen und simulieren Sie die Richtlinie sorgfältig, bevor Sie sie aktivieren, um sicherzustellen, dass sie wie vorgesehen funktioniert.

+

CAUTION: Wenn Sie eine neue ILM-Richtlinie aktivieren, verwendet StorageGRID diese zum Verwalten aller Objekte, einschließlich vorhandener und neu aufgenommener Objekte.  Überprüfen Sie vor der Aktivierung einer neuen ILM-Richtlinie alle Änderungen an der Platzierung vorhandener replizierter und löschcodierter Objekte.  Das Ändern des Standorts eines vorhandenen Objekts kann zu vorübergehenden Ressourcenproblemen führen, wenn die neuen Platzierungen ausgewertet und implementiert werden.

.. Aktivieren Sie die neuen Richtlinien und stellen Sie sicher, dass die alten Richtlinien jetzt inaktiv sind.
+
Wenn Sie mehrere Richtlinien aktivieren möchten,link:../ilm/creating-ilm-policy.html#activate-ilm-policy["Befolgen Sie die Schritte zum Erstellen von ILM-Richtlinientags"] .

+
Wenn Sie eine verbundene Site außer Betrieb nehmen, beginnt StorageGRID mit dem Entfernen von Objektdaten von der ausgewählten Site, sobald Sie die neue ILM-Richtlinie aktivieren.  Das Verschieben oder Löschen aller Objektkopien kann Wochen dauern.  Obwohl Sie eine Site-Außerbetriebnahme sicher starten können, während sich noch Objektdaten auf der Site befinden, wird der Außerbetriebnahmevorgang schneller und mit weniger Unterbrechungen und Leistungseinbußen abgeschlossen, wenn Sie das Verschieben von Daten von der Site zulassen, bevor Sie den eigentlichen Außerbetriebnahmevorgang starten (indem Sie in Schritt 5 des Assistenten *Außerbetriebnahme starten* auswählen).



. Bearbeiten oder entfernen Sie jede _inaktive_ Richtlinie, indem Sie zunächst den Link für die jeweilige Richtlinie auswählen, wie in den vorherigen Schritten beschrieben.
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["Bearbeiten der Richtlinie"]Es handelt sich also nicht um den stillzulegenden Standort.
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["Entfernen einer Richtlinie"] .


. Wenn Sie mit den Änderungen an den ILM-Regeln und -Richtlinien fertig sind, sollten in Schritt 3 (ILM-Richtlinien überarbeiten) keine weiteren Richtlinien mehr aufgeführt sein. Wählen Sie *Weiter*.
+
Schritt 4 (ILM-Referenzen entfernen) wird angezeigt.


