---
permalink: expand/adding-grid-nodes-to-add-capabilities.html 
sidebar: sidebar 
keywords: grid nodes, expand, expansion, site, add 
summary: Sie können einem StorageGRID -System Redundanz oder zusätzliche Funktionen hinzufügen, indem Sie vorhandenen Sites neue Grid-Knoten hinzufügen. 
---
= Fügen Sie Grid-Knoten hinzu, um Ihrem System Funktionen hinzuzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einem StorageGRID -System Redundanz oder zusätzliche Funktionen hinzufügen, indem Sie vorhandenen Sites neue Grid-Knoten hinzufügen.

Sie können beispielsweise Gateway-Knoten zur Verwendung in einer Hochverfügbarkeitsgruppe (HA) hinzufügen oder einen Admin-Knoten an einem Remote-Standort hinzufügen, um die Überwachung mithilfe eines lokalen Knotens zu ermöglichen.

Sie können in einem einzigen Erweiterungsvorgang einen oder mehrere der folgenden Knotentypen zu einer oder mehreren vorhandenen Sites hinzufügen:

* Nicht-primäre Admin-Knoten
* Speicherknoten
* Gateway-Knoten


Beachten Sie beim Hinzufügen von Rasterknoten die folgenden Einschränkungen:

* Der primäre Admin-Knoten wird während der Erstinstallation bereitgestellt.  Sie können während einer Erweiterung keinen primären Admin-Knoten hinzufügen.
* Sie können Speicherknoten und andere Knotentypen in derselben Erweiterung hinzufügen.
* Beim Hinzufügen von Speicherknoten müssen Sie die Anzahl und den Standort der neuen Knoten sorgfältig planen. Sehen link:../expand/guidelines-for-adding-object-capacity.html["Richtlinien zum Hinzufügen von Objektkapazität"] .
* Wenn die Option *Neuen Knotenstandard festlegen* auf der Registerkarte „Nicht vertrauenswürdige Client-Netzwerke“ der Seite „Firewall-Steuerung“ auf „Nicht vertrauenswürdig“ gesetzt ist, müssen Client-Anwendungen, die über das Client-Netzwerk eine Verbindung zu Erweiterungsknoten herstellen, die Verbindung über einen Endpunktport des Lastenausgleichs herstellen (*KONFIGURATION* > *Sicherheit* > *Firewall-Steuerung*). Siehe die Anweisungen zulink:../admin/configure-firewall-controls.html["Ändern Sie die Sicherheitseinstellungen für den neuen Knoten"] und zulink:../admin/configuring-load-balancer-endpoints.html["Konfigurieren Sie Load Balancer-Endpunkte"] .

