---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: Nachdem ein Erweiterungsvorgang zum Hinzufügen neuer Speicherknoten abgeschlossen ist, sollte das StorageGRID -System automatisch mit der Verwendung der neuen Speicherknoten beginnen.  Sie müssen das StorageGRID -System verwenden, um zu überprüfen, ob der neue Speicherknoten aktiv ist. 
---
= Überprüfen Sie, ob der Speicherknoten aktiv ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem ein Erweiterungsvorgang zum Hinzufügen neuer Speicherknoten abgeschlossen ist, sollte das StorageGRID -System automatisch mit der Verwendung der neuen Speicherknoten beginnen.  Sie müssen das StorageGRID -System verwenden, um zu überprüfen, ob der neue Speicherknoten aktiv ist.

.Schritte
. Sign in beim Grid Manager an mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
. Wählen Sie *KNOTEN* > *_Erweiterungsspeicherknoten_* > *Speicher*.
. Positionieren Sie den Cursor über dem Diagramm *Benutzter Speicher – Objektdaten*, um den Wert für *Benutzt* anzuzeigen. Dabei handelt es sich um die Menge des insgesamt nutzbaren Speicherplatzes, der für Objektdaten verwendet wurde.
. Überprüfen Sie, ob der Wert von *Verwendet* zunimmt, wenn Sie den Cursor im Diagramm nach rechts bewegen.

