---
permalink: ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html 
sidebar: sidebar 
keywords: cloud storage pools, cloudmirror replication 
summary: Wenn Sie mit der Verwendung von Cloud Storage Pools beginnen, kann es hilfreich sein, die Ähnlichkeiten und Unterschiede zwischen Cloud Storage Pools und dem StorageGRID CloudMirror-Replikationsdienst zu verstehen. 
---
= Vergleichen Sie Cloud Storage Pools und CloudMirror-Replikation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie mit der Verwendung von Cloud Storage Pools beginnen, kann es hilfreich sein, die Ähnlichkeiten und Unterschiede zwischen Cloud Storage Pools und dem StorageGRID CloudMirror-Replikationsdienst zu verstehen.

[cols="1a,3a,3a"]
|===
|  | Cloud-Speicherpool | CloudMirror-Replikationsdienst 


 a| 
Was ist der Hauptzweck?
 a| 
Fungiert als Archivierungsziel.  Die Objektkopie im Cloud Storage Pool kann die einzige Kopie des Objekts oder eine zusätzliche Kopie sein.  Das heißt, anstatt zwei Kopien vor Ort aufzubewahren, können Sie eine Kopie in StorageGRID aufbewahren und eine Kopie an den Cloud Storage Pool senden.
 a| 
Ermöglicht einem Mandanten, Objekte automatisch aus einem Bucket in StorageGRID (Quelle) in einen externen S3-Bucket (Ziel) zu replizieren.  Erstellt eine unabhängige Kopie eines Objekts in einer unabhängigen S3-Infrastruktur.



 a| 
Wie ist es eingerichtet?
 a| 
Auf die gleiche Weise wie Speicherpools definiert, mithilfe des Grid Managers oder der Grid Management API.  Kann als Platzierungsort in einer ILM-Regel ausgewählt werden.  Während ein Speicherpool aus einer Gruppe von Speicherknoten besteht, wird ein Cloud-Speicherpool mithilfe eines Remote-S3- oder Azure-Endpunkts (IP-Adresse, Anmeldeinformationen usw.) definiert.
 a| 
Ein Mandantenbenutzerlink:../tenant/configuring-cloudmirror-replication.html["konfiguriert die CloudMirror-Replikation"] durch Definieren eines CloudMirror-Endpunkts (IP-Adresse, Anmeldeinformationen usw.) mithilfe des Tenant Managers oder der S3-API.  Nachdem der CloudMirror-Endpunkt eingerichtet wurde, kann jeder Bucket, der diesem Mandantenkonto gehört, so konfiguriert werden, dass er auf den CloudMirror-Endpunkt verweist.



 a| 
Wer ist für die Einrichtung verantwortlich?
 a| 
Normalerweise ist ein Grid-Administrator
 a| 
Normalerweise ist ein Mieterbenutzer



 a| 
Was ist das Ziel?
 a| 
* Jede kompatible S3-Infrastruktur (einschließlich Amazon S3)
* Azure Blob Archive-Ebene
* Google Cloud Platform (GCP)

 a| 
* Jede kompatible S3-Infrastruktur (einschließlich Amazon S3)
* Google Cloud Platform (GCP)




 a| 
Was bewirkt, dass Objekte zum Ziel verschoben werden?
 a| 
Eine oder mehrere ILM-Regeln in den aktiven ILM-Richtlinien.  Die ILM-Regeln definieren, welche Objekte StorageGRID in den Cloud Storage Pool verschiebt und wann die Objekte verschoben werden.
 a| 
Der Vorgang der Aufnahme eines neuen Objekts in einen Quell-Bucket, der mit einem CloudMirror-Endpunkt konfiguriert wurde.  Objekte, die im Quell-Bucket vorhanden waren, bevor der Bucket mit dem CloudMirror-Endpunkt konfiguriert wurde, werden nicht repliziert, es sei denn, sie werden geändert.



 a| 
Wie werden Objekte abgerufen?
 a| 
Anwendungen müssen Anfragen an StorageGRID stellen, um Objekte abzurufen, die in einen Cloud-Speicherpool verschoben wurden.  Wenn die einzige Kopie eines Objekts in den Archivspeicher übertragen wurde, verwaltet StorageGRID den Wiederherstellungsprozess des Objekts, sodass es abgerufen werden kann.
 a| 
Da es sich bei der gespiegelten Kopie im Ziel-Bucket um eine unabhängige Kopie handelt, können Anwendungen das Objekt abrufen, indem sie Anfragen entweder an StorageGRID oder an das S3-Ziel senden.  Angenommen, Sie verwenden die CloudMirror-Replikation, um Objekte in eine Partnerorganisation zu spiegeln.  Der Partner kann seine eigenen Anwendungen verwenden, um Objekte direkt vom S3-Ziel zu lesen oder zu aktualisieren.  Die Verwendung von StorageGRID ist nicht erforderlich.



 a| 
Können Sie direkt vom Ziel lesen?
 a| 
Nein. In einen Cloud-Speicherpool verschobene Objekte werden von StorageGRID verwaltet.  Leseanforderungen müssen an StorageGRID gerichtet werden (und StorageGRID ist für den Abruf aus dem Cloud Storage Pool verantwortlich).
 a| 
Ja, da es sich bei der gespiegelten Kopie um eine unabhängige Kopie handelt.



 a| 
Was passiert, wenn ein Objekt aus der Quelle gelöscht wird?
 a| 
Das Objekt wird auch aus dem Cloud-Speicherpool gelöscht.
 a| 
Die Löschaktion wird nicht repliziert.  Ein gelöschtes Objekt ist im StorageGRID Bucket nicht mehr vorhanden, im Ziel-Bucket jedoch weiterhin.  Ebenso können Objekte im Ziel-Bucket gelöscht werden, ohne dass dies Auswirkungen auf die Quelle hat.



 a| 
Wie greifen Sie nach einem Desaster (StorageGRID -System nicht betriebsbereit) auf Objekte zu?
 a| 
Ausgefallene StorageGRID Knoten müssen wiederhergestellt werden.  Während dieses Vorgangs können Kopien replizierter Objekte mithilfe der Kopien im Cloud-Speicherpool wiederhergestellt werden.
 a| 
Die Objektkopien im CloudMirror-Ziel sind unabhängig von StorageGRID, sodass auf sie direkt zugegriffen werden kann, bevor die StorageGRID Knoten wiederhergestellt werden.

|===