---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: Ein Cloud-Speicherpool gibt einen einzelnen externen Amazon S3-Bucket oder einen anderen S3-kompatiblen Anbieter oder einen Azure Blob-Speichercontainer an. 
---
= Erstellen Sie einen Cloud-Speicherpool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Cloud-Speicherpool gibt einen einzelnen externen Amazon S3-Bucket oder einen anderen S3-kompatiblen Anbieter oder einen Azure Blob-Speichercontainer an.

Wenn Sie einen Cloud-Speicherpool erstellen, geben Sie den Namen und den Speicherort des externen Buckets oder Containers an, den StorageGRID zum Speichern von Objekten verwenden soll, den Cloud-Anbietertyp (Amazon S3/GCP oder Azure Blob Storage) und die Informationen, die StorageGRID für den Zugriff auf den externen Bucket oder Container benötigt.

StorageGRID validiert den Cloud Storage Pool, sobald Sie ihn speichern. Sie müssen daher sicherstellen, dass der im Cloud Storage Pool angegebene Bucket oder Container vorhanden und erreichbar ist.

.Bevor Sie beginnen
* Sie sind beim Grid Manager angemeldet mit einemlink:../admin/web-browser-requirements.html["unterstützter Webbrowser"] .
* Sie haben dielink:../admin/admin-group-permissions.html["erforderliche Zugriffsberechtigungen"] .
* Sie haben dielink:considerations-for-cloud-storage-pools.html["Überlegungen zu Cloud-Speicherpools"] .
* Der externe Bucket oder Container, auf den der Cloud Storage Pool verweist, ist bereits vorhanden und Sie haben die<<service-endpoint-info,Informationen zum Dienstendpunkt>> .
* Um auf den Eimer oder Behälter zuzugreifen, haben Sie die<<authentication-account-info,Kontoinformationen für den Authentifizierungstyp>> du wirst wählen.


.Schritte
. Wählen Sie *ILM* > *Speicherpools* > *Cloud-Speicherpools*.
. Wählen Sie *Erstellen* und geben Sie dann die folgenden Informationen ein:
+
[cols="1a,3a"]
|===
| Feld | Beschreibung 


 a| 
Name des Cloud-Speicherpools
 a| 
Ein Name, der den Cloud-Speicherpool und seinen Zweck kurz beschreibt.  Verwenden Sie einen Namen, der beim Konfigurieren von ILM-Regeln leicht zu identifizieren ist.



 a| 
Anbietertyp
 a| 
Welchen Cloud-Anbieter verwenden Sie für diesen Cloud-Speicherpool:

** *Amazon S3/GCP*: Wählen Sie diese Option für einen Amazon S3, Commercial Cloud Services (C2S) S3, Google Cloud Platform (GCP) oder einen anderen S3-kompatiblen Anbieter.
** *Azure Blob-Speicher*




 a| 
Eimer oder Behälter
 a| 
Der Name des externen S3-Buckets oder Azure-Containers.  Sie können diesen Wert nicht mehr ändern, nachdem der Cloud-Speicherpool gespeichert wurde.

|===
. [[service-endpoint-info]]Geben Sie basierend auf Ihrem ausgewählten Providertyp die Service-Endpunktinformationen ein.
+
[role="tabbed-block"]
====
.Amazon S3/GCP
--
.. Wählen Sie als Protokoll entweder HTTPS oder HTTP aus.
+

NOTE: Verwenden Sie keine HTTP-Verbindungen für vertrauliche Daten.

.. Geben Sie den Hostnamen ein. Beispiel:
+
`s3-_aws-region_.amazonaws.com`

.. Wählen Sie den URL-Stil aus:
+
[cols="1a,3a"]
|===
| Option | Beschreibung 


 a| 
Automatische Erkennung
 a| 
Versuchen Sie, anhand der bereitgestellten Informationen automatisch zu erkennen, welcher URL-Stil verwendet werden soll.  Wenn Sie beispielsweise eine IP-Adresse angeben, verwendet StorageGRID eine URL im Pfadstil.  Wählen Sie diese Option nur, wenn Sie nicht wissen, welchen bestimmten Stil Sie verwenden sollen.



 a| 
Virtuell gehosteter Stil
 a| 
Verwenden Sie eine URL im virtuell gehosteten Stil, um auf den Bucket zuzugreifen.  URLs im virtuell gehosteten Stil enthalten den Bucket-Namen als Teil des Domänennamens.  Beispiel: `+https://bucket-name.s3.company.com/key-name+`



 a| 
Pfad-Stil
 a| 
Verwenden Sie eine URL im Pfadstil, um auf den Bucket zuzugreifen.  URLs im Pfadstil enthalten am Ende den Bucket-Namen.  Beispiel: `+https://s3.company.com/bucket-name/key-name+`

*Hinweis:* Die URL-Option im Pfadstil wird nicht empfohlen und wird in einer zukünftigen Version von StorageGRID veraltet sein.

|===
.. Geben Sie optional die Portnummer ein oder verwenden Sie den Standardport: 443 für HTTPS oder 80 für HTTP.


--
.Azure Blob Storage
--
.. Geben Sie die URI für den Service-Endpunkt in einem der folgenden Formate ein.
+
*** `+https://host:port+`
*** `+http://host:port+`




Beispiel: `https://_myaccount_.blob.core.windows.net:443`

Wenn Sie keinen Port angeben, wird standardmäßig Port 443 für HTTPS und Port 80 für HTTP verwendet.

--
====


. [[authentication-account-info]]Wählen Sie *Weiter*.  Wählen Sie dann den Authentifizierungstyp aus und geben Sie die erforderlichen Informationen für den Cloud Storage Pool-Endpunkt ein:
+
[role="tabbed-block"]
====
.Zugriffsschlüssel
--
_Für Amazon S3/GCP oder andere S3-kompatible Anbieter_

.. *Zugriffsschlüssel-ID*: Geben Sie die Zugriffsschlüssel-ID für das Konto ein, dem der externe Bucket gehört.
.. *Geheimer Zugriffsschlüssel*: Geben Sie den geheimen Zugriffsschlüssel ein.


--
.IAM-Rollen überall
--
_Für den AWS IAM Roles Anywhere-Dienst_

StorageGRID verwendet den AWS Security Token Service (STS), um dynamisch ein kurzlebiges Token für den Zugriff auf AWS-Ressourcen zu generieren.

.. *AWS IAM Roles Anywhere-Region*: Wählen Sie die Region für den Cloud-Speicherpool aus. Beispiel:  `us-east-1` .
.. *Trust Anchor URN*: Geben Sie die URN des Trust Anchor ein, der Anfragen für kurzlebige STS-Anmeldeinformationen validiert.  Kann eine Stamm- oder Zwischenzertifizierungsstelle sein.
.. *Profil-URN*: Geben Sie die URN des IAM Roles Anywhere-Profils ein, das die Rollen auflistet, die für jede vertrauenswürdige Person übernommen werden können.
.. *Rollen-URN*: Geben Sie die URN der IAM-Rolle ein, die für jeden vertrauenswürdigen Benutzer übernommen werden kann.
.. *Sitzungsdauer*: Geben Sie die Dauer der temporären Sicherheitsanmeldeinformationen und der Rollensitzung ein.  Geben Sie mindestens 15 Minuten und höchstens 12 Stunden ein.
.. *Server-CA-Zertifikat* (optional): Ein oder mehrere vertrauenswürdige CA-Zertifikate im PEM-Format zur Überprüfung des IAM Roles Anywhere-Servers.  Wenn es weggelassen wird, wird der Server nicht überprüft.
.. *Endentitätszertifikat*: Der öffentliche Schlüssel im PEM-Format des vom Vertrauensanker signierten X509-Zertifikats.  AWS IAM Roles Anywhere verwendet diesen Schlüssel, um ein STS-Token auszustellen.
.. *Privater End-Entity-Schlüssel*: Der private Schlüssel für das End-Entity-Zertifikat.


--
.CAP (C2S-Zugangsportal)
--
_Für Commercial Cloud Services (C2S) S3-Dienst_

.. *URL für temporäre Anmeldeinformationen*: Geben Sie die vollständige URL ein, die StorageGRID verwendet, um temporäre Anmeldeinformationen vom CAP-Server abzurufen, einschließlich aller erforderlichen und optionalen API-Parameter, die Ihrem C2S-Konto zugewiesen sind.
.. *Server-CA-Zertifikat*: Wählen Sie *Durchsuchen* und laden Sie das CA-Zertifikat hoch, das StorageGRID zur Überprüfung des CAP-Servers verwenden wird.  Das Zertifikat muss PEM-kodiert und von einer entsprechenden staatlichen Zertifizierungsstelle (CA) ausgestellt sein.
.. *Client-Zertifikat*: Wählen Sie *Durchsuchen* und laden Sie das Zertifikat hoch, mit dem StorageGRID sich beim CAP-Server identifiziert.  Das Client-Zertifikat muss PEM-codiert sein, von einer entsprechenden staatlichen Zertifizierungsstelle (CA) ausgestellt worden sein und Zugriff auf Ihr C2S-Konto haben.
.. *Privater Schlüssel des Clients*: Wählen Sie *Durchsuchen* und laden Sie den PEM-codierten privaten Schlüssel für das Client-Zertifikat hoch.
.. Wenn der private Schlüssel des Clients verschlüsselt ist, geben Sie die Passphrase zum Entschlüsseln des privaten Schlüssels des Clients ein.  Andernfalls lassen Sie das Feld *Passphrase für den privaten Clientschlüssel* leer.



NOTE: Wenn das Client-Zertifikat verschlüsselt wird, verwenden Sie das herkömmliche Format für die Verschlüsselung.  Das verschlüsselte PKCS #8-Format wird nicht unterstützt.

--
.Azure Blob Storage
--
_Für Azure Blob Storage, nur gemeinsam genutzter Schlüssel_

.. *Kontoname*: Geben Sie den Namen des Speicherkontos ein, dem der externe Container gehört
.. *Kontoschlüssel*: Geben Sie den geheimen Schlüssel für das Speicherkonto ein


Sie können diese Werte über das Azure-Portal ermitteln.

--
.Anonym
--
Es sind keine weiteren Angaben erforderlich.

--
====
. Wählen Sie *Weiter*. Wählen Sie dann die Art der Serverüberprüfung aus, die Sie verwenden möchten:
+
[cols="1a,2a"]
|===
| Option | Beschreibung 


 a| 
Verwenden Sie Stamm-CA-Zertifikate im Storage Node OS
 a| 
Verwenden Sie die auf dem Betriebssystem installierten Grid CA-Zertifikate, um Verbindungen zu sichern.



 a| 
Benutzerdefiniertes CA-Zertifikat verwenden
 a| 
Verwenden Sie ein benutzerdefiniertes CA-Zertifikat.  Wählen Sie *Durchsuchen* und laden Sie das PEM-codierte Zertifikat hoch.



 a| 
Zertifikat nicht überprüfen
 a| 
Wenn Sie diese Option auswählen, sind TLS-Verbindungen zum Cloud-Speicherpool nicht sicher.

|===
. Wählen Sie *Speichern*.
+
Wenn Sie einen Cloud-Speicherpool speichern, führt StorageGRID Folgendes aus:

+
** Überprüft, ob der Bucket oder Container und der Service-Endpunkt vorhanden sind und ob sie mit den von Ihnen angegebenen Anmeldeinformationen erreicht werden können.
** Schreibt eine Markierungsdatei in den Bucket oder Container, um ihn als Cloud-Speicherpool zu identifizieren.  Entfernen Sie niemals diese Datei mit dem Namen `x-ntap-sgws-cloud-pool-uuid` .
+
Wenn die Validierung des Cloud Storage Pools fehlschlägt, erhalten Sie eine Fehlermeldung mit der Erklärung, warum die Validierung fehlgeschlagen ist.  Beispielsweise kann ein Fehler gemeldet werden, wenn ein Zertifikatsfehler vorliegt oder wenn der von Ihnen angegebene Bucket oder Container noch nicht vorhanden ist.



. Wenn ein Fehler auftritt, lesen Sie dielink:troubleshooting-cloud-storage-pools.html["Anweisungen zur Fehlerbehebung bei Cloud-Speicherpools"] , beheben Sie alle Probleme und versuchen Sie dann erneut, den Cloud-Speicherpool zu speichern.

