---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: Sie können die letzte Zugriffszeit als Referenzzeit in einer ILM-Regel verwenden.  Beispielsweise möchten Sie möglicherweise Objekte, die in den letzten drei Monaten angezeigt wurden, auf lokalen Speicherknoten belassen und Objekte, die nicht so kürzlich angezeigt wurden, an einen externen Standort verschieben.  Sie können die letzte Zugriffszeit auch als erweiterten Filter verwenden, wenn eine ILM-Regel nur auf Objekte angewendet werden soll, auf die zuletzt an einem bestimmten Datum zugegriffen wurde. 
---
= Verwenden der letzten Zugriffszeit in ILM-Regeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die letzte Zugriffszeit als Referenzzeit in einer ILM-Regel verwenden.  Beispielsweise möchten Sie möglicherweise Objekte, die in den letzten drei Monaten angezeigt wurden, auf lokalen Speicherknoten belassen und Objekte, die nicht so kürzlich angezeigt wurden, an einen externen Standort verschieben.  Sie können die letzte Zugriffszeit auch als erweiterten Filter verwenden, wenn eine ILM-Regel nur auf Objekte angewendet werden soll, auf die zuletzt an einem bestimmten Datum zugegriffen wurde.

.Informationen zu diesem Vorgang
Bevor Sie die letzte Zugriffszeit in einer ILM-Regel verwenden, sollten Sie die folgenden Überlegungen berücksichtigen:

* Wenn Sie die letzte Zugriffszeit als Referenzzeit verwenden, beachten Sie, dass das Ändern der letzten Zugriffszeit für ein Objekt keine sofortige ILM-Auswertung auslöst.  Stattdessen werden die Platzierungen des Objekts bewertet und das Objekt wird nach Bedarf verschoben, wenn ILM das Objekt im Hintergrund auswertet.  Dies kann nach dem Zugriff auf das Objekt zwei Wochen oder länger dauern.
+
Berücksichtigen Sie diese Latenz beim Erstellen von ILM-Regeln basierend auf der letzten Zugriffszeit und vermeiden Sie Platzierungen mit kurzen Zeiträumen (weniger als ein Monat).

* Wenn Sie die letzte Zugriffszeit als erweiterten Filter oder als Referenzzeit verwenden, müssen Sie die Aktualisierung der letzten Zugriffszeit für S3-Buckets aktivieren.  Sie können dielink:../tenant/enabling-or-disabling-last-access-time-updates.html["Mietermanager"] oder dielink:../s3/put-bucket-last-access-time-request.html["Mandantenverwaltungs-API"] .
+

NOTE: Aktualisierungen der letzten Zugriffszeit sind für S3-Buckets standardmäßig deaktiviert.

+

NOTE: Beachten Sie, dass die Aktivierung von Updates zur letzten Zugriffszeit die Leistung beeinträchtigen kann, insbesondere in Systemen mit kleinen Objekten.  Die Leistungseinbußen entstehen dadurch, dass StorageGRID die Objekte bei jedem Abrufen mit neuen Zeitstempeln aktualisieren muss.



In der folgenden Tabelle ist zusammengefasst, ob die letzte Zugriffszeit für alle Objekte im Bucket für verschiedene Arten von Anforderungen aktualisiert wird.

[cols="1a,1a,1a"]
|===
| Art der Anfrage | Ob die Zeit des letzten Zugriffs aktualisiert wird, wenn die Aktualisierung der Zeit des letzten Zugriffs deaktiviert ist | Ob die Zeit des letzten Zugriffs aktualisiert wird, wenn die Aktualisierung der Zeit des letzten Zugriffs aktiviert ist 


 a| 
Anforderung zum Abrufen eines Objekts, seiner Zugriffskontrollliste oder seiner Metadaten
 a| 
Nein
 a| 
Ja



 a| 
Anforderung zum Aktualisieren der Metadaten eines Objekts
 a| 
Ja
 a| 
Ja



 a| 
Anforderung zum Kopieren eines Objekts von einem Bucket in einen anderen
 a| 
* Nein, für die Quellkopie
* Ja, für die Zielkopie

 a| 
* Ja, für die Quellkopie
* Ja, für die Zielkopie




 a| 
Anfrage zum Abschließen eines mehrteiligen Uploads
 a| 
Ja, für das montierte Objekt
 a| 
Ja, für das montierte Objekt

|===